### ISSUE TITLE
Problem with reconciliation

### ISSUE THREAD

**Issue by vitobotta** [firefly-iii/firefly-iii#2208] opened 2019-04-04 17:34 UTC
I am running Firefly III version 4.7.17 and I seem to have a problem with reconciliation, unless I misunderstand how it works ... See attachment. If I go to reconcile an account today, the difference as shown on the right under "Reconciliation options" is zero, as expected. However when I try to store the reconciliation, under "Overview of reconciliation" it offers to remove 1972.62 from the account to clear a difference. I have no idea of what that amount is or how it is calculated. Any ideas? Thanks!
<img width="1364" alt="Screenshot 2019-04-04 at 20 27 28" src="https://user-images.githubusercontent.com/283811/55576016-e982b600-5718-11e9-85ba-e214ad8e9585.png">

**Comment by JC5** [comment] 2019-04-04 19:32
It could be a bug, I have to check. Thanks for letting me know. An upgrade of the code is underway for the next big release.

**Comment by M-Paladin** [comment] 2019-05-02 13:14
Hello,

I have the same problem as you can see
![Capture du 2019-05-02 15-10-35](https://user-images.githubusercontent.com/49365410/57077506-84f15180-6cec-11e9-9010-f9c7a6848df4.png)

But I found where it comes from
![Capture du 2019-05-02 15-12-30](https://user-images.githubusercontent.com/49365410/57077590-bb2ed100-6cec-11e9-82d3-e385fa5f984d.png)

The differences is coming from two transactions that aren't in the chosen period but they appear and they count

**Comment by vitobotta** [comment] 2019-05-06 14:10
I still have this problem and I don't know how to fix. For example my checking account balance is now 2683.38, all transactions have been cleared/reconciled but Firefly says the balance is 1941.18. When I try to reconcile, it asks me for a start balance with date and amount, but I have no idea of what I should enter there. If I enter the balance at the very beginning (March 4) and then I enter the current balance as of today, when I click "Store reconciliation" I see a dialog as in the attachment which suggests to subtracts 2000 euros, which will make things worse...

Any help on how to fix the balance would be much appreciated :)

<img width="896" alt="Screenshot 2019-05-06 at 17 07 45" src="https://user-images.githubusercontent.com/283811/57230754-ba19de80-7021-11e9-87c3-1e473bc4abc7.png">

**Comment by vitobotta** [comment] 2019-05-06 14:42
Uhm, as starting balance I entered the balance as of the 1st and now it seems to be correct. I guess I was missing something obvious on how it works...

**Comment by M-Paladin** [comment] 2019-05-07 11:17
I made another test thanks to Firefox

At the beginning, here's the state
![Capture du 2019-05-07 13-10-46](https://user-images.githubusercontent.com/49365410/57295176-3d8f0a80-70ca-11e9-9819-6a5185a639d2.png)

Then, I use the functionality to examine the element
This allow me to delete the nodes outside of asked period
![Capture du 2019-05-07 13-11-35](https://user-images.githubusercontent.com/49365410/57295273-6c0ce580-70ca-11e9-865f-0847633bf9ac.png)

After that, values are correct
![Capture du 2019-05-07 13-12-14](https://user-images.githubusercontent.com/49365410/57295305-7af39800-70ca-11e9-97e0-8a60621bfd8a.png)

**Comment by M-Paladin** [comment] 2019-05-07 11:35
However, there's another bug with already reconciled transaction within the period
![Capture du 2019-05-07 13-24-43](https://user-images.githubusercontent.com/49365410/57295811-98753180-70cb-11e9-84dd-b4de4c93a157.png)

Instead of substract them, it adds them
In my example :
Start Balance (0) + Selected Transactions (24841.19) + Already Cleared Transaction (23724.89) - End Balance (1116.3) = Difference (47449.78)
It should be :
Start Balance (0) + Selected Transactions (24841.19) **-** Already Cleared Transaction (23724.89) - End Balance (1116.3) = Difference (0)

Maybe it's coming from the fact that already cleared transaction are all Transfer.
And as every transfer have a positive value displayed even if it's leaving the account, maybe it can be the source of the bug.

**Comment by vitobotta** [comment] 2019-05-07 11:36
In my case I think I fixed the current balance by entering the correct known balance at some date as the starting balance.

**Comment by M-Paladin** [comment] 2019-05-10 21:06
ok I found the solution I think.
I tested it and it seems to be ok for the two problems encountered.

Here's the source file I modified on my install
https://github.com/firefly-iii/firefly-iii/blob/f57fc06347fb3e5fcab1c662ac198d9248eb6ee4/app/Http/Controllers/Json/ReconcileController.php

From line 154
```
        foreach ($cleared as $transaction) {
            if ($transaction->date <= $end) {
                $clearedAmount = bcadd($clearedAmount, $transaction->transaction_amount); // @codeCoverageIgnore
                ++$countCleared;
            }
        }
        $difference  = bcadd(bcadd(bcsub($startBalance, $endBalance), $clearedAmount), $amount);
```
I read the "foreach loop" above this one (line 116) and here's the new code I created from it (maybe not the better one)
```
        foreach ($cleared as $transaction) {
            if ($transaction->date <= $end && $transaction->date >= $start) {
                $srcAccount  = $this->accountRepos->findNull((int)$transaction->account_id);
                $dstAccount  = $this->accountRepos->findNull((int)$transaction->opposing_account_id);
                $srcCurrency = (int)$this->accountRepos->getMetaValue($srcAccount, 'currency_id');
                $dstCurrency = (int)$this->accountRepos->getMetaValue($dstAccount, 'currency_id');

                // is $account source or destination?
                if ($account->id === $srcAccount->id) {
                    // source, and it matches the currency id or is 0
                    if ($srcCurrency === $transaction->transaction_currency_id || 0 === $srcCurrency) {
                        Log::debug(sprintf('Source matches currency: %s', $transaction->transaction_amount));
                        $clearedAmount = bcadd($clearedAmount, $transaction->transaction_amount);
                        ++$countCleared;
                    }
                    // destination, and it matches the foreign currency ID.
                    if ($srcCurrency === $transaction->foreign_currency_id) {
                        Log::debug(sprintf('Source matches foreign currency: %s', $transaction->transaction_foreign_amount));
                        $clearedAmount = bcadd($clearedAmount, $transaction->transaction_foreign_amount);
                        ++$countCleared;
                    }
                }

                if ($account->id === $dstAccount->id) {
                    // destination, and it matches the currency id or is 0
                    if ($dstCurrency === $transaction->transaction_currency_id || 0 === $dstCurrency) {
                        Log::debug(sprintf('Destination matches currency: %s', app('steam')->negative($transaction->transaction_amount)));
                        $clearedAmount = bcadd($clearedAmount, app('steam')->negative($transaction->transaction_amount));
                        ++$countCleared;
                    }
                    // destination, and it matches the foreign currency ID.
                    if ($dstCurrency === $transaction->foreign_currency_id) {
                        Log::debug(sprintf('Destination matches foreign currency: %s', $transaction->transaction_foreign_amount));
                        $clearedAmount = bcadd($clearedAmount, $transaction->transaction_foreign_amount);
                        ++$countCleared;
                    }
                }
                //$clearedAmount = bcadd($clearedAmount, $transaction->transaction_amount); // @codeCoverageIgnore
                //++$countCleared;
            }
        }
        $difference  = bcadd(bcadd(bcsub($startBalance, $endBalance), $clearedAmount), $amount);

```
If some of you can test it, it could be interesting.

**Comment by JbalTero** [comment] 2019-06-06 14:53
@JC5 The code above by @M-Paladin fixed it for me.

**Comment by JbalTero** [comment] 2019-06-06 14:56
Here's the screenshot of reconcile process. The difference expected should be 7, but I got ₱73,227.00.
![image](https://user-images.githubusercontent.com/3615746/59043016-1042a180-88ae-11e9-823c-bd0d2e79b0fb.png)
------------
After @M-Paladin code, it is fixed correctly to 7.

![image](https://user-images.githubusercontent.com/3615746/59042948-f2753c80-88ad-11e9-86c5-e7a39df166b4.png)

**Comment by JC5** [comment] 2019-06-22 11:18
I've cleaned up the code and did some digging into this issue for the new release.

Could you check if you can replicate the problem on the [dev instance](https://dev.firefly-iii.org/)? The login is `demo@firefly` / `demo`, just like the demo site.

**Comment by JbalTero** [comment] 2019-06-22 12:36
Unfortunately, i can't have the time to look into this right now

**Comment by vitobotta** [comment] 2019-07-10 17:25
Hi, I am still having this problem but I am using Docker, so it doesn't make much sense to change the code in the container... Any update? :)

**Comment by vitobotta** [comment] 2019-07-10 17:31
Actually I tried now... I made the change and when I did "Store reconciliation" it offered to add/subtract the correct difference, but the end balances are still wrong. "Less wrong", but still wrong :D

**Comment by polystratus** [comment] 2019-07-11 21:02
try to replace firefly-iii/public/v1/js/ff/accounts/reconcile.js code line 87-93 to

``` 
    var cleared = [];
    $.each($('input[class="cleared"]'), function (i, v) {
        var obj = $(v);
        // add only transactions in range
        if(obj.data('inrange') === true){ 
            console.log('Added item with amount to list of cleared ' + obj.val());
            // todo here we need to check previous transactions etc.
            cleared.push(obj.data('id'));
        }
    });
```

**Comment by JC5** [comment] 2019-07-12 11:13
Are you testing this on 4.7.17 or 4.8.0?

**Comment by polystratus** [comment] 2019-07-12 12:06
4.7.17

**Comment by JC5** [comment] 2019-07-12 13:20
OK. The issue is (probably) already resolved in the next release. You can test this on https://dev.firefly-iii.org/ (same login as the demo site)

**Comment by vitobotta** [comment] 2019-07-13 18:02
Hi @JC5 I would like to try 4.8.0 with my data to see if the problem is gone. When are you planning to release the new docker image? Thanks!

**Comment by JC5** [comment] 2019-07-13 18:10
You could use the `develop` tag. The new release won't be due for some time yet.

**Comment by vitobotta** [comment] 2019-07-13 18:16
Are there still big bugs etc in the dev version? Is it safe to use now?

**Comment by JC5** [comment] 2019-07-13 18:18
I haven't tested the docker upgrade yet although the normal upgrade works fine. Make a backup, and use it at your own risk.

**Comment by vitobotta** [comment] 2019-07-15 14:12
Hi @JC5, I have upgraded a copy of my Docker instance/data to 'develop'. After a few reconciliation attempts, for example with a credit card, the current balance according to Firefly is -1,258.54;  I entered the balance as of July 8 according to my bank -1248.55, and the current balance, -1257.92. `Reconciliation options` shows 1.24 difference which sounds incorrect because -1258.54 + 1257.92 is 0.62. When I click on `Store reconciliation` it shows a zero difference as you can see in the picture. I don't understand the numbers. What I am doing wrong? Thanks

<img width="894" alt="Screenshot 2019-07-15 at 17 05 27" src="https://user-images.githubusercontent.com/283811/61222641-c4441180-a723-11e9-8a42-67515b068b23.png">

**Comment by JC5** [comment] 2019-08-03 04:00
I don't know, I don't have enough to go on. I've fixed a few edge cases in the latest version. For now, I have to consider this fixed (I can't create anymore cases where the numbers are off).

**Closed** 2019-08-09 19:04 UTC
Labels: bug, fixed
