### ISSUE TITLE
Firefly III docker image for Raspberry Pi 3

### ISSUE THREAD

**Issue by SIGISLV** [firefly-iii/firefly-iii#1464] opened 2018-06-04 05:29 UTC
Hi everyone,
thank you for that app it was axactly what I was seaching for.
I tried to install firefly III on a rapberry pi 3 with docker but my container died before working.
Is there anybody who can help me make it work ?

Also I couldn't be able to docker-compose the architecture.

It might not work on rpi3

**Comment by JC5** [comment] 2018-06-04 06:03
Hi,

Thanks for the compliments!

The RP3 uses a different processor architecture, so the Docker image will not work by default. In order for Firefly III to work on a RP3 the whole Dockerfile needs to be rewritten. I'll put it on the list :).

**Comment by JC5** [comment] 2018-07-31 03:42
I'll have to do some digging, I am not an expert either! I noticed the cron job doesn't work well either so plenty of tasks there :D.

**Comment by JC5** [comment] 2018-07-31 03:43
Thanks for the information btw, I appreciate your digging around. :+1:

**Comment by dicastro** [comment] 2018-08-02 21:42
Hi!

@JC5  I love FireflyIII!! This is exactly what I've been planning to do during several years. It seems you've read my mind. Its awesome!

Following what @ErikFontanel has said in his comment, I've achieved to have FireflyIII running on a Raspberry Pi 3 b+. This is what I've done:

## Changes in the __Dockerfile__

- I've changed the `FROM` by this `FROM arm32v7/php:7.2.8-apache-stretch`
- I've commented the following part:
```
# Install latest curl
#RUN cd /tmp && \
#    wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz && \
#    tar -xvf openssl-${OPENSSL_VERSION}.tar.gz && \
#    cd openssl-${OPENSSL_VERSION} && \
#    ./config && \
#    make && \
#    make install

#RUN cd /tmp && \
#    wget https://curl.haxx.se/download/curl-${CURL_VERSION}.tar.gz && \
#    tar -xvf curl-${CURL_VERSION}.tar.gz && \
#    cd curl-${CURL_VERSION} && \
#    ./configure --with-ssl && \
#    make && \
#    make install
```

This is the final _Dockerfile_:

```
# use PHP 7.1 and Apache as a base.
FROM arm32v7/php:7.2.8-apache-stretch

# set working dir
ENV FIREFLY_PATH /var/www/firefly-iii
ENV CURL_VERSION 7.60.0
ENV OPENSSL_VERSION 1.1.1-pre6
WORKDIR $FIREFLY_PATH
ADD . $FIREFLY_PATH

# install packages
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends libcurl4-openssl-dev \
                                               zlib1g-dev \
                                               libjpeg62-turbo-dev \
                                               wget \
                                               libpng-dev \
                                               libicu-dev \
                                               libedit-dev \
                                               libtidy-dev \
                                               libxml2-dev \
                                               libsqlite3-dev \
                                               libpq-dev \
                                               libbz2-dev \
                                               gettext-base \
                                               cron \
                                               locales && \
                                               apt-get clean && \
                                               rm -rf /var/lib/apt/lists/*

# Setup the Composer installer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install latest curl
#RUN cd /tmp && \
#    wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz && \
#    tar -xvf openssl-${OPENSSL_VERSION}.tar.gz && \
#    cd openssl-${OPENSSL_VERSION} && \
#    ./config && \
#    make && \
#    make install

#RUN cd /tmp && \
#    wget https://curl.haxx.se/download/curl-${CURL_VERSION}.tar.gz && \
#    tar -xvf curl-${CURL_VERSION}.tar.gz && \
#    cd curl-${CURL_VERSION} && \
#    ./configure --with-ssl && \
#    make && \
#    make install


# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Setup cron job
RUN (crontab -l ; echo "* * * * * root $FIREFLY_PATH/artisan schedule:run >> /var/log/cron.log") | crontab

# Install PHP exentions.
RUN docker-php-ext-install -j$(nproc) curl gd intl json readline tidy zip bcmath xml mbstring pdo_sqlite pdo_mysql bz2 pdo_pgsql

# Generate locales supported by Firefly III
RUN echo "en_US.UTF-8 UTF-8\nde_DE.UTF-8 UTF-8\nfr_FR.UTF-8 UTF-8\nit_IT.UTF-8 UTF-8\nnl_NL.UTF-8 UTF-8\npl_PL.UTF-8 UTF-8\npt_BR.UTF-8 UTF-8\nru_RU.UTF-8 UTF-8\ntr_TR.UTF-8 UTF-8\n\n" > /etc/locale.gen && locale-gen

# copy Apache config to correct spot.
COPY ./.deploy/docker/apache2.conf /etc/apache2/apache2.conf

# Enable apache mod rewrite..
RUN a2enmod rewrite

# Enable apache mod ssl..
RUN a2enmod ssl

# Create volumes for several directories:
VOLUME $FIREFLY_PATH/storage/export $FIREFLY_PATH/storage/upload

# Enable default site (Firefly III)
COPY ./.deploy/docker/apache-firefly.conf /etc/apache2/sites-available/000-default.conf

# Make sure we own Firefly III directory
RUN chown -R www-data:www-data /var/www && chmod -R 775 $FIREFLY_PATH/storage

# Run composer
RUN composer install --prefer-dist --no-dev --no-scripts --no-suggest

# Expose port 80
EXPOSE 80

# Run the command on container startup
CMD cron

# Run entrypoint thing
ENTRYPOINT [".deploy/docker/entrypoint.sh"]
```

## Changes in the `docker-compose.yml`

This is my `docker-compose.yml` file:

```
--- 
networks: 
  firefly_iii_net: 
    driver: bridge
services: 
  firefly_iii_app: 
    environment: 
      - FF_DB_HOST=firefly_iii_db
      - FF_DB_NAME=firefly_db
      - FF_DB_USER=firefly_db
      - FF_DB_PASSWORD=firefly_db_secret
      - FF_APP_KEY=S0m3R@nd0mStr1ngOf32Ch@rsEx@ctly
      - FF_APP_ENV=local
      - TZ=Europe/Madrid
    build:
      context: ./firefly_iii_app
    image: qopuir/firefly-iii:4.7.5.3
    links: 
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    ports: 
      - "80:80"
    volumes: 
      - 
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      - 
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
  firefly_iii_db: 
    environment: 
      - MYSQL_DATABASE=firefly_db
      - MYSQL_USER=firefly_db
      - MYSQL_PASSWORD=firefly_db_secret
      - MYSQL_ROOT_PASSWORD=firefly_root_secret
    image: "yobasystems/alpine-mariadb:arm32v7"
    networks: 
      - firefly_iii_net
    volumes: 
      - "firefly_iii_db:/var/lib/mysql"
version: "3.2"
volumes: 
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~
```

## Multiarch docker images

In [this](https://blog.docker.com/2017/11/multi-arch-all-the-things/) article there is an introduction to multiarchitecture docker images.

It should be great to have FireflyIII in Docker Hub ready to run in RPI!!

**Comment by JC5** [comment] 2018-08-08 12:33
Yes, I apologise for not replying. I had it on my todo list for the past weekend but it was a billion degrees here so I spent my time in the pool instead. Will pick this up asap. I am interested and want to move forward with the perfect docker file

**Comment by MichelFreund** [comment] 2018-08-10 18:34
Would be absolutely great if there was a Raspberry Pi 3 image or docker file. Thanks dicastro, will follow your hints to install on my Raspberry Pi 3.

**Comment by ErikFontanel** [comment] 2018-08-12 14:00
@JC5 

I haven't tried it yet, but how about the other way around? Using the official PHP image and `apt-get install supervisor`? See [approach 2](https://stackoverflow.com/a/44201082).

**Comment by JC5** [comment] 2018-08-12 17:59
No that would be too easy :wink:

Perhaps this week if I have time during the evenings. Thanks for the pointer! :grin: I looked at something similar but I couldn't make it work.

**Comment by ErikFontanel** [comment] 2018-08-12 21:44
I thought I experience issues with installing curl and thus disabled it par @dicastro's instructions. Just checked, but my current FFiii image running on my RPi has cURL `curl 7.60.0 (armv7l-unknown-linux-gnueabihf)` installed. I downloaded SSL and cURL and compiled it from source. Not sure yet why the current Dockerfile fails exactly, but I'll try to reproduce the process and pay attention to the cURL installation (it just takes a while ;)).

**Comment by ErikFontanel** [comment] 2018-08-13 13:33
okay little update, the current Dockerfile builds okay on a Raspberry Pi, including updating cURL (it just takes ~2h). The problem is that build process fails on line 59 (as in my [previous comment](https://github.com/firefly-iii/firefly-iii/issues/1464#issuecomment-411380936)) when the PHP extensions are installed.

Since curl is already part of the php image, it shouldn't be necessary to install the curl extension again.  The solution is seems easy, remove curl from the list. But as with a lot of stuff, it's usually not that easy ;). I'm not sure if compiling and installing a newer curl also influences the curl php extension. I'm not familiar enough with the inner workings of FFF so I haven't ran any tests yet. Is there a way to test the bunq import? 

Adding supervisor should not be that hard, but is that necessary to fix the cronjob? Or is that failing for another reason?

Anyway, I think I have something cooking, I'll send a PR tomorrowish.

**Comment by JC5** [comment] 2018-08-13 13:41
@OGKevin updated cURL originally to support bunq. He can answer some questions about the bunq API as well.

To get a sandbox key, you can go to https://www.bunq.com/developer and follow the instructions. This key can be used in FF3 (check out the .env file too).

**Comment by OGKevin** [comment] 2018-08-13 13:52
The updated curl is needed due to https://github.com/bunq/sdk_php/issues/7

**Comment by dicastro** [comment] 2018-08-13 14:34
@ErikFontanel

I didn't know that Docker figured out automatically which architecture to use. I will try it.

@JC5

Why it is _supervisor_ needed to run a cron job? Why _crontab_ is not enough?

I have installed crontab in some images:

```
# rsyslog is used by crontab for the logs

> apt-get install rsyslog crontab
```

To initialize the crontab:

```
> crontab <FILE_HAVING_CRON_JOB_DEFINITIONS>
```

Then in the entrypoint script:

```
service rsyslog start
service cron start
```

If _supervisor_ is a requirement, why what @ErikFontanel has proposed (`apt-get install supervisor`) is _too easy_?

I have also done that in many images without any issues.

Well, what I've done exactly to install _supervisor_ is:

```
> apt-get install python-setuptools

> easy_install supervisor
```

Define `SUPERVISOR_HOME` environment variable:

```
ENV SUPERVISOR_HOME <USER_HOME>/supervisor
```

Create a _log_ folder in `SUPERVISOR_HOME`:

```
mkdir -p ${SUPERVISOR_HOME}/log
```

Create `supervisord.conf` file in the user's home folder (~/supervisor/supervisord.conf):

```conf
[unix_http_server]
file=%(ENV_SUPERVISOR_HOME)s/supervisor.sock
chmod=0700
username = dummy
password = dummy

[supervisord]
nodaemon=true
user=root
logfile=%(ENV_SUPERVISOR_HOME)s/log/supervisord.log
pidfile=%(ENV_SUPERVISOR_HOME)s/supervisord.pid
childlogdir=%(ENV_LOCKEN_HOME)s/log

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix://%(ENV_SUPERVISOR_HOME)s/supervisor.sock
username = dummy
password = dummy
```

Add the following alias into the user's `.bashrc` file:

```
alias supervisorctl="supervisorctl -c $SUPERVISOR_HOME/supervisord.conf"
```

Define the `CMD` of the `Dockerfile` as:

```
CMD ["/usr/local/bin/supervisord", "-c", "<USER_HOME>/supervisor/supervisord.conf"]
```

**Comment by JC5** [comment] 2018-08-13 15:45
So I was under the impression that single Docker images wouldn't "just" run a cronjob out of the box like that. Hence the need for supervisor or other creative solutions. If that's not true than it's easy.

**Comment by JC5** [comment] 2018-08-13 16:01
@chrif, I could use your help here as well. Could you read the thread and give us your thoughts? I appreciate your input.

**Comment by ErikFontanel** [comment] 2018-08-13 17:38
@JC5 
some will argue that cron jobs belong in a separate container or should be run on the host machine because of the 'single purpose/process' philosophy, however in this case I think that's a bit overkill

**Comment by chrif** [comment] 2018-08-13 22:00
@JC5 I have no experience with Raspberry Pi so I can't comment on that. I never had success with background processes in a container and yes it is best practice to avoid it. As for supervisor, I would definitely install it myself instead of moving to a third party image. I mentioned webdevops/php-nginx:7.2 just as an example. Sorry if I gave the impression that it was a recommendation.

**Comment by JC5** [comment] 2018-08-14 04:43
No problem @crif! I'm also learning :grin:.

With all of you helping out we can build the perfect docker file :+1:

**Comment by ErikFontanel** [comment] 2018-08-15 13:01
As far as I know there are no plans for mysql/mariadb to support ARM (see [this comment](https://github.com/docker-library/mysql/issues/318#issuecomment-339460074) for some background). 

just thinking out loud: 
A possible solution could be using an [additional yaml](https://docs.docker.com/compose/extends/) ie. `docker-compose.arm.yml` for RPi/other platforms. This compose-file shouldn't have to be part of the repo, just only instructions for the RPi users.

But a unified solution would be better of course.

**Comment by JC5** [comment] 2018-08-15 15:16
Firefly III can handle Postgres just fine, and I don't mind moving towards Postgres. Any particular image you guys recommend?

**Comment by JC5** [comment] 2018-08-15 16:57
Should have known :grin: I'll go and experiment :D

**Comment by Richyread** [comment] 2018-08-16 22:40
> the end of the thread shines some arm light, although that requires a 64bit distro.

Indeed and there certainly is already an 'official' maraidb package for [armV8](https://hub.docker.com/r/arm64v8/mariadb/) but that combination whilst theoretically possible, is  definately a bleeding edge user case 😆.

For a quick & simple 'drop in replacement' the Linuxserver.io team [https://www.linuxserver.io/](url) operate a mirror of the vast majority of their maintained docker repo, under the sub branch **[lsioarmhf](https://hub.docker.com/u/lsioarmhf/)** specifically for the Rpi.

They have a large and varied community - across a number of disciplines (e.g. very popular/commonplace within unRAID setups) and their [mariadb package](https://hub.docker.com/r/lsioarmhf/mariadb/) is a core supporting component for most of their other packages, along with well documented resource pages to boot 😉 

+1 from me for Rpi support and if you require someone to break stuff/'idiot proof' the install steps (with me being the token 'idiot'!/be a guinea pig - then just shout I'd be happy to help! 👍 

Richy.

**Comment by JC5** [comment] 2018-08-17 03:15
Thanks @Richyread, I appreciate that. 

I'm currently in the process of testing if I can make the docker-compose.yml in the develop branch to play nice with Postgres. It requires different env vars to connect to the database properly. Once that works I could tag you to try it?

**Comment by JC5** [comment] 2018-08-17 17:16
Building the image I'm seeing this error constantly:

```
php: /usr/local/lib/libcurl.so.4: no version information available (required by php)
```

Any clues guys?

**Comment by JC5** [comment] 2018-08-18 03:28
The Docker file and compose file are happily running using postgres. Cron is not working from the current image. Will try supervisor now.

**Comment by JC5** [comment] 2018-08-18 18:12
I've pushed a new Dockerfile with supervisor that seems to work on my RPi3. Feedback and logs seem to be a bit weird, will look into it.

It's running merrily now and I'm keeping an eye on it to see if the cron actually fires.

**Comment by ErikFontanel** [comment] 2018-08-20 11:38
@JC5 
Great news! 

That error is the result of loading the new libcurl [@ this line](https://github.com/firefly-iii/firefly-iii/blob/develop/Dockerfile#L54). It seems that php has trouble using the newer libs. I have no success reconfiguring and reinstalling php curl with `docker-php-ext-configure curl` so far.

**Comment by JC5** [comment] 2018-09-02 15:44
Ah very good! I must have tried the wrong thing. I couldn't get it to work ☹️ 

I can't rebuild the 4.7.6 image but I can add the commands to the Dockerfile. That should fix it for the hard-core users that build their own image and will be automatically included in the new release.

Thanks for reporting, and thanks for testing! :+1:

**Comment by a1ex4** [comment] 2018-09-04 22:02
I think automated builds form Docker Hub are not compatible with arm arch ? At least with pure arm image it's not possible, I'm really not sure about multi-arch images.
Anyway using the latest image the container is just failing with incompatible architecture errors...

Are you guys testing the new Dockerfile by building the image the Pi itself ? 

Thanks again for awesome work JC5 ! 👍

**Comment by JC5** [comment] 2018-09-05 05:52
No they're not (yet). I haven't had the time yet to make it multi-arch. It's pretty complex at the moment to do this.

The last one (4.7.6.2) isn't tested on a Pi (don't have one here) but I plan to do this in the future.

**Comment by JaccovdS** [comment] 2018-10-28 14:57
Any conclusion on this issue? Is it still advised to use the modifications of @dicastro? If not is there another way forward and is it documented somewhere?

**Comment by JC5** [comment] 2018-10-28 14:59
In the mean time, support for multi-arch builds by Docker has been improving. But it is still pretty terrible. I've given it some attempts in the past but it's pretty complex. No conclusions yet.

**Comment by a1ex4** [comment] 2018-12-25 21:56
The Docker image is available for the new 4.7.9 update, at [a1ex4/rpi-firefly-iii:4.7.9](https://hub.docker.com/r/a1ex4/rpi-firefly-iii/), everything working fine so far. To update just edit your `docker-compose.yml`, replace the image, run `docker-compose up -d `and the database update should happen on its own.

Pinging @JC5 🙂

**Comment by JC5** [comment] 2018-12-26 06:14
That is very cool, my compliments. Could you link to the Dockerfile?

I just had the thought that it would be a good idea to remove most of the complexity from the current Docker build by removing the cron job. That would also make it easier to make one Dockerfile for multiple architectures.

I never saw your question, my apologies. The code your installation hangs on seems to be key generation for OAuth. That could take some time but should never take 30 seconds. Not really sure what's causing it.

**Comment by a1ex4** [comment] 2019-01-03 22:04
FYI @JC5 I setup Jenkins on my server, and it's building Firefly's develop and release Raspberry Pi image, everytime a change is detected on any branches, then pushed to my Docker hub.

Though I'm not sure where to go from here ? To mke the building process clean I'd need access to Firefly's repo webhooks, and to Docker hub too, so... 
Anyway I'll be building/pushing each releases to my hub, and I could make a PR so the Jenkinsfile is in the repo at least.

**Comment by JC5** [comment] 2019-01-07 17:23
This is awesome!

Reading into this, I'm pretty sure I can make Travis or another builder build the ARM images as well. I have to spend some time on it though. Not sure yet when.

**Comment by JC5** [comment] 2019-02-02 06:04
I've just set up a basic build on Travis that should create ARM images. Haven't tested it yet.

**Comment by mcrosson** [comment] 2019-02-02 19:12
@JC5 Are you building the Dockerfile-ARM on an x86 box?

**Comment by JC5** [comment] 2019-02-02 19:55
Yes, using Travis. I got the image working on my own RP3, but it seems to be tagged as amd64 still.

**Comment by mcrosson** [comment] 2019-02-03 06:04
@JC5 if you'd like I'm willing to put some arm hardware up for native builds of firefly-iii

I'm working on the lollipop cloud project (https://lollipopcloud.solutions) and we have a community member who aimed me your direction as an alternative for quick books. We're running quite a few builds of different docker containers and adding another app is well inside our scope ;)

**Comment by JC5** [comment] 2019-02-03 10:00
OK, so sorry for the spam everybody, but I was doing pretty good this morning and I just pushed a new release and new docker images. I haven't had time to double-check everything but I believe the following tags are multi-arch and should work on your Raspberry Pi out of the box:

jc5x/firefly-iii:develop
jc5x/firefly-iii:latest
jc5x/firefly-iii:release-4.7.10

**Comment by mcrosson** [comment] 2019-02-03 21:00
@JC5 Did you include arm64 as well?

**Comment by mcrosson** [comment] 2019-02-08 05:41
@JC5 Gotcha, would you be upset/otherwise if I poked at native arm builds using the main Dockerfile once it's part of an official release?

I'm working with a project that's focused on self-hosted clouds for individuals or familial units and one of the things we like to do is run our own Docker builds and publish to a dedicated Docker registry that's focused on arm containers. It's separate from the main docker hub though.

**Comment by JC5** [comment] 2019-02-08 06:16
No please feel free! I want to keep control over the main builds in the jc5x/firefly-iii repository, so if it's possible I'll copy some of your work over to my "own" Dockerfiles. But I might not be able to pick it up right away so feel free to set something up! 

I know way too little about this so I'll be following with much curiousity :grin:

**Comment by mcrosson** [comment] 2019-02-08 19:42
@JC5 I just ran arm32 and arm64 builds using the main dockerfile that's published. I built on a pair of orange pi pc / pc2 boards that are arm32 / arm64.

For those looking to run the build on their raspberry pi they can do ```docker build -t fireflyiii/fireflyiii:latest .``` from the cloned sources.

**Closed** 2019-02-16 18:35 UTC
Labels: enhancement, fixed

**Comment by JC5** [comment] 2019-02-16 18:37
4.7.12 has been released. Follow the status of the Docker build on [Travis CI](https://travis-ci.com/firefly-iii/firefly-iii/builds).
