### ISSUE TITLE
Administration missing in 4.7.5.3

### ISSUE THREAD

**Issue by Ludo444** [firefly-iii/firefly-iii#1584] opened 2018-08-01 07:08 UTC
Hey again,

link to Administration is missing in Options in version 4.7.5.3. I have correct record in 'role_user' table and /admin is accessible through URL. Also I'm 100% sure it was there in previous version before upgrade.

**Comment by lucavallerini** [comment] 2018-08-01 08:25
I can confirm, but I can access the administration via URL without doing anything.

**Comment by JC5** [comment] 2018-08-01 08:40
Call it a coincidence, but I noticed this yesterday as well:

https://github.com/firefly-iii/firefly-iii/commit/1af45aff736c101e8f40c1908d64306369885095

It will be fixed in the next release. Thanks for letting me know! Turns out I was referring to a function that no longer exists.

**Comment by anmol26s** [comment] 2018-08-05 12:47
Facing this issue in Firefly-III Yunohost package too.

**Comment by JC5** [comment] 2018-08-07 17:31
I'm closing this since it's fixed. Look for this feature in the next release, and let me know if you encounter any problems!

**Closed by JC5** 2018-08-07 17:31 UTC
Labels: bug, fixed
