### ISSUE TITLE
No transactions were downloaded from GoCardless. You may be rate limited or something else went wrong

### ISSUE THREAD

**Issue by Bart1909** [firefly-iii/firefly-iii#9228] opened 2024-09-11 06:16 UTC
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Since 03.09.2024 no transactions were downloaded from GoCardless.

If I log into Gocardless and connect my bank the transactions are shown.

I'm wondering about the lines:
```
[2024-09-11 08:00:08] local.DEBUG: Account success rate limit: 10  
[2024-09-11 08:00:08] local.DEBUG: Account success rate limit remaining: 0  
[2024-09-11 08:00:08] local.DEBUG: Account success rate limit reset: -1875538  
```

### Debug information

```
[2024-09-11 08:00:01] local.DEBUG: Now in App\Console\AutoImports::startConversion  
[2024-09-11 08:00:01] local.INFO: Going to automatically import everything found in /import (/import)  
[2024-09-11 08:00:01] local.INFO: Found 1 (importable +) JSON file sets in /import  
[2024-09-11 08:00:01] local.DEBUG: ImportFile: directory "/import"  
[2024-09-11 08:00:01] local.DEBUG: ImportFile: file      "import_config_2024-07-15.json"  
[2024-09-11 08:00:01] local.DEBUG: ImportFile: importable "/import/import_config_2024-07-15.json"  
[2024-09-11 08:00:01] local.DEBUG: ImportFile: JSON       "/import/import_config_2024-07-15.json"  
[2024-09-11 08:00:01] local.DEBUG: Now in updateDateRange()  
[2024-09-11 08:00:01] local.DEBUG: Range is partial, after is NULL, dateNotBefore will be calculated.  
[2024-09-11 08:00:01] local.DEBUG: dateNotBefore is now "2024-09-01"  
[2024-09-11 08:00:01] local.DEBUG: Going to generate conversion routine identifier.  
[2024-09-11 08:00:01] local.DEBUG: Attempt #1 results in "conversion-TEWCC31btjBJ"  
[2024-09-11 08:00:01] local.INFO: Job identifier is "conversion-TEWCC31btjBJ"  
[2024-09-11 08:00:01] local.DEBUG: Now in startOrFindConversion(conversion-TEWCC31btjBJ)  
[2024-09-11 08:00:01] local.DEBUG: File does not exist or error, create a new one.  
[2024-09-11 08:00:01] local.DEBUG: Now in setConversionStatus(conv_running)  
[2024-09-11 08:00:01] local.DEBUG: Return status. {"status":"waiting_to_start","errors":[],"warnings":[],"messages":[]} 
[2024-09-11 08:00:01] local.DEBUG: Found "conversion-TEWCC31btjBJ" in the session  
[2024-09-11 08:00:01] local.DEBUG: Set identifier to "conversion-TEWCC31btjBJ"  
[2024-09-11 08:00:01] local.DEBUG: Conversion status is "waiting_to_start"  
[2024-09-11 08:00:01] local.DEBUG: Now in storeConversionStatus(conversion-TEWCC31btjBJ): conv_running  
[2024-09-11 08:00:01] local.DEBUG: Messages: 0, warnings: 0, errors: 0  
[2024-09-11 08:00:01] local.DEBUG: Now in App\Services\Nordigen\Conversion\RoutineManager::start  
[2024-09-11 08:00:01] local.DEBUG: The GoCardless API URL is https://bankaccountdata.gocardless.com  
[2024-09-11 08:00:01] local.DEBUG: Call transaction processor download.  
[2024-09-11 08:00:01] local.DEBUG: Now in App\Services\Nordigen\Conversion\Routine\TransactionProcessor::download  
[2024-09-11 08:00:01] local.DEBUG: Found 1 accounts to download from.  
[2024-09-11 08:00:01] local.DEBUG: Going to download transactions for account #0 "<accountId>"  
[2024-09-11 08:00:01] local.DEBUG: Now in App\Services\Nordigen\Services\AccountInformationCollector::collectInformation  
[2024-09-11 08:00:01] local.DEBUG: Get account details is DISABLED.  
[2024-09-11 08:00:01] local.DEBUG: Get account balance is DISABLED.  
[2024-09-11 08:00:01] local.DEBUG: Now in App\Services\Nordigen\Services\AccountInformationCollector::getBasicDetails(<accountId>)  
[2024-09-11 08:00:01] local.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
[2024-09-11 08:00:01] local.DEBUG: No refresh token, so return false.  
[2024-09-11 08:00:01] local.DEBUG: No Nordigen refresh token, so return false.  
[2024-09-11 08:00:01] local.DEBUG: No Nordigen ID in hasId() session, will return config variable.  
[2024-09-11 08:00:01] local.DEBUG: No Nordigen key in hasKey() session, will return config variable.  
[2024-09-11 08:00:01] local.DEBUG: Now at App\Services\Nordigen\TokenManager::getNewTokenSet  
[2024-09-11 08:00:01] local.DEBUG: authenticatedGet(https://bankaccountdata.gocardless.com/api/v2/accounts/<accountId>)  
[2024-09-11 08:00:01] local.DEBUG: Request parameters will be set to:   
[2024-09-11 08:00:02] local.DEBUG: Rate limit: 100  
[2024-09-11 08:00:02] local.DEBUG: Rate limit remaining: 99  
[2024-09-11 08:00:02] local.DEBUG: Rate limit reset: 59  
[2024-09-11 08:00:02] local.DEBUG: Now in pauseForRateLimit  
[2024-09-11 08:00:02] local.DEBUG: [a] Rate limit: 99 requests remaining, and 59s before the limit resets.  
[2024-09-11 08:00:02] local.DEBUG: Save the account success limits? NO  
[2024-09-11 08:00:02] local.DEBUG: Response for basic information request: {"id":"<accountId>","created":"2023-09-25T08:54:28.480887Z","last_accessed":"2024-09-10T16:00:09.799852Z","iban":"<iban>","institution_id":"COMDIRECT_COBADEHD","status":"READY","owner_name":"<name>"} 
[2024-09-11 08:00:02] local.DEBUG: Set new IBAN from basic details.  
[2024-09-11 08:00:02] local.DEBUG: Done downloading information for debug purposes.  
[2024-09-11 08:00:02] local.DEBUG: Request parameters will be set to:   
[2024-09-11 08:00:02] local.DEBUG: authenticatedGet(https://bankaccountdata.gocardless.com/api/v2/accounts/<accountId>/transactions/)  
[2024-09-11 08:00:08] local.DEBUG: Rate limit: 100  
[2024-09-11 08:00:08] local.DEBUG: Rate limit remaining: 98  
[2024-09-11 08:00:08] local.DEBUG: Rate limit reset: 59  
[2024-09-11 08:00:08] local.DEBUG: Account success rate limit: 10  
[2024-09-11 08:00:08] local.DEBUG: Account success rate limit remaining: 0  
[2024-09-11 08:00:08] local.DEBUG: Account success rate limit reset: -1875538  
[2024-09-11 08:00:08] local.DEBUG: Now in pauseForRateLimit  
[2024-09-11 08:00:08] local.DEBUG: [a] Rate limit: 98 requests remaining, and 59s before the limit resets.  
[2024-09-11 08:00:08] local.DEBUG: Save the account success limits? YES  
[2024-09-11 08:00:08] local.ERROR: Account success limit: Refuse to sleep for more than 5 minutes, throw exception instead.  
[2024-09-11 08:00:08] local.DEBUG: Done with download  
[2024-09-11 08:00:08] local.DEBUG: Rate limit for account <accountId>: 0 request(s) left, -1875538 second(s)  
[2024-09-11 08:00:08] local.DEBUG: Generating Firefly III transactions.  
[2024-09-11 08:00:08] local.DEBUG: Nordigen: Defer account search to trait.  
[2024-09-11 08:00:08] local.DEBUG: Now in collectAllTargetAccounts()  
[2024-09-11 08:00:08] local.DEBUG: Now in collectAccounts("asset")  
[2024-09-11 08:00:08] local.DEBUG: No access token in hasAccessToken() session, will return config variable.  
[2024-09-11 08:00:08] local.DEBUG: No base url in getBaseUrl() session, will return config variable.  
[2024-09-11 08:00:08] local.DEBUG: Found 1 accounts of type "asset"  
[2024-09-11 08:00:08] local.DEBUG: Collected 1 accounts of type "asset"  
[2024-09-11 08:00:08] local.DEBUG: Processing account #41 ("Comdirect") with type "asset"  
[2024-09-11 08:00:08] local.DEBUG: Now in collectAccounts("liabilities")  
[2024-09-11 08:00:08] local.DEBUG: Found 0 accounts of type "liabilities"  
[2024-09-11 08:00:08] local.DEBUG: Collected 0 accounts of type "liabilities"  
[2024-09-11 08:00:08] local.DEBUG: Nordigen: Collected 0 accounts.  
[2024-09-11 08:00:08] local.DEBUG: Add message about rate limits.  
[2024-09-11 08:00:08] local.DEBUG: Account "41" has no interesting rate limit information.  
[2024-09-11 08:00:08] local.WARNING: Downloaded nothing, will return nothing.  
[2024-09-11 08:00:08] local.ERROR: [c] Add error to index #0: No transactions were downloaded from GoCardless. You may be rate limited or something else went wrong.  
[2024-09-11 08:00:08] local.DEBUG: Add error on index #0 (line no. 1): No transactions were downloaded from GoCardless. You may be rate limited or something else went wrong.  
[2024-09-11 08:00:08] local.DEBUG: Now in storeConversionStatus(conversion-TEWCC31btjBJ): conv_running  
[2024-09-11 08:00:08] local.DEBUG: Messages: 0, warnings: 0, errors: 1  
[2024-09-11 08:00:08] local.DEBUG: Now in setConversionStatus(conv_done)  
[2024-09-11 08:00:08] local.DEBUG: Found "conversion-TEWCC31btjBJ" in the session  
[2024-09-11 08:00:08] local.ERROR: [a] Zero transactions!  
[2024-09-11 08:00:09] local.ERROR: Too many errors in the data conversion.  
[2024-09-11 08:00:09] local.ERROR: Could not complete import from file "import_config_2024-07-15.json".  
[2024-09-11 08:00:09] local.DEBUG: If no error above this line, mail was sent!  
[2024-09-11 08:00:08] local.DEBUG: If no error below this line, mail was sent!  
[2024-09-11 08:00:08] local.DEBUG: Warnings count: 0  
[2024-09-11 08:00:08] local.DEBUG: Errors count  : 1  
[2024-09-11 08:00:08] local.DEBUG: Messages count: 0  
[2024-09-11 08:00:08] local.INFO: Will send report message.  
[2024-09-11 08:00:08] local.DEBUG: Now in sendReportOverMail  
[2024-09-11 08:00:08] local.DEBUG: Array contains 1 error(s)  
[2024-09-11 08:00:08] local.DEBUG: Array contains 0 warning(s)  
[2024-09-11 08:00:08] local.DEBUG: Array contains 0 message(s)  
[2024-09-11 08:00:08] local.DEBUG: Created event ImportedTransactions with filtering (2)  
[2024-09-11 08:00:08] local.ERROR: Too many errors in the data conversion (1), exit.  
[2024-09-11 08:00:08] local.ERROR: Conversion index (error) 0: No transactions were downloaded from GoCardless. You may be rate limited or something else went wrong.  
[2024-09-11 08:00:08] local.DEBUG: Now in storeConversionStatus(conversion-TEWCC31btjBJ): conv_done  
[2024-09-11 08:00:08] local.DEBUG: Conversion status is "conv_running"  
[2024-09-11 08:00:08] local.DEBUG: Now in startOrFindConversion(conversion-TEWCC31btjBJ)  
```

### Additional info

Firefly III Data Importer, v1.5.5

**Comment by Jhutjens92** [comment] 2024-09-11 06:32
I've had the same "issue" however this merely means that you are request capped. In my case my import from last night worked and showed this: [2024-09-11 01:00:08] [production.INFO](http://production.info/): [c] Add message to index #0: You have 9 request(s) left for bank account "Betaalrekening XX". [Read more about GoCardless rate limits](https://docs.firefly-iii.org/totally-still-todo). Meaning i get 10 new requests starting from today. Not sure if it resets per month /30 day period. Haven't been able to figure this out yet.

See this site for more info: https://bankaccountdata.zendesk.com/hc/en-gb/articles/11529637772188-Bank-Account-Data-API-Rate-Limits

**Comment by semiBE** [comment] 2024-09-11 07:27
I have been using the GoCardless integration for quite some time and never hit the rate limits (ndr: after the rate limits were introduced) but I have also had the same issues as reported by OP in the last few days. 
Is the data-importer handling the waiting time as suggested by the GoCardless API by any chance? Because I can see log entries which go by "I need to wait more than 5min so I won't" :D And, if the data-importer is not handling it (yet?), how do you guys manage the waiting time? Looking for suggestions! Thanks!

**Comment by Bart1909** [comment] 2024-09-11 07:29
I also run the importer less then 10 times per day after the limit was introduced. And it worked with the rate limit until last week :/

**Comment by semiBE** [comment] 2024-09-11 08:30
> I also run the importer less then 10 times per day after the limit was introduced. And it worked with the rate limit until last week :/

Well in my case is one every 12hrs and still the same issue applies

**Comment by JC5** [comment] 2024-09-11 08:50
Hi, thanks for opening an issue. 

This is not a bug, but a result of GoCardless new rate limits. You have received an email about this. I will close this issue and would like to refer you to the discussions-tab.

**Closed** 2024-09-11 08:50 UTC

**Comment by Bart1909** [comment] 2024-09-11 08:52
> Hi, thanks for opening an issue.
> 
> This is not a bug, but a result of GoCardless new rate limits. You have received an email about this. I will close this issue and would like to refer you to the discussions-tab.

But should the rate limits not reset after one day? It's not working for over a week now.
And as said I should not run into rate limits because running the importer less then 10 times per day

**Comment by Bart1909** [comment] 2024-09-11 09:00
I've tested the API call manually and I think, the GoCardless Header are wrong.

The result code is 200 and I receive a result but the headers look like:
![grafik](https://github.com/user-attachments/assets/75c52431-42ce-47cb-90e3-8734909942de)

**Comment by digitlength** [comment] 2024-09-11 20:04
Imports are still working over here, importing exactly 10 times per day. 

My Firefly is latest production release.
My importer is pinned to v1.5.3.

**Comment by calgara12** [comment] 2024-09-12 05:44
For me It stopped working 10-12ish days ago. Always hit the rate limit. I dont really get it, because I am only syncing 6 times per day. and it hasnt worked in 12 days. If it would be a rate limit problem shouldnt it work some of the time?

**Comment by digitlength** [comment] 2024-09-12 05:54
> If it would be a rate limit problem shouldnt it work some of the time?

That might depend on when those six times are. What version of the Importer are you using? Have you tried pausing imports for more than 24h, and then restarting them?

**Comment by Bart1909** [comment] 2024-09-12 05:57
For me it's working again if I downgrade to `fireflyiii/data-importer:version-1.5.3`

**Comment by calgara12** [comment] 2024-09-12 05:58
> What version of the Importer are you using? Have you tried pausing imports for more than 24h, and then restarting them?

It's a cron job running every 4 hours. I haven't tried pausing it for 24 hours. I will do that now. Also the importer I initially used was the latest one 1.5.5, but after reading your post I tried it with 1.5.3, still hitting the rate limit. But maybe it will work after pausing for 24 hours. Thank you for the assistance btw :)

**Comment by calgara12** [comment] 2024-09-12 06:03
> For me it's working again if I downgrade to `fireflyiii/data-importer:version-1.5.3`


Glad it's working again for you, this gives me hope hahaha.
Did you do anything else other than downgrade? Did you pause the import beforehand for some time?

**Comment by Bart1909** [comment] 2024-09-12 06:09
> > For me it's working again if I downgrade to `fireflyiii/data-importer:version-1.5.3`
> 
> Glad it's working again for you, this gives me hope hahaha. Did you do anything else other than downgrade? Did you pause the import beforehand for some time?

No, simply downgrade.
I import 6 times per day. And tested this manually like written above. There was a result but the headers were sent wrong from GoCardless.
I think in version 1.5.3 the validation of the headers is not implemented and it is working because of this now.

**Comment by digitlength** [comment] 2024-09-12 06:10
> but after reading your post I tried it with 1.5.3, still hitting the rate limit. 

But if there was a problem with 1.5.5 and you hit the rate limit already for that day (for some reason) then 1.5.3 will also fail: you'd already hit the limit. How long did you wait?

This is regardless of the GoCardless headers - I'm assuming you hit the real limit already.

**Comment by JC5** [comment] 2024-09-12 06:16
Could you move this discussion to the Discussion tab please? More people will read your dialogue.
