### ISSUE TITLE
Duplicated transfer transaction import from YNAB

### ISSUE THREAD

**Issue by vwvw** [firefly-iii/firefly-iii#4493] opened 2021-03-11 15:16 UTC
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:
when importing data from YNAB with the importer, transfer transaction appear twice in the data downloaded from YNAB. The importer does not check the `transfer_transaction_id` from the YNAB transaction for deduplication. The transactions are imported correctly as transfer but appear twice in Firefly III resulting in wrong balances.

**Steps to reproduce**
Setup two accounts on YNAB. Add a transfer transaction between the two. Run the importer on both account.

![2021-03-11-161605_863x499_scrot](https://user-images.githubusercontent.com/11035844/110809431-294b6400-8285-11eb-8416-009811614760.png)

Thanks for the AMAZING software by the way!

**Comment by JC5** [comment] 2021-03-11 17:07
Thanks for letting me know, I'll see what I can do.

**Comment by bpjobin** [comment] 2021-04-28 02:21
This also happened to me using CSV Importer. Even with the duplicate detection method enabled, it won't find it since it seems to be looking for duplicates only in the same account. Perhaps this feature needs a more complex way of finding what's a duplicate and what's not. 

One idea when it comes to transfers would be not to search for duplicates but rather a matching transaction of the same type that has the same amount, date and who's source and destination accounts match. That wouldn't be rock solid but would probably solve this problem 90% of the time. 

I also noticed that in ofx files from two different accounts from my bank that the transaction ids from the transfer transaction don't match. For example you transfer 1$ from account A to account B. Now in the statement of account A, there will be a transfer transaction of -1$ with an ID of say 4023. On the statement of account be, there will be the same transaction but negated since it's a deposit (1$) but with a different id. I guess it depends on how banks manage there data. Or maybe there something I missed in the data the ofx format provides. 

Otherwise I also have to mention that your application is absolutely amazing. It's a breeze to import and manage data. I really enjoy it. Keep up the good work!

**Comment by JC5** [comment] 2021-04-29 17:03
Thanks for the compliments but please open a new ticket for your problems.

**Comment by JaCoB1123** [comment] 2021-09-18 21:11
I'm having the same problem. Has there been any progress on this?

If not, could you point me to the relevant code? I might take a stab at the problem myself.

**Comment by JC5** [comment] 2021-09-19 07:37
I have to keep registering test accounts with YNAB, they do not give out developer access until you take out a subscription. As such, I haven't looked at the problem yet and I can't tell you where the issue may be.

I suspect a custom solution must be build to search for the `transfer_transaction_id` before the import continues.

**Comment by jdambacher** [comment] 2021-11-06 11:47
Hey there, any updates on this?

**Comment by JaCoB1123** [comment] 2021-11-07 17:46
@jdambacher  I unfortunately didn't find the time to look into it yet.

I'm also having trouble setting up a test environment. Is there some documentation somewhere? Ideally using docker?
I only found Dockerfiles for firefly and its base-image.

**Comment by jdambacher** [comment] 2021-11-15 10:29
@JaCoB1123 Yes, there is a docker image: https://github.com/firefly-iii/ynab-importer

You can create a 30-day free account at YNAB and try it out. Just create some sample transfer transactions.

**Comment by JaCoB1123** [comment] 2021-11-15 12:34
@jdambacher I found that repo, I just can't find a Dockerfile to build it?
Or what's the recommended way to setup a local development environment?

**Comment by jdambacher** [comment] 2021-11-15 19:08
I see! Maybe @JC5 can help. I didn't find a Dockerfile either, only the built Docker image at Docker Hub.

**Comment by JC5** [comment] 2021-11-15 20:08
The Dockerfile and associated code is on Azure: https://dev.azure.com/Firefly-III/_git/ImportToolImage?path=/Dockerfile

If you have a solution keep me posted.

**Comment by JC5** [comment] 2021-11-15 22:37
I pushed a potential fix to the develop branch and develop image. Could you check it out?

**Comment by JaCoB1123** [comment] 2021-11-16 10:06
@JC5 Thanks a lot for the potential fix.

I just made a test run with my real YNAB budget. Unfortunately it didn't import any transactions this time.

**Comment by JC5** [comment] 2021-11-16 10:48
Mmm, that doesn't sound too useful 😅 

I've added some debug logging to the develop branch + image. Could you see if the logs shed any light on the potential issue?

**Comment by JaCoB1123** [comment] 2021-11-16 11:44
I'm running it again with the added logs. I just checked the previous logs as well and I have this pattern about 2k times:

```
[2021-11-16 11:28:52] production.DEBUG: Transaction "e67fb5d8-27c5-bfdb-1536-9658d4eec88d" has a transfer_transaction_id "7edd3e03-a674-0e5f-e1a9-9658d4eeb589" which is already registered as another transaction. Its a duplicate  
[2021-11-16 11:28:52] production.ERROR: Transaction "e67fb5d8-27c5-bfdb-1536-9658d4eec88d" is a duplicate of "7edd3e03-a674-0e5f-e1a9-9658d4eeb589". {"transaction_id":null,"memo":null,"transactions":[{"transaction_id":"e67fb5d8-27c5-bfdb-1536-9658d4eec88d","date":"2014-01-29","account_id":"8f278993-af78-7776-e926-9658d4dd872b","account_name":"Bargeld","payee_id":"bb8f8448-36ec-4e80-2d0a-9658d4dedb0b","payee_name":"Transfer : Comdirect","category_name":"Uncategorized","transfer_account_id":"5ceaa778-f059-15dc-cfcb-9658d4dd8d76","transfer_transaction_id":"7edd3e03-a674-0e5f-e1a9-9658d4eeb589","amount":150000,"memo":"Abgehoben"}]} 
[2021-11-16 11:28:52] production.ERROR: Error: x6irVzsE4ZPdgsnr 0: Transaction "7edd3e03-a674-0e5f-e1a9-9658d4eeb589" is a duplicate and will not be imported.  
```

Here are all lines I could find for a specific transaction (`71a1b6ec-ef35-745f-7dfe-9658d4f4b6ad`)

```
[2021-11-16 11:28:51] production.DEBUG: Save transaction ID 71a1b6ec-ef35-745f-7dfe-9658d4f4b6ad as a potential duplicate.  
[2021-11-16 11:28:52] production.DEBUG: Transaction "71a1b6ec-ef35-745f-7dfe-9658d4f4b6ad" has a transfer_transaction_id "905a9635-a533-70b9-f70c-9658d4f498cf" which is already registered as another transaction. Its a duplicate  
[2021-11-16 11:28:52] production.ERROR: Transaction "71a1b6ec-ef35-745f-7dfe-9658d4f4b6ad" is a duplicate of "905a9635-a533-70b9-f70c-9658d4f498cf". {"transaction_id":null,"memo":null,"transactions":[{"transaction_id":"71a1b6ec-ef35-745f-7dfe-9658d4f4b6ad","date":"2014-12-09","account_id":"8f278993-af78-7776-e926-9658d4dd872b","account_name":"Bargeld","payee_id":"bb8f8448-36ec-4e80-2d0a-9658d4dedb0b","payee_name":"Transfer : Comdirect","category_name":"Uncategorized","transfer_account_id":"5ceaa778-f059-15dc-cfcb-9658d4dd8d76","transfer_transaction_id":"905a9635-a533-70b9-f70c-9658d4f498cf","amount":-2600000,"memo":""}]} 
[2021-11-16 11:28:52] production.DEBUG: Transaction "905a9635-a533-70b9-f70c-9658d4f498cf" has a transfer_transaction_id "71a1b6ec-ef35-745f-7dfe-9658d4f4b6ad" which is already registered as another transaction. Its a duplicate  
[2021-11-16 11:28:52] production.ERROR: Transaction "905a9635-a533-70b9-f70c-9658d4f498cf" is a duplicate of "71a1b6ec-ef35-745f-7dfe-9658d4f4b6ad". {"transaction_id":null,"memo":null,"transactions":[{"transaction_id":"905a9635-a533-70b9-f70c-9658d4f498cf","date":"2014-12-09","account_id":"5ceaa778-f059-15dc-cfcb-9658d4dd8d76","account_name":"Comdirect","payee_id":"3862e666-5b91-7652-d5ed-9658d4def637","payee_name":"Transfer : Bargeld","category_name":"Uncategorized","transfer_account_id":"8f278993-af78-7776-e926-9658d4dd872b","transfer_transaction_id":"71a1b6ec-ef35-745f-7dfe-9658d4f4b6ad","amount":2600000,"memo":""}]} 
[2021-11-16 11:28:52] production.ERROR: Error: x6irVzsE4ZPdgsnr 0: Transaction "71a1b6ec-ef35-745f-7dfe-9658d4f4b6ad" is a duplicate and will not be imported.  
```

**Comment by JC5** [comment] 2021-11-16 16:14
OK, as far as I can see it works. At least, it works for me ™️ . Transfers between accounts are skipped but inflow and expenses are saved. Is that not the case for you?

Your example is marked as a transfer, you see.

**Comment by JaCoB1123** [comment] 2021-11-17 07:51
@JC5 Yes, that's what it does for me as well. Maybe I wasn't clear and used the wrong terminology. That's not an ideal solution though.

Before the change all transfers where imported twice - once for each involved account I guess.
After the change no transfers are imported at all.
For me the optimum would be to have each transfer imported exactly once.

I could of course do a single transfer to balance each account out, but that would leave me with very wrong historic account balances. E.g. my checking accounts balance is above 100k according to firefly and my credit card is below negative 100k 😄

**Comment by JC5** [comment] 2021-11-17 07:54
>  For me the optimum would be to have each transfer imported exactly once.

That's what I intended, and that's what's happening for me right now. "Transfers are skipped" is not the right wording in my previous reply: transfers are saved once, not twice. So in my own test environment, these transfers between accounts are imported one time.

> I could of course do a single transfer to balance each account out, but that would leave me with very wrong historic account balances. E.g. my checking accounts balance is above 100k according to firefly and my credit card is below negative 100k 😄

I'm not entirely sure what you mean.

**Comment by JaCoB1123** [comment] 2021-11-18 07:53
> That's what I intended, and that's what's happening for me right now. 

@JC5 Ok, good to know we're aiming for the same target.

I just wanted to try again, but it didn't import anything and showed `
Could not create transaction: Duplicate of transaction #….` for all transactions, athough I 
deleted all transactions using the UI. After deleting all transactions according to your instructions from !3546 the import ran again.
=> Did I miss something or did I do something wrong? Should I submit another issue for that?

For me it only imported 5 actual transfers though. It seems like the not-imported ones have each other as the transfer_transaction_id which makes them both get ignored?

Here are the logs for one of the not-imported transfers:

```
[2021-11-17 22:28:16] production.DEBUG: Save transaction ID e67fb5d8-27c5-bfdb-1536-9658d4eec88d as a potential duplicate.  
[2021-11-17 22:28:16] production.DEBUG: Save transaction ID 7edd3e03-a674-0e5f-e1a9-9658d4eeb589 as a potential duplicate. 
[2021-11-17 22:28:16] production.DEBUG: Found 11849 transaction ID(s) …
[2021-11-17 22:28:16] production.DEBUG: Transaction "e67fb5d8-27c5-bfdb-1536-9658d4eec88d" has a transfer_transaction_id "7edd3e03-a674-0e5f-e1a9-9658d4eeb589" which is already registered as another transaction. Its a duplicate  
[2021-11-17 22:28:16] production.ERROR: Transaction "e67fb5d8-27c5-bfdb-1536-9658d4eec88d" is a duplicate of "7edd3e03-a674-0e5f-e1a9-9658d4eeb589". {"transaction_id":null,"memo":null,"transactions":[{"transaction_id":"e67fb5d8-27c5-bfdb-1536-9658d4eec88d","date":"2014-01-29","account_id":"8f278993-af78-7776-e926-9658d4dd872b","account_name":"Bargeld Jan","payee_id":"bb8f8448-36ec-4e80-2d0a-9658d4dedb0b","payee_name":"Transfer : Comdirect","category_name":"Uncategorized","transfer_account_id":"5ceaa778-f059-15dc-cfcb-9658d4dd8d76","transfer_transaction_id":"7edd3e03-a674-0e5f-e1a9-9658d4eeb589","amount":150000,"memo":"Abgehoben"}]} 
[2021-11-17 22:28:16] production.ERROR: Error: KAFpKIVGo5CLCZNx 0: Transaction "7edd3e03-a674-0e5f-e1a9-9658d4eeb589" is a duplicate and will not be imported.  
[2021-11-17 22:28:16] production.DEBUG: Transaction "7edd3e03-a674-0e5f-e1a9-9658d4eeb589" has a transfer_transaction_id "e67fb5d8-27c5-bfdb-1536-9658d4eec88d" which is already registered as another transaction. Its a duplicate  
[2021-11-17 22:28:16] production.ERROR: Transaction "7edd3e03-a674-0e5f-e1a9-9658d4eeb589" is a duplicate of "e67fb5d8-27c5-bfdb-1536-9658d4eec88d". {"transaction_id":null,"memo":null,"transactions":[{"transaction_id":"7edd3e03-a674-0e5f-e1a9-9658d4eeb589","date":"2014-01-29","account_id":"5ceaa778-f059-15dc-cfcb-9658d4dd8d76","account_name":"Comdirect","payee_id":"3862e666-5b91-7652-d5ed-9658d4def637","payee_name":"Transfer : Bargeld Jan","category_name":"Uncategorized","transfer_account_id":"8f278993-af78-7776-e926-9658d4dd872b","transfer_transaction_id":"e67fb5d8-27c5-bfdb-1536-9658d4eec88d","amount":-150000,"memo":"Abgehoben"}]} 
[2021-11-17 22:28:16] production.ERROR: Error: KAFpKIVGo5CLCZNx 0: Transaction "e67fb5d8-27c5-bfdb-1536-9658d4eec88d" is a duplicate and will not be imported.  
```

And here are all the log entries I found for one of the transfers that was imported:

```
[2021-11-17 22:28:16] production.DEBUG: Save transaction ID 719c196b-ac86-bed2-aa24-4251e9201ac3 as a potential duplicate.  
[2021-11-17 22:28:17] production.DEBUG: Transaction "b17ab311-4b93-ce63-fddc-4251e920d553" has a transfer_transaction_id "719c196b-ac86-bed2-aa24-4251e9201ac3" which is already registered as another transaction. Its a duplicate  
[2021-11-17 22:28:17] production.ERROR: Transaction "b17ab311-4b93-ce63-fddc-4251e920d553" is a duplicate of "b859cc19-62d8-2a16-634e-4251e920a283". {"transaction_id":"b17ab311-4b93-ce63-fddc-4251e920d553","memo":"Einmalanlage gemäß Sparplan","transactions":[{"transaction_id":"b17ab311-4b93-ce63-fddc-4251e920d553","date":"2015-01-16","account_id":"5d1dcdb9-d1f8-61b8-0a9e-4251e9099701","account_name":"Comdirect Verrechnung","payee_id":"fb28685c-452d-3bb9-f45a-4251e90e7137","payee_name":"Transfer : Comdirect Depot","category_name":"Notfall","transfer_account_id":"690935d2-e80b-dadf-7de4-4251e9095b7c","transfer_transaction_id":"f12496ee-7a52-2c85-8bec-4251e9206891","amount":-104380,"memo":"DAX"},{"transaction_id":"b17ab311-4b93-ce63-fddc-4251e920d553","date":"2015-01-16","account_id":"5d1dcdb9-d1f8-61b8-0a9e-4251e9099701","account_name":"Comdirect Verrechnung","payee_id":"fb28685c-452d-3bb9-f45a-4251e90e7137","payee_name":"Transfer : Comdirect Depot","category_name":"Notfall","transfer_account_id":"690935d2-e80b-dadf-7de4-4251e9095b7c","transfer_transaction_id":"719c196b-ac86-bed2-aa24-4251e9201ac3","amount":-237300,"memo":"Emerging Markets"},{"transaction_id":"b17ab311-4b93-ce63-fddc-4251e920d553","date":"2015-01-16","account_id":"5d1dcdb9-d1f8-61b8-0a9e-4251e9099701","account_name":"Comdirect Verrechnung","payee_id":"fb28685c-452d-3bb9-f45a-4251e90e7137","payee_name":"Transfer : Comdirect Depot","category_name":"Notfall","transfer_account_id":"690935d2-e80b-dadf-7de4-4251e9095b7c","transfer_transaction_id":"b859cc19-62d8-2a16-634e-4251e920a283","amount":-316530,"memo":"World"}]} 
[2021-11-17 22:28:17] production.DEBUG: Transaction "719c196b-ac86-bed2-aa24-4251e9201ac3" is not a duplicate  
[2021-11-17 22:39:44] production.DEBUG: Trying to send transaction #6412 {"apply_rules":true,"error_if_duplicate_hash":true,"group_title":null,"transactions":[{"amount":"237.3","type":"transfer","description":"Emerging Markets","date":"2015-01-16","notes":"Transaction ID: 719c196b-ac86-bed2-aa24-4251e9201ac3","category_name":"Uncategorized","source_id":95,"destination_id":101}]} 
```

> I'm not entirely sure what you mean.

For example I have 10k on my checking account and -10k on my credit card although both are supposed to be zero. I could just move the 10k from checking to the credit card to have the correct balances. That would leave all my balances up until now to be incorrect though, rendering the graph on the dashboard useless.

**Comment by JC5** [comment] 2021-12-10 17:18
I'm sorry @JaCoB1123 but I'm limiting my time to the new [data importer](https://github.com/firefly-iii/data-importer). I'm not going to spend more time on this issue. 

Importing from YNAB is still possible by CSV export, but the dedicated YNAB importer will not be developed further. Sorry about that.

**Closed by JC5** 2021-12-10 17:18 UTC
Labels: bug, import
