### ISSUE TITLE
Rabobank will not import and read the "C" and "D" in the .csv file.

### ISSUE THREAD

**Issue by uffer** [firefly-iii/firefly-iii#815] opened 2017-09-05 18:19 UTC
Hi,

As the title descriped: Rabobank will not import and read the "C" and "D" in the .csv file.

Explanation: 
With the following (attached) test .csv from the Rabobank and the .rabobank .json from the wiki all of the transactions will be imported if there are income. (Looks nice, I can stop working almost :-))

[TEST.txt](https://github.com/firefly-iii/firefly-iii/files/1278420/TEST.txt)
[RabobankImport.txt](https://github.com/firefly-iii/firefly-iii/files/1278423/RabobankImport.txt)
(changed the .json to txt befor uploaded to the github)

I don't see any errors in the /var/www/firefly-iii/storage/logs/ is this an bug? or just my misstake somewhere?

Clean install on new and updated ubuntu vm.
Firefly-iii version 4.6.4

Thanks in advance

Uffer

**Comment by JC5** [comment] 2017-09-05 18:46
Both your transactions import correctly, I'm afraid. I'm not really sure what is happening.

![screen shot 2017-09-05 at 20 44 31](https://user-images.githubusercontent.com/5889984/30077118-2143b062-927b-11e7-9a3a-d6e1c59d327e.png)

Could you [enable debugging](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) and post the log of the import?

**Comment by uffer** [comment] 2017-09-06 09:26
Ok that is strange....

Same import:


![capture](https://user-images.githubusercontent.com/18116064/30104441-e87ce296-92f5-11e7-86aa-95f3c3ed7ea9.PNG)

[firefly-iii-2017-09-06-log.txt](https://github.com/firefly-iii/firefly-iii/files/1280529/firefly-iii-2017-09-06-log.txt)

Different results. If you need more information, please let me know. Thanks for the help!

**Comment by AxisNL** [comment] 2017-09-06 10:48
I have the same problem. I just deleted my entire firefly 3.8 vm, and started from scratch again. Created a new VM, new empty db, and did a clean install of firefly 4.6.4. I recreated three accounts. I went to the rabobank site, got all transactions starting 01-01-2017, intending to start out fresh. I imported all transactions using your default rabobank json config from the wiki, and it imported. But, in my case as well, all transactions are marked as revenue.

**Comment by JC5** [comment] 2017-09-06 11:56
I see the import routine has been updated between your version and the current development version. This means that the problem is fixed in the development-version, which I plan to release soon.

Thank you both for reporting this! With a little luck, this problem will be gone in a short while.

**Comment by uffer** [comment] 2017-09-06 12:20
Ok, thanks for the help!

**Comment by JC5** [comment] 2017-09-09 05:25
New release is live.

**Closed by JC5** 2017-09-09 05:25 UTC
Labels: bug, fixed
