### ISSUE TITLE
Piggy bank events are not being created

### ISSUE THREAD

**Issue by JeroenED** [firefly-iii/firefly-iii#3745] opened 2020-08-29 09:22 UTC
**Bug description**
I am running Firefly III version 5.3.3, and my problem is: When creating a transaction that is link to a piggy bank the link is not created

**Steps to reproduce**
1. Create a piggy bank (if you don't have one)
2. Create a transaction and select the piggy bank in the piggy bank selector

**Extra info**
Browser: Firefox 80.0 + Chrome 85.0 (Both show the same issue)
OS: Pop_OS! Linux 20.04.1

**Bonus points**

- I checked the logs and database myself and found that the transaction does contains correct piggy bank id without name and that there is simply no record in the piggy_bank_events table

**Comment by JC5** [comment] 2020-08-29 10:03
I just verified this, and it seems to work for me. However

- The transaction you make must be a transfer.
- In the same currency as the piggy bank.
- Involving the account of the piggy bank in either the source or destination account.

Here's an example from the demo site (until it resets):

- https://demo.firefly-iii.org/piggy-banks/show/8
- https://demo.firefly-iii.org/transactions/show/467

**Comment by JeroenED** [comment] 2020-08-30 08:52
Hi @JC5,

I saw the demo transactions and I even was able to create piggy transactions myself on the demo environment. This being said it is clear (at least to me) that the issue in connected to the environment or settings.

Here you can find debug logs as I suspect they might be interesting.
[ff3-audit-2020-08-30.log](https://github.com/firefly-iii/firefly-iii/files/5146511/ff3-audit-2020-08-30.log)
[ff3-fpm-fcgi-2020-08-30.log](https://github.com/firefly-iii/firefly-iii/files/5146512/ff3-fpm-fcgi-2020-08-30.log)

And here are some more details on my environment.
```
$ php -v
PHP 7.4.9 (cli) (built: Aug  7 2020 14:30:01) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

// Since database is SQLite
$ php -r "print_r(SQLite3::version());"
Array
(
    [versionString] => 3.31.1
    [versionNumber] => 3031001
)

```

If you would need any more informations, please let me know.

**Comment by JC5** [comment] 2020-08-31 06:47
Thanks, i'll check it out. Not sure what's going on.

**Comment by JeroenED** [comment] 2020-09-07 08:04
Hi @JC5 Do you have any results on the research already. I started to think it might be connected to a change in PHP7.4. i'll try to verify it this evening as I'm not sure if true or not.

**Comment by JC5** [comment] 2020-09-07 11:03
There's not enough info in the log files to be sure what the cause is but I've added some details and a potential fix for the most obvious culprit. This will be included in the next release. Thanks for reminding me.

**Closed** 2020-09-13 05:49 UTC
Labels: bug, fixed

**Comment by JC5** [comment] 2020-09-13 08:31
Closed because beta 1 is out.

**Comment by JeroenED** [comment] 2020-09-13 10:05
Hi, I just installed the beta and can confirm the issue is resolved!
