### ISSUE TITLE
First Date of recurring transaction breaks Type of repetition field in French

### ISSUE THREAD

**Issue by Bubka** [firefly-iii/firefly-iii#1550] opened 2018-07-13 07:32 UTC
Hello,

**Bug description**
I am running Firefly III version 4.7.5 with French localization.

In some cases, when selecting the `First Date` of a recurring transaction in the new|edit recurring transaction form, the `Type of repetition` select field failed to load its options.

After some testing, I identified that the bug occurred when the selected date is a day of one of those month:
- Février (February)
- Août (August)
- Décembre (December)

As you can see each of those 3 months has a special character in its French spelling wich is, i think, the root cause of the bug.

**Steps to reproduce**
- Set firefly in French
- Open a new recurring transaction form
- Set a `First Date` as a day in one of the previously listed month
- and, ta-da:
<img width="375" alt="recurringfirstdatebug" src="https://user-images.githubusercontent.com/858858/42679484-5db8d9ae-8682-11e8-9fda-a3e6d1a5331d.png">

**Extra info**
Firefox 12.1 (10941) for iOS 11.3 (15E216)

Debug information generated at 2018-07-13 09:48:15 Europe/Paris for Firefly III version **4.7.5**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.5 |
| FF API version | 0.4 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.1.17 |
| Display errors | Off |
| Session start | 2018-07-01 00:00:00 |
| Session end | 2018-07-31 23:59:59 |
| Session first | 2006-01-02 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US" | 'en_US' |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | |
| User agent | Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/12.1b10941 Mobile/15E216 Safari/605.1.15 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, imagick, session, intl, json, mbstring, mcrypt, memcached, standard, mysqlnd, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, Reflection, imap, SimpleXML, soap, sockets, mongodb, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, mysqli, cgi-fcgi, ionCube Loader, Zend OPcache |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.7.1, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.4, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.26, laravel/passport@v5.0.3, laravelcollective/html@v5.6.10, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.45, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.15, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, swiftmailer/swiftmailer@v6.1.0, symfony/console@v4.1.1, symfony/css-selector@v4.1.1, symfony/debug@v4.1.1, symfony/event-dispatcher@v4.1.1, symfony/finder@v4.1.1, symfony/http-foundation@v4.1.1, symfony/http-kernel@v4.1.1, symfony/polyfill-ctype@v1.8.0, symfony/polyfill-mbstring@v1.8.0, symfony/polyfill-php56@v1.8.0, symfony/polyfill-php72@v1.8.0, symfony/polyfill-util@v1.8.0, symfony/process@v4.1.1, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.1.1, symfony/translation@v4.1.1, symfony/var-dumper@v4.1.1, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.3, vlucas/phpdotenv@v2.5.0, zendframework/zend-diactoros@1.8.0, |

**Comment by JC5** [comment] 2018-07-13 13:58
I cannot replicate this. Firefly III works fine in French. I can see the repetition types no matter what I do.

However, you have a French Firefox browser as well, and I do not. On iOS no less.

I will do some digging!

**Comment by JC5** [comment] 2018-07-13 14:00
<img width="613" alt="screen shot 2018-07-13 at 15 59 46" src="https://user-images.githubusercontent.com/5889984/42695499-d15707d6-86b5-11e8-981d-789f479b68db.png">

**Comment by Bubka** [comment] 2018-07-15 18:51
I tried at home, here is what I identified: the issue seems to be a server side configuration issue (I self-host my firefly instance). All request with one of the previously listed month return 500 HTTP responses ! 

```
https://domain.tld/recurring/suggest?date=2018-08-08&pre_select=daily
```
returns
```
HTTP/1.1 500 Internal Server Error
Date: Sun, 15 Jul 2018 17:39:22 GMT
Server: Apache
X-Powered-By: PHP/7.1.17
Cache-Control: no-cache, private
Set-Cookie: mediaplan=R3[...]14; path=/; expires=Sun, 15-Jul-2018 18:40:06 GMT
laravel_token=eyiI6IE[...]MjifQ%3D3D; expires=Sun, 15-Jul-2018 19:39:22 GMT; Max-Age=7200; path=/; httponly
XSRF-TOKEN=epiI6kh[...]NhjA5In%3D; expires=Sun, 15-Jul-2018 19:39:22 GMT; Max-Age=7200; path=/
firefly_session=eJpdiIm9[...]WJmUzNJ9; expires=Sun, 15-Jul-2018 19:39:22 GMT; Max-Age=7200; path=/; httponly
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8
X-IPLB-Instance: 17338
```

The response body is an HTML page that show `Be right back.`

If i set the request with any another month i get a 200 response as expected.

Any idea before i dive into apache/php settings ?

**Comment by JC5** [comment] 2018-07-15 18:55
The “be right back” page indicates an internal Firefly III error. I suggest turning on debug mode (see the link below). This might show what is happening on screen.

The logs for Firefly III are stored in /storage/logs and might also say what happened. 

https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode

**Comment by Bubka** [comment] 2018-07-16 12:29
I have set APP_DEBUG to true, here is the error report i received by email just after setting a buggy transaction date:
```
Uncaught InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded in /.../vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:75
Stack trace: 
#0 /.../vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\Http\JsonResponse->setData(Array)
#1 /.../vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(31): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array, 500, Array)
#2 /.../vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(83): Illuminate\Http\JsonResponse->__construct(Array, 500, Array, 0)
#3 /.../app/Exceptions/Handler.php(100): Illuminate\Routing\ResponseFactory->json(Array, 500)
#4 /.../vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): FireflyIII\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(InvalidArgumentException)) 
#5 /.../vendor/laravel/framework/src/Illuminate/Foundati
```
The error was of type "Symfony\Component\Debug\Exception\FatalErrorException".

The error occured on/at: Mon, 16 Jul 2018 14:07:45 +0200.

This error occured in file `/.../vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php` on line 75 with code 1.

**Comment by JC5** [comment] 2018-07-16 14:38
It seems that the files that contain the translations are not stored as UTF-8 / ASCII files. This is probably caused by the special characters. Perhaps combined with your operating system (on the server).

In turn, this gives you the "Malformed UTF-8 characters"-error.

I see that the error stack-trace is cut off halfway. 

Can you share the entire stacktrace? I need it to find out where to apply the fix.

**Comment by Bubka** [comment] 2018-07-16 22:43
Here is a full debug logs file of what happens when i select a month with a special character:
https://send.firefox.com/download/d11f2bb640/#jkzMKFNNY6xjzxtp9jNXnw (valid for 2 downloads || 24h)

**Comment by JC5** [comment] 2018-07-17 14:48
OK, this seems to be a problem with the installation unfortunately. I've been trying this but I can't reproduce it on my Sandstorm machine.

Could you share the output of the command `locale -a`?

**Comment by Bubka** [comment] 2018-07-17 15:29
```
aa_DJ
aa_DJ.utf8
aa_ER
aa_ER@saaho
aa_ET
af_ZA
af_ZA.utf8
ak_GH
am_ET
an_ES
an_ES.utf8
anp_IN
ar_AE
ar_AE.utf8
ar_BH
ar_BH.utf8
ar_DZ
ar_DZ.utf8
ar_EG
ar_EG.utf8
ar_IN
ar_IQ
ar_IQ.utf8
ar_JO
ar_JO.utf8
ar_KW
ar_KW.utf8
ar_LB
ar_LB.utf8
ar_LY
ar_LY.utf8
ar_MA
ar_MA.utf8
ar_OM
ar_OM.utf8
ar_QA
ar_QA.utf8
ar_SA
ar_SA.utf8
ar_SD
ar_SD.utf8
ar_SS
ar_SY
ar_SY.utf8
ar_TN
ar_TN.utf8
ar_YE
ar_YE.utf8
as_IN
ast_ES
ast_ES.utf8
ayc_PE
az_AZ
be_BY
be_BY@latin
be_BY.utf8
bem_ZM
ber_DZ
ber_MA
bg_BG
bg_BG.utf8
bho_IN
bn_BD
bn_IN
bo_CN
bo_IN
br_FR
br_FR@euro
br_FR.utf8
brx_IN
bs_BA
bs_BA.utf8
byn_ER
C
ca_AD
ca_AD.utf8
ca_ES
ca_ES@euro
ca_ES.utf8
ca_ES.utf8@valencia
ca_ES@valencia
ca_FR
ca_FR.utf8
ca_IT
ca_IT.utf8
cmn_TW
crh_UA
csb_PL
cs_CZ
cs_CZ.utf8
C.UTF-8
cv_RU
cy_GB
cy_GB.utf8
da_DK
da_DK.utf8
de_AT
de_AT@euro
de_AT.utf8
de_BE
de_BE@euro
de_BE.utf8
de_CH
de_CH.utf8
de_DE
de_DE@euro
de_DE.utf8
de_LI.utf8
de_LU
de_LU@euro
de_LU.utf8
doi_IN
dv_MV
dz_BT
el_CY
el_CY.utf8
el_GR
el_GR.utf8
en_AG
en_AU
en_AU.utf8
en_BW
en_BW.utf8
en_CA
en_CA.utf8
en_DK
en_DK.iso885915
en_DK.utf8
en_GB
en_GB.iso885915
en_GB.utf8
en_HK
en_HK.utf8
en_IE
en_IE@euro
en_IE.utf8
en_IN
en_NG
en_NZ
en_NZ.utf8
en_PH
en_PH.utf8
en_SG
en_SG.utf8
en_US
en_US.iso885915
en_US.utf8
en_ZA
en_ZA.utf8
en_ZM
en_ZW
en_ZW.utf8
eo
eo.utf8
es_AR
es_AR.utf8
es_BO
es_BO.utf8
es_CL
es_CL.utf8
es_CO
es_CO.utf8
es_CR
es_CR.utf8
es_CU
es_DO
es_DO.utf8
es_EC
es_EC.utf8
es_ES
es_ES@euro
es_ES.utf8
es_GT
es_GT.utf8
es_HN
es_HN.utf8
es_MX
es_MX.utf8
es_NI
es_NI.utf8
es_PA
es_PA.utf8
es_PE
es_PE.utf8
es_PR
es_PR.utf8
es_PY
es_PY.utf8
es_SV
es_SV.utf8
es_US
es_US.utf8
es_UY
es_UY.utf8
es_VE
es_VE.utf8
et_EE
et_EE.iso885915
et_EE.utf8
eu_ES
eu_ES@euro
eu_ES.utf8
eu_FR
eu_FR@euro
eu_FR.utf8
fa_IR
ff_SN
fi_FI
fi_FI@euro
fi_FI.utf8
fil_PH
fo_FO
fo_FO.utf8
fr_BE
fr_BE@euro
fr_BE.utf8
fr_CA
fr_CA.utf8
fr_CH
fr_CH.utf8
fr_FR
fr_FR@euro
fr_FR.utf8
fr_LU
fr_LU@euro
fr_LU.utf8
fur_IT
fy_DE
fy_NL
ga_IE
ga_IE@euro
ga_IE.utf8
gd_GB
gd_GB.utf8
gez_ER
gez_ER@abegede
gez_ET
gez_ET@abegede
gl_ES
gl_ES@euro
gl_ES.utf8
gu_IN
gv_GB
gv_GB.utf8
hak_TW
ha_NG
he_IL
he_IL.utf8
hi_IN
hne_IN
hr_HR
hr_HR.utf8
hsb_DE
hsb_DE.utf8
ht_HT
hu_HU
hu_HU.utf8
hy_AM
hy_AM.armscii8
ia_FR
id_ID
id_ID.utf8
ig_NG
ik_CA
is_IS
is_IS.utf8
it_CH
it_CH.utf8
it_IT
it_IT@euro
it_IT.utf8
iu_CA
iw_IL
iw_IL.utf8
ja_JP.eucjp
ja_JP.utf8
ka_GE
ka_GE.utf8
kk_KZ
kk_KZ.utf8
kl_GL
kl_GL.utf8
km_KH
kn_IN
kok_IN
ko_KR.euckr
ko_KR.utf8
ks_IN
ks_IN@devanagari
ku_TR
ku_TR.utf8
kw_GB
kw_GB.utf8
ky_KG
lb_LU
lg_UG
lg_UG.utf8
li_BE
lij_IT
li_NL
lo_LA
lt_LT
lt_LT.utf8
lv_LV
lv_LV.utf8
lzh_TW
mag_IN
mai_IN
mg_MG
mg_MG.utf8
mhr_RU
mi_NZ
mi_NZ.utf8
mk_MK
mk_MK.utf8
ml_IN
mni_IN
mn_MN
mr_IN
ms_MY
ms_MY.utf8
mt_MT
mt_MT.utf8
my_MM
nan_TW
nan_TW@latin
nb_NO
nb_NO.utf8
nds_DE
nds_NL
ne_NP
nhn_MX
niu_NU
niu_NZ
nl_AW
nl_BE
nl_BE@euro
nl_BE.utf8
nl_NL
nl_NL@euro
nl_NL.utf8
nn_NO
nn_NO.utf8
nr_ZA
nso_ZA
oc_FR
oc_FR.utf8
om_ET
om_KE
om_KE.utf8
or_IN
os_RU
pa_IN
pap_AN
pap_AW
pap_CW
pa_PK
pl_PL
pl_PL.utf8
POSIX
ps_AF
pt_BR
pt_BR.utf8
pt_PT
pt_PT@euro
pt_PT.utf8
quz_PE
ro_RO
ro_RO.utf8
ru_RU
ru_RU.cp1251
ru_RU.koi8r
ru_RU.utf8
ru_UA
ru_UA.utf8
rw_RW
sa_IN
sat_IN
sc_IT
sd_IN
sd_IN@devanagari
se_NO
shs_CA
sid_ET
si_LK
sk_SK
sk_SK.utf8
sl_SI
sl_SI.utf8
so_DJ
so_DJ.utf8
so_ET
so_KE
so_KE.utf8
so_SO
so_SO.utf8
sq_AL
sq_AL.utf8
sq_MK
sr_ME
sr_RS
sr_RS@latin
ss_ZA
st_ZA
st_ZA.utf8
sv_FI
sv_FI@euro
sv_FI.utf8
sv_SE
sv_SE.iso885915
sv_SE.utf8
sw_KE
sw_TZ
szl_PL
ta_IN
ta_LK
te_IN
tg_TJ
tg_TJ.utf8
the_NP
th_TH
th_TH.utf8
ti_ER
ti_ET
tig_ER
tk_TM
tl_PH
tl_PH.utf8
tn_ZA
tr_CY
tr_CY.utf8
tr_TR
tr_TR.utf8
ts_ZA
tt_RU
tt_RU@iqtelif
ug_CN
uk_UA
uk_UA.utf8
unm_US
ur_IN
ur_PK
uz_UZ
uz_UZ@cyrillic
uz_UZ.utf8
ve_ZA
vi_VN
wa_BE
wa_BE@euro
wa_BE.utf8
wae_CH
wal_ET
wo_SN
xh_ZA
xh_ZA.utf8
yi_US
yi_US.utf8
yo_NG
yue_HK
zh_CN
zh_CN.gb18030
zh_CN.gbk
zh_CN.utf8
zh_HK
zh_HK.utf8
zh_SG
zh_SG.gbk
zh_SG.utf8
zh_TW
zh_TW.euctw
zh_TW.utf8
zu_ZA
zu_ZA.utf8
```

**Comment by Bubka** [comment] 2018-07-18 06:16
the config.php edit fixes the bug :+1: &#128079;

Is there a way for you to handle a such case in your code or will i have to edit the file after each upgrade ?

**Comment by JC5** [comment] 2018-07-18 06:34
I will update the file centrally, so you won't have to fix this in the future :+1:

**Comment by JC5** [comment] 2018-08-01 05:34
And this should be fixed in the current release as well.

**Closed by JC5** 2018-08-01 05:34 UTC
Labels: possible bug

**Comment by simon511000** [comment] 2019-01-10 16:38
No, It's not fixed in the current release : 
![temp](https://user-images.githubusercontent.com/31013205/50982900-80ffb080-14fe-11e9-825a-7c5794802406.PNG)

**Comment by simon511000** [comment] 2019-01-10 16:44
![temp](https://user-images.githubusercontent.com/31013205/50983267-6b3ebb00-14ff-11e9-8dfa-3b15974b80ff.PNG)

**Comment by simon511000** [comment] 2019-01-10 19:08
@JC5

**Comment by JC5** [comment] 2019-01-10 19:10
Looks like I forgot to update the file. The fix still works though.
