### ISSUE TITLE
Different Redirect behaviour since 4.7.16

### ISSUE THREAD

**Issue by forcaeluz** [firefly-iii/firefly-iii#2179] opened 2019-03-17 13:39 UTC
I am running Firefly III version 4.7.17

**Description**
In 4.7.15 and earlier, if I saved a new withdrawal/income/tranfer I would get redirected to the page I was previously (And that usually would be the dashboard). Since 4.7.16 and later, I'm being redirected to the "Create" page.

Although I'm not sure if I dislike this, I wonder, is this by design?

**Extra info**
Debug information generated at 2019-03-17 14:33:05 Europe/Amsterdam for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.15-0ubuntu0.18.04.1 |
| Display errors | Off |
| Session start | 2019-03-01 00:00:00 |
| Session end | 2019-03-31 00:00:00 |
| Session first | 2016-11-20 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, gd, intl, imap, ldap, bcmath, zip, iconv, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gettext, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache | 

**Bonus points**
- Tested on the demo site and have the same behaviour there.

**Comment by JC5** [comment] 2019-03-17 14:12
Yes, but this is not by design. I hope to be able to revert it in the next release.

**Comment by aelsenaar** [comment] 2019-07-21 10:43
Hi, any progress on this issue?

**Comment by JC5** [comment] 2019-07-21 11:50
You’ll know when it’s fixed, thanks :)

**Comment by aelsenaar** [comment] 2019-07-21 12:26
> You’ll know when it’s fixed, thanks :)

:-) Thx!

**Comment by JC5** [comment] 2019-08-01 04:23
A fix is implemented on the dev site at https://dev.firefly-iii.org/. Login is the same as the demo site (demo@firefly / demo).

I still got to test it but the fallback should be a bit more graceful.

**Comment by aelsenaar** [comment] 2019-08-04 08:24
> A fix is implemented on the dev site at https://dev.firefly-iii.org/. Login is the same as the demo site (demo@firefly / demo).

Back from vacation and checked the dev -site just now but I am unable to test this. The dev-site seems to have some problems with column 'transaction_journals.transaction_group_id'.

**Comment by JC5** [comment] 2019-08-04 08:26
Thx for letting me know. Should be fixed now.

**Comment by aelsenaar** [comment] 2019-08-05 06:56
> A fix is implemented on the dev site at https://dev.firefly-iii.org/. Login is the same as the demo site (demo@firefly / demo).
>
> I still got to test it but the fallback should be a bit more graceful.

I tested this but I was expecting some other behavior. I expected the edit page to close and return to the previous page. In my test case, the page with the list of transactions. Is my expectation wrong?

**Comment by JC5** [comment] 2019-08-05 14:54
Yeah good point, that's the only view that doesn't listen to the new redirect rules. Stay tuned. It's because that particular view got a rewrite.

**Comment by JC5** [comment] 2019-08-05 17:46
Should now also be fixed.

**Comment by aelsenaar** [comment] 2019-08-07 07:58
> Should now also be fixed.

Tested, looks fine now. Thx!

**Closed** 2019-08-09 19:03 UTC
Labels: bug, fixed
