### ISSUE TITLE
JavaScript page/text after storing transaction (iOS / Firefox Mobile) - Firefly III 5.6.0 - Layout v2

### ISSUE THREAD

**Issue by JanFeld** [firefly-iii/firefly-iii#5110] opened 2021-09-23 17:21 UTC
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When storing a transaction on my mobile phone (iOS 15 / Firefox) i'll get forwarded to a text page which looks like the in the images attached.

The transaction is stored and seems to be correct.
I can access all pages afterwards without any issues.
The "Transaction .. stored" message is displayed on the first access of any FF3 page afterwards.

### Expected behaviour

Simply go back to the last page where i've been coming from.
Including a message that the transaction has been stored.

### Debug information

* iOS 15.0
* Firefox Daylight 37.0 (5971)
* Firefly 3 5.6.0 - Layout v2

### Steps to reproduce

Use a mobile phone (preferably iOS with OS 15 and Firefox) and try to store a transaction using the layout v2.

### Additional info

Sadly i'm not able to reproduce this issue on the demo page because i've forgot how to get to the layout-v2 preview..

The screenshots below show the page.

![ff3_bug_01](https://user-images.githubusercontent.com/22739965/134554319-ac1d30a6-cc03-4377-8c02-a2256865cb3d.png)

![ff3_bug_02](https://user-images.githubusercontent.com/22739965/134554327-054159ae-88b2-4a26-9aa0-14c7a52ce362.png)

Cheers,
Jan

**Comment by JC5** [comment] 2021-09-23 17:26
Thanks, I noticed it as well. I hoped it was a glitch. I'll pick it up!

**Comment by schneekluth** [comment] 2021-09-24 10:12
It also appears with the legacy UI on iOS 15.

**Comment by JC5** [comment] 2021-09-25 03:14
Fixed in the next release

**Closed** 2021-09-25 12:26 UTC
Labels: bug, fixed

**Comment by rygos** [comment] 2021-09-28 18:57
i have the same Problem. serviceworker.js is viewed every time I submit a transaction (new or edit).
Safari on macOS Monterey. On Chrome everything works as expected.

**Comment by JC5** [comment] 2021-09-29 14:24
Which version of Firefly III are you running, please?

**Comment by rygos** [comment] 2021-09-30 14:14
The latest. 5.6.1.
I can reproduce the error with the installed version on my server or also on your demo installation.

When I add or edit a transaction, after clicking on the Save button, this Javascript page appears, which is shown in the screenshots above.

The URL of showed page (after edit):
https://demo.firefly-iii.org/serviceworker.js?transaction_group_id=381&message=updated

**Comment by JC5** [comment] 2021-10-01 03:28
The URL is excluded from being used as a redirect. I checked the code and I can't replicate this. Since the service worker is asynchronous it's not even supposed to be loaded by Safari directly. I'm not spending more effort on this untill Montery is out of beta.
