### ISSUE TITLE
Deleted transactions don't get updated

### ISSUE THREAD

**Issue by creylopez** [firefly-iii/firefly-iii#6739] opened 2022-12-23 07:45 UTC
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have experienced several times that if I delete a transaction the balance does not get updated. If I look into the database, I can see that the transaction is still there.

I tried deleting the transaction directly in the database but balance does not get updated. I know that by deleting the transaction manually I could be missing something.

### Expected behaviour

When a transaction is deleted, balances should be updated accordingly.

### Debug information

Debug information generated at 2022-12-23 07:45:03 UTC for Firefly III version **5.7.15**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.15 |
| Firefly III API | 1.5.6 |
| Build | 298, 02-11-2022 05:00:04 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.11` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | Europe/Madrid |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-12-01 00:00:00 |
| Session end | 2022-12-31 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 1 |
| User language | es_ES |
| User locale | es_ES |
| Attempt at "es_ES.utf8" | 'es_ES.utf8' |
| Attempt at "es_ES.UTF-8" | 'es_ES.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15 |

**Comment by JC5** [comment] 2022-12-23 08:13
I'm aware, yes. There are several issues about this already, and the problem has been fixed in the `develop` branch. The root cause is that the balance (cached on the server side) is not being refreshed when a transaction is removed.

Deleted items do not get deleted from the database, that's not the problem.

**Comment by creylopez** [comment] 2022-12-23 08:31
Super. I’ll wait for the new release. Regarding the deletion or not of the transaction, this morning the transaction was not deleted. I could see it in the database. Other times I cannot say Saludos / Best regards / Viele Grüße Celestino ReyEl 23 dic 2022, a las 9:13, James Cole ***@***.***> escribió:﻿
I'm aware, yes. There are several issues about this already, and the problem has been fixed in the develop branch. The root cause is that the balance (cached on the server side) is not being refreshed when a transaction is removed.
Deleted items do not get deleted from the database, that's not the problem.

**Comment by JC5** [comment] 2022-12-23 08:33
Yes, they will always be visible in the database. Notice how the `deleted_at` column is filled in, after deleting the transaction.

If you browse to `/flush`, the server cache will be cleared.

**Comment by iamwebwiz** [comment] 2022-12-23 11:42
Very helpful @JC5 , thank you. I was having this very issue.

**Comment by jhelbig** [comment] 2022-12-23 23:41
I would also like to add this is impacting importing as well.

I had to correct a discrepancy lost in an entire month and it was easier to delete all transactions for the month and re-import from source.  So I thought...

If records are not actually deleted from the database would it not be better to name the action "void transaction" instead of "delete"?

**Comment by JC5** [comment] 2022-12-24 03:30
The behavior you describe is [intentional and well-documented](https://docs.firefly-iii.org/data-importer/errors/duplicate_transactions/). The button will not be renamed.

**Comment by jhelbig** [comment] 2022-12-24 17:56
> The behavior you describe is [intentional and well-documented](https://docs.firefly-iii.org/data-importer/errors/duplicate_transactions/). The button will not be renamed.

> Firefly III will also check deleted transactions when checking for duplicates. This is on purpose. If your import contains bad transactions or informative message hidden as transactions, they will not be re-imported after you've deleted them.

That seems counterintuitive.  If you delete something you typically do not expect to ever see it again.  This is the message you get when you attempt to delete a transaction.  It also states this cannot be undone, but that's untrue.
![image](https://user-images.githubusercontent.com/11377461/209446040-e82976d1-afc2-464f-a942-e6c5d8144f77.png)

I get why a financial tracking system would never permanently delete items, but I don't understand why voided(pronounced "deleted") transactions would have any impact on new transactions that are being imported since they should no longer be a part of the active dataset.

At this point I have little choice but to circumvent the intended use of the application and make changes directly to the database.  I'm sure that wasn't an intended outcome when this functionality was developed.

I just hope I know what I'm doing to the logical model and don't break something 🤷

The snark is real, and I apologize for it, but the frustration is real on this because the documentation does not document _why_ this pattern is used.  As an end-user I feel misinformed based on common terms that are used throughout the industry.

**Comment by JC5** [comment] 2022-12-24 18:15
>I'm sure that wasn't an intended outcome when this functionality was developed. [..] I just hope I know what I'm doing to the logical model and don't break something 🤷

You have to realize I don't really care 🤷🏻, but I do hope you know what you're doing. Enjoy the holiday season.

**Comment by creylopez** [comment] 2022-12-24 18:19
IMHO, that is working well once you understand how it works. Better not to touch it. Saludos / Best regards / Viele Grüße Celestino ReyEl 24 dic 2022, a las 19:15, James Cole ***@***.***> escribió:﻿

I'm sure that wasn't an intended outcome when this functionality was developed. [..] I just hope I know what I'm doing to the logical model and don't break something 🤷

You have to realize I don't really care 🤷🏻, but I do hope you know what you're doing. Enjoy the holiday season.

**Comment by jhelbig** [comment] 2022-12-24 18:59
> > I'm sure that wasn't an intended outcome when this functionality was developed. [..] I just hope I know what I'm doing to the logical model and don't break something 🤷
> 
> You have to realize I don't really care 🤷🏻, but I do hope you know what you're doing. Enjoy the holiday season.

Great that we have established that.  It's a shame that you put forth the same efforts on your responses as you do with your product.

**Comment by JC5** [comment] 2022-12-24 19:13
I guess you get what you give. Again, I hope enjoy the holiday season.

**Closed by JC5** 2022-12-24 19:13 UTC
Labels: bug, fixed
