### ISSUE TITLE
Understanding Importing and Transaction Flow/Accounts

### ISSUE THREAD

**Issue by StarScream159** [firefly-iii/firefly-iii#557] opened 2017-02-10 19:31 UTC
Hello,

Sorry if this question has been asked and answered, but I'm having a really hard time wrapping my head around everything and how I can use this with my bank and credit card statements.

From a fresh install, I created my bank account (chequing) and I exported my last months bank statement in CSV and attempted to import the file into Firefly. I was going to start here, then add my Credit Card(s) and Mortgage Accounts, Investment Account, etc. later. So importing works and all transactions are assigned to the chequing account, but I'm not clear on what fields I should be labeling as such nor am I sure if I am doing this correctly. I've tried to read the documentation, but I can't wrap my head around it - maybe it is due to the way my bank's exported data is... I'm not sure.

My bank gives me a simple CSV file in the following format (sample numbers and transactions follow):

Date | Description | Withdraws ($) | Deposits ($) | Balance ($)
------------ | ------------- | ------------ | ------------- | -------------
1/3/2017 | BURGER KING | 6.50 | | 10,000.00
1/4/2017 | SUBWAY | 5.00 | | 9,995.00
1/5/2017 | CVS | 23.50 | | 9971.50
1/9/2017 | GC 2512-DEPOSIT | | 300 | 10271.50
1/10/2017 | DOLLARAMA ST NO 357 _F | 9.75 | | 10261.75
1/13/2017 | E TFR C39f0s9 | | 50.00 | 10311.75
1/15/2017 | HILTON TOR | 150.00 | | 10161.75
1/20/2017 | MORTGAGE | 500.00 | | 9661.75
1/22/2017 | LOTTOWIN | | 5555.00 | 15216.75

And so on.

When the import happens, it seems to assume all transactions are purchases and I can't find a way to set deposits correctly.

Am I doing something wrong? Should I be organizing this differently?

Thanks for reading, I really want to understand how this works. I love the look and feel of the layout. Just need to wrap my head around how transactions relate to accounts.

EDIT: Added a few more sample transactions. From the documentation that I was reading and trying to understand, and correct me where I am wrong, all transactions go from one account to another. So from my example data set, would there be a "BURGER KING", "SUBWAY", "CVS", etc. account? Should I bet setting that up before importing? Do I have to create an account for *every* place I shop at?

**Comment by JC5** [comment] 2017-02-11 09:10
Hey! Let's see.

You don't need to set up an account for every shop. That would be expense accounts, and Firefly will create them automatically.

To import your CSV successfully, the columns withdrawal and deposits should be combined into one column: a negative amount for withdrawals and a positive one for deposits.

The date format in Firefly should be m/d/Y I think.

There should be one asset account (called "Your bank asset") which you should select as the default destination.

The balance column is not necessary.

The sheet should look something like this:

Date | Description | Amount ($)
------------ | ------------- | ------------ 
1/3/2017 | BURGER KING | -6.50
1/4/2017 | SUBWAY | -5.00
1/5/2017 | CVS | -23.50
1/9/2017 | GC 2512-DEPOSIT | 300

In Firefly, these columns would get these types (no need to map them):

- Date
- Opposing account name
- Amount

That will leave the descriptions empty but the transactions should be imported correctly.

**Comment by StarScream159** [comment] 2017-02-11 22:04
Okay great! That makes *so* much sense. Thanks. So I tested a few hundred transactions and it works pretty good (thank goodness for excel macros lol), I can see money going in and out like it should. But I have a follow up question if you don't mind:

My bank only allows me to go back 18 months (ie. the oldest transaction I can start at is September 1st, 2015). So I figured what I could do is delete everything so I start fresh and then create the bank account again but then put in an initial balance on the day before the import (so in this case it would be October 31st balance). Then as the import happens, it'll adjust the account balance accordingly starting with any transactions. I can't seem to get it to work like that. After the import, if I look at the graphs that get generated it starts the account balance at 0... and then since the first transaction is a withdrawal it is a negative balance on September 1st, 2015).

Am I not using the "initial balance" correctly when I open/create the account before importing?

**Comment by JC5** [comment] 2017-02-12 07:45
The way you think is correct! What should work is this routine:

- Create the account, and set no opening balance.
- Import and verify.
- Take your actual balance (let's say 500) and subtract it from what Firefly is reporting (ie 300). In this case, your opening balance should be 200.

Edit the account, set the date on August 30th (the day before September 1st) and it should look fine.

**Comment by StarScream159** [comment] 2017-02-15 19:40
Thanks so much @JC5. That works well. So I started over again to make sure I understand the complete flow and now I'm getting hooked up on the rules.

My goal here is to create rules for various categories. So like fast food, groceries, etc.. The way I see best to set it up is to go by the transaction description/title. So with that lets say I create a new rule:
Triggers | Actions
------------- | ------------
description contains "SUBWAY" | set category "Fast Food"

This works great when there is only a single trigger per rule, but once I add another it stops working.
For example:
Triggers | Actions
------------- | ------------
description contains "SUBWAY"<br>description contains "BURGER KING | set category "Fast Food"

This would now not trigger at all. So I assumed that this was due to the fact that it looks for and "AND" between the triggers and not an "OR". So it would be looking for "SUBWAY" and "BURGER KING", which doesn't exist. So it never triggers.

Assuming that is correct, I then thought we could use the "Stop processing other triggers" option for each trigger to get it to be treated as an "OR". But that doesn't seem to work either.

What's the best way to do this? Do I have to create a whole new rule set for each individual trigger case? That isn't a problem, I was just trying to organize all common triggers into the same rule. ie. all fast food places in one rule, all grocery stores in another, etc..

Thanks for the support thus far.

**Comment by JC5** [comment] 2017-02-16 08:29
The problem is that rules use "AND", like you said. Rules that trigger on multiple source account names won't trigger. I must remember to expand the user interface to mention this.

You'll have to use separate rules. Keep them simple and verify they work. You can use rule groups to keep them together.

If you want to see why a specific rule is not triggered, you can open the `.env` file and change the app_log_level to `debug`. This makes Firely record almost everything it is doing, and especially when creating a new transaction (either automatically or manually) these logs will be _filled_ with records detailing why rules trigger or not.

**Comment by StarScream159** [comment] 2017-02-17 00:59
Okay, I'll create them all separate. Not 100% sure what you mean by "Rules that trigger on multiple source account names won't trigger." Do you mean that if you use more then one of the "Source account ..." triggers? Because in my scenario above I didn't. I was only using the description contains trigger, and I only have 1 account.

**Comment by JC5** [comment] 2017-02-17 05:38
Apologies, I mentioned the wrong trigger! But the same applies to adding multiple triggers of "description contains".

**Comment by Aquariu** [comment] 2017-09-22 22:04
Dear all,

Sorry to resurrect an old thread but I couldn't find anything related and this looks close enough to my issue.

I'm looking for the documentation about everything that's possible on the command line. It seems, thanks to issue threads like [this one](php artisan firefly:start-import), that I can import bank data csv from the command line. Something along the line of `php artisan firefly:start-import` or` php artisan firefly:create-import`. Where can I find details, or example of how to do this ? 

I started using firefly not long ago and I love it, but the missing piece in my puzzle is the ability to automatically import data on a regular basis. I can already extract bank data with a cron script thanks to the excellent `boobank` application (a part of [weboob](http://weboob.org/)). Now if only I could import the extracted csv using the same cron job, I would be thrilled.

Kind regards,

Olivier
(note: currently my server is using php7.0 for various stuff so I'm limited to Firefly v4.6.3.1 but I'll upgrade everything if needed).

**Comment by pkoziol** [comment] 2017-09-24 10:53
After looking at [the source code](https://github.com/firefly-iii/firefly-iii/blob/4.6.3.1/app/Console/Commands/CreateImport.php) (I'm not an author) I'd suggest you to try running:
```
php artisan firefly:create-import $PATH_TO_CSV_FILE $PATH_TO_JSON_CONFIG_FILE --user=1 --type=csv --start
```
which should register import job in the database and immediately start it.

**Comment by JC5** [comment] 2017-09-24 10:58
Run `php artisan help` for help with commands

On 24 Sep 2017 12:53, "Paweł Kozioł" <notifications@github.com> wrote:

After looking at the source code
<https://github.com/firefly-iii/firefly-iii/blob/4.6.3.1/app/Console/Commands/CreateImport.php>
(I'm not an author) I'd suggest you to try running:

php artisan firefly:create-import $PATH_TO_CSV_FILE
$PATH_TO_JSON_CONFIG_FILE --user=1 --type=csv --start

which should register import job in the database and immediately start it.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/firefly-iii/firefly-iii/issues/557#issuecomment-331702091>,
or mute the thread

**Comment by Aquariu** [comment] 2017-09-24 19:36
thank you all for your kind answers,

Note that the command line doesn't specify how to choose the account for the import, but I had not noticed that this information was store in the json conf file itself (I was under the impression that this was a choice independent of the csv formating stuff).. 

So I'll perform a "by hand" import for all accounts and save a json file for each one (something I had overlooked previously) and then use those.

For reference here's the output for `php artisan help firefly:create-import`:
`Usage:
  firefly:create-import [options] [--] <file> <configuration>

Arguments:
  file                  
  configuration         

Options:
      --user[=USER]      [default: "1"]
      --type[=TYPE]      [default: "csv"]
      --start           
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --env[=ENV]       The environment the command should run under
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
`

**Comment by Aquariu** [comment] 2017-09-25 21:49
Dear all,

I managed to script all the import tasks but I'm now faced with a duplication issue.

Basically, for all my accounts, the script performs this:
- download the latest 50 transactions in a csv from the bank
- import that csv using the correct json related to this account

My plan was to run this on a weekly basis with a cron job.

What happened with importing 2 sets of csv files 5 days appart is that the latest transactions are present multiple times in database. Trying again with the latest one creates even more duplicates.

I was under the impression that firefly would automatically detect the transactions already in database and wouldn't duplicate them. I believe that's what the original poster in [this thread](https://github.com/firefly-iii/firefly-iii/issues/797) talks about. Did I miss something? I hope I didn't misunderstood anything.

Kind regards,

**Comment by JC5** [comment] 2017-09-26 03:32
It should detect duplicates. It does this by comparing the lines with one another.

Could you [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode)?

Firefly compares the exact CSV line with previous imported entries (hash comparison). If it fails, it means the lines are different somehow.

I'll do some investigating on my side but I need your help to see if the lines are actually different (different hash) or the same.

**Comment by Aquariu** [comment] 2017-09-28 21:08
OK here's some feedback;
- I started from scratch (`php artisan migrate:refresh --seed`)
- Recreated all my accounts
- Recreated 1 import json file for each account
- Launched my import script for 1 account yesterday and today. There was no movement on the account in between. I expected he second import to do nothing.


1. 

27th

Here's the CSV 1st line (below the headers, semicolon separator) (I hide the full description of the transaction for privacy)

`@cic;Not loaded;2017-09-15;2017-09-15;2017-09-15;2;"Raw description of the transaction";Not available;"Description";-63.00;Not loaded;Not loaded;Not loaded;Not loaded;Not loaded;[]
`
Which resulted in the import log:

> [2017-09-27 21:32:13] production.DEBUG: Now at row 1  
> [2017-09-27 21:32:13] production.DEBUG: Created ImportAccount.  
> [2017-09-27 21:32:13] production.DEBUG: Created ImportAccount.  
> [2017-09-27 21:32:13] production.DEBUG: Created ImportBill.  
> [2017-09-27 21:32:13] production.DEBUG: Created ImportCategory.  
> [2017-09-27 21:32:13] production.DEBUG: Created ImportBudget.  
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"_ignore","value":"@cic","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"_ignore","value":"Not loaded","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"date-transaction","value":"2017-09-15","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"_ignore","value":"2017-09-15","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"_ignore","value":"2017-09-15","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"_ignore","value":"2","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"description","value":"Raw description","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"_ignore","value":"Not available","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"_ignore","value":"Description","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"amount","value":"-63.00","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"_ignore","value":"Not loaded","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"_ignore","value":"Not loaded","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"_ignore","value":"Not loaded","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"_ignore","value":"Not loaded","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"_ignore","value":"Not loaded","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: Annotated value {"role":"_ignore","value":"[]","mapped":null} 
> [2017-09-27 21:32:13] production.DEBUG: ImportJournal complete, returning.  
> 

and then, after all the other lines are given the same treatment:

> [2017-09-27 21:32:13] production.DEBUG: Going to store object #0 with description "Raw description"  
> [2017-09-27 21:32:13] production.DEBUG: In findMappedObject() for Account  
> [2017-09-27 21:32:13] production.DEBUG: Find mapped account based on field "accountId" with value  
> [2017-09-27 21:32:13] production.DEBUG: In getMappedObject() for Account  
> [2017-09-27 21:32:13] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-27 21:32:13] production.DEBUG: Find mapped account based on field "accountIban" with value  
> [2017-09-27 21:32:13] production.DEBUG: In getMappedObject() for Account  
> [2017-09-27 21:32:13] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-27 21:32:13] production.DEBUG: Find mapped account based on field "accountNumber" with value  
> [2017-09-27 21:32:13] production.DEBUG: In getMappedObject() for Account  
> [2017-09-27 21:32:13] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-27 21:32:13] production.DEBUG: Find mapped account based on field "accountName" with value  
> [2017-09-27 21:32:13] production.DEBUG: In getMappedObject() for Account  
> [2017-09-27 21:32:13] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-27 21:32:13] production.DEBUG: Found no account on mapped data or no map present.  
> [2017-09-27 21:32:13] production.DEBUG: In findExistingObject() for Account  
> [2017-09-27 21:32:13] production.DEBUG: Found NO existing accounts.  
> [2017-09-27 21:32:13] production.DEBUG: Will try to find an asset account just in case.  
> [2017-09-27 21:32:13] production.DEBUG: In findExistingObject() for Account  
> [2017-09-27 21:32:13] production.DEBUG: Found NO existing accounts.  
> [2017-09-27 21:32:13] production.DEBUG: Fall back to default account #11 "CIC - Mulhouse"  
> [2017-09-27 21:32:13] production.DEBUG: -63 is negative, create opposing expense account.  
> [2017-09-27 21:32:13] production.DEBUG: In findMappedObject() for Account  
> [2017-09-27 21:32:13] production.DEBUG: Find mapped account based on field "accountId" with value  
> [2017-09-27 21:32:13] production.DEBUG: In getMappedObject() for Account  
> [2017-09-27 21:32:13] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-27 21:32:13] production.DEBUG: Find mapped account based on field "accountIban" with value  
> [2017-09-27 21:32:13] production.DEBUG: In getMappedObject() for Account  
> [2017-09-27 21:32:13] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-27 21:32:14] production.DEBUG: Find mapped account based on field "accountNumber" with value  
> [2017-09-27 21:32:14] production.DEBUG: In getMappedObject() for Account  
> [2017-09-27 21:32:14] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-27 21:32:14] production.DEBUG: Find mapped account based on field "accountName" with value  
> [2017-09-27 21:32:14] production.DEBUG: In getMappedObject() for Account  
> [2017-09-27 21:32:14] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-27 21:32:14] production.DEBUG: Found no account on mapped data or no map present.  
> [2017-09-27 21:32:14] production.DEBUG: In findExistingObject() for Account  
> [2017-09-27 21:32:14] production.DEBUG: Found NO existing accounts.  
> [2017-09-27 21:32:14] production.DEBUG: Will try to find an asset account just in case.  
> [2017-09-27 21:32:14] production.DEBUG: In findExistingObject() for Account  
> [2017-09-27 21:32:14] production.DEBUG: Found NO existing accounts.  
> [2017-09-27 21:32:14] production.DEBUG: Found no account of type Expense account so must create one ourselves.  
> [2017-09-27 21:32:14] production.DEBUG: Searching for account named "(no name)" (of user #1) of the following type(s) {"types":["Expense account"]} 
> [2017-09-27 21:32:14] production.DEBUG: There is no account with name "(no name)" or types ["Expense account"] 
> [2017-09-27 21:32:14] production.DEBUG: Final account creation dataset {"user_id":1,"account_type_id":4,"name":"(no name)","virtual_balance":null,"active":true,"iban":null} 
> [2017-09-27 21:32:14] production.DEBUG: Created new account #12 named "(no name)" of type Expense account.  
> [2017-09-27 21:32:14] production.DEBUG: Array does not have valid opening balance data.  
> [2017-09-27 21:32:14] production.DEBUG: Could not find a opening balance journal, return empty one.  
> [2017-09-27 21:32:14] production.DEBUG: Successfully stored new account #12: (no name)  
> [2017-09-27 21:32:14] production.DEBUG: Going to set "importHash" with value ""3d361a20308ddf4a2b1a3eb492989952bd13a0586cfc2de6b2f4a56768e1257f""  
> [2017-09-27 21:32:14] production.DEBUG: Created journal with ID #1  
> [2017-09-27 21:32:14] production.DEBUG: Created transaction with ID #1, account #11, amount -63  
> [2017-09-27 21:32:14] production.DEBUG: Created transaction with ID #2, account #12, amount 63  
> [2017-09-27 21:32:14] production.DEBUG: In findMappedObject() for Category  
> [2017-09-27 21:32:14] production.DEBUG: Find mapped category based on field "id" with value  
> [2017-09-27 21:32:14] production.DEBUG: In getMappedObject() for Category  
> [2017-09-27 21:32:14] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-27 21:32:14] production.DEBUG: Find mapped category based on field "name" with value  
> [2017-09-27 21:32:14] production.DEBUG: In getMappedObject() for Category  
> [2017-09-27 21:32:14] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-27 21:32:14] production.DEBUG: Found no category on mapped data or no map present.  
> [2017-09-27 21:32:14] production.DEBUG: In findExistingObject() for Category  
> [2017-09-27 21:32:14] production.DEBUG: Found NO existing categories.  
> [2017-09-27 21:32:14] production.DEBUG: In findMappedObject() for Budget  
> [2017-09-27 21:32:14] production.DEBUG: Find mapped budget based on field "id" with value  
> [2017-09-27 21:32:14] production.DEBUG: In getMappedObject() for Budget  
> [2017-09-27 21:32:14] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-27 21:32:14] production.DEBUG: Find mapped budget based on field "name" with value  
> [2017-09-27 21:32:14] production.DEBUG: In getMappedObject() for Budget  
> [2017-09-27 21:32:14] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-27 21:32:14] production.DEBUG: Found no budget on mapped data or no map present.  
> [2017-09-27 21:32:14] production.DEBUG: In findExistingObject() for Budget  
> [2017-09-27 21:32:14] production.DEBUG: Found NO existing budgets.  
> [2017-09-27 21:32:14] production.DEBUG: In findMappedObject() for Bill  
> [2017-09-27 21:32:14] production.DEBUG: Find mapped bill based on field "id" with value  
> [2017-09-27 21:32:14] production.DEBUG: In getMappedObject() for Bill  
> [2017-09-27 21:32:14] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-27 21:32:14] production.DEBUG: Find mapped bill based on field "name" with value  
> [2017-09-27 21:32:14] production.DEBUG: In getMappedObject() for Bill  
> [2017-09-27 21:32:14] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-27 21:32:14] production.DEBUG: Found no bill on mapped data or no map present.  
> [2017-09-27 21:32:14] production.DEBUG: In findExistingObject() for Bill  
> [2017-09-27 21:32:14] production.DEBUG: Found NO existing bills.  
> [2017-09-27 21:32:14] production.INFO: Imported new journal #1 with description "Raw Description  


the hash is displayed and I have no reason to doubt it.


Ok now same transaction from the extract generated on the 28th (today):

CSV:
`@cic;Not loaded;2017-09-15;2017-09-15;2017-09-15;2;PRLV SEPA DIRECTION GENERALE DE 1E067000068102M368005571130 681020495027346184 111 MENM368005571130102 IMPOT;Not available;SEPA DIRECTION GENERALE DE 1E067000068102M368005571130 681020495027346184 111 MENM368005571130102 IMPOT;-63.00;Not loaded;Not loaded;Not loaded;Not loaded;Not loaded;[]
`

2 parts of the log:

> [2017-09-28 20:01:26] production.DEBUG: Go for import!  
> [2017-09-28 20:01:26] production.INFO: Start with import job Ri8k5QAAvuBI  
> [2017-09-28 20:01:26] production.DEBUG: Job is configured, start with run()  
> [2017-09-28 20:01:26] production.DEBUG: Now in CsvProcessor run(). Job is now running...  
> [2017-09-28 20:01:26] production.DEBUG: Content size is 2639 bytes.  
> [2017-09-28 20:01:26] production.DEBUG: Created a CSV reader starting at offset 1  
> [2017-09-28 20:01:26] production.NOTICE: Building importable objects from CSV file.  
> [2017-09-28 20:01:26] production.DEBUG: Now at row 1  
> [2017-09-28 20:01:26] production.DEBUG: Created ImportAccount.  
> [2017-09-28 20:01:26] production.DEBUG: Created ImportAccount.  
> [2017-09-28 20:01:26] production.DEBUG: Created ImportBill.  
> [2017-09-28 20:01:26] production.DEBUG: Created ImportCategory.  
> [2017-09-28 20:01:26] production.DEBUG: Created ImportBudget.  
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"_ignore","value":"@cic","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"_ignore","value":"Not loaded","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"date-transaction","value":"2017-09-15","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"_ignore","value":"2017-09-15","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"_ignore","value":"2017-09-15","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"_ignore","value":"2","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"description","value":"Raw description","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"_ignore","value":"Not available","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"_ignore","value":"Description","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"amount","value":"-63.00","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"_ignore","value":"Not loaded","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"_ignore","value":"Not loaded","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"_ignore","value":"Not loaded","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"_ignore","value":"Not loaded","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"_ignore","value":"Not loaded","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: Annotated value {"role":"_ignore","value":"[]","mapped":null} 
> [2017-09-28 20:01:26] production.DEBUG: ImportJournal complete, returning.  
> 


and then:

> [2017-09-28 20:01:26] production.DEBUG: Going to store object #0 with description "Raw description"  
> [2017-09-28 20:01:26] production.DEBUG: In findMappedObject() for Account  
> [2017-09-28 20:01:26] production.DEBUG: Find mapped account based on field "accountId" with value  
> [2017-09-28 20:01:26] production.DEBUG: In getMappedObject() for Account  
> [2017-09-28 20:01:26] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-28 20:01:26] production.DEBUG: Find mapped account based on field "accountIban" with value  
> [2017-09-28 20:01:26] production.DEBUG: In getMappedObject() for Account  
> [2017-09-28 20:01:26] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-28 20:01:26] production.DEBUG: Find mapped account based on field "accountNumber" with value  
> [2017-09-28 20:01:26] production.DEBUG: In getMappedObject() for Account  
> [2017-09-28 20:01:26] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-28 20:01:26] production.DEBUG: Find mapped account based on field "accountName" with value  
> [2017-09-28 20:01:26] production.DEBUG: In getMappedObject() for Account  
> [2017-09-28 20:01:26] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-28 20:01:26] production.DEBUG: Found no account on mapped data or no map present.  
> [2017-09-28 20:01:26] production.DEBUG: In findExistingObject() for Account  
> [2017-09-28 20:01:26] production.DEBUG: Found NO existing accounts.  
> [2017-09-28 20:01:26] production.DEBUG: Will try to find an asset account just in case.  
> [2017-09-28 20:01:26] production.DEBUG: In findExistingObject() for Account  
> [2017-09-28 20:01:26] production.DEBUG: Found NO existing accounts.  
> [2017-09-28 20:01:26] production.DEBUG: Fall back to default account #11 "CIC - Mulhouse"  
> [2017-09-28 20:01:26] production.DEBUG: -63 is negative, create opposing expense account.  
> [2017-09-28 20:01:26] production.DEBUG: In findMappedObject() for Account  
> [2017-09-28 20:01:26] production.DEBUG: Find mapped account based on field "accountId" with value  
> [2017-09-28 20:01:26] production.DEBUG: In getMappedObject() for Account  
> [2017-09-28 20:01:26] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-28 20:01:26] production.DEBUG: Find mapped account based on field "accountIban" with value  
> [2017-09-28 20:01:26] production.DEBUG: In getMappedObject() for Account  
> [2017-09-28 20:01:26] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-28 20:01:26] production.DEBUG: Find mapped account based on field "accountNumber" with value  
> [2017-09-28 20:01:26] production.DEBUG: In getMappedObject() for Account  
> [2017-09-28 20:01:26] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-28 20:01:26] production.DEBUG: Find mapped account based on field "accountName" with value  
> [2017-09-28 20:01:26] production.DEBUG: In getMappedObject() for Account  
> [2017-09-28 20:01:26] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-28 20:01:26] production.DEBUG: Found no account on mapped data or no map present.  
> [2017-09-28 20:01:26] production.DEBUG: In findExistingObject() for Account  
> [2017-09-28 20:01:26] production.DEBUG: Found NO existing accounts.  
> [2017-09-28 20:01:26] production.DEBUG: Will try to find an asset account just in case.  
> [2017-09-28 20:01:26] production.DEBUG: In findExistingObject() for Account  
> [2017-09-28 20:01:26] production.DEBUG: Found NO existing accounts.  
> [2017-09-28 20:01:26] production.DEBUG: Found no account of type Expense account so must create one ourselves.  
> [2017-09-28 20:01:26] production.DEBUG: Searching for account named "(no name)" (of user #1) of the following type(s) {"types":["Expense account"]} 
> [2017-09-28 20:01:26] production.DEBUG: Found #12 ((no name)) with type id 4  
> [2017-09-28 20:01:26] production.WARNING: There already is an account named "(no name)" of type "Expense account".  
> [2017-09-28 20:01:26] production.DEBUG: Array does not have valid opening balance data.  
> [2017-09-28 20:01:26] production.DEBUG: Could not find a opening balance journal, return empty one.  
> [2017-09-28 20:01:26] production.DEBUG: Successfully stored new account #12: (no name)  
> [2017-09-28 20:01:26] production.DEBUG: Going to set "importHash" with value ""3d361a20308ddf4a2b1a3eb492989952bd13a0586cfc2de6b2f4a56768e1257f""  
> [2017-09-28 20:01:26] production.DEBUG: Created journal with ID #588  
> [2017-09-28 20:01:26] production.DEBUG: Created transaction with ID #1175, account #11, amount -63  
> [2017-09-28 20:01:26] production.DEBUG: Created transaction with ID #1176, account #12, amount 63  
> [2017-09-28 20:01:26] production.DEBUG: In findMappedObject() for Category  
> [2017-09-28 20:01:26] production.DEBUG: Find mapped category based on field "id" with value  
> [2017-09-28 20:01:26] production.DEBUG: In getMappedObject() for Category  
> [2017-09-28 20:01:26] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-28 20:01:26] production.DEBUG: Find mapped category based on field "name" with value  
> [2017-09-28 20:01:26] production.DEBUG: In getMappedObject() for Category  
> [2017-09-28 20:01:26] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-28 20:01:26] production.DEBUG: Found no category on mapped data or no map present.  
> [2017-09-28 20:01:26] production.DEBUG: In findExistingObject() for Category  
> [2017-09-28 20:01:26] production.DEBUG: Found NO existing categories.  
> [2017-09-28 20:01:26] production.DEBUG: In findMappedObject() for Budget  
> [2017-09-28 20:01:26] production.DEBUG: Find mapped budget based on field "id" with value  
> [2017-09-28 20:01:26] production.DEBUG: In getMappedObject() for Budget  
> [2017-09-28 20:01:26] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-28 20:01:26] production.DEBUG: Find mapped budget based on field "name" with value  
> [2017-09-28 20:01:26] production.DEBUG: In getMappedObject() for Budget  
> [2017-09-28 20:01:26] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-28 20:01:26] production.DEBUG: Found no budget on mapped data or no map present.  
> [2017-09-28 20:01:26] production.DEBUG: In findExistingObject() for Budget  
> [2017-09-28 20:01:26] production.DEBUG: Found NO existing budgets.  
> [2017-09-28 20:01:26] production.DEBUG: In findMappedObject() for Bill  
> [2017-09-28 20:01:26] production.DEBUG: Find mapped bill based on field "id" with value  
> [2017-09-28 20:01:26] production.DEBUG: In getMappedObject() for Bill  
> [2017-09-28 20:01:26] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-28 20:01:26] production.DEBUG: Find mapped bill based on field "name" with value  
> [2017-09-28 20:01:26] production.DEBUG: In getMappedObject() for Bill  
> [2017-09-28 20:01:26] production.DEBUG: Array is empty, nothing will come of this.  
> [2017-09-28 20:01:26] production.DEBUG: Found no bill on mapped data or no map present.  
> [2017-09-28 20:01:26] production.DEBUG: In findExistingObject() for Bill  
> [2017-09-28 20:01:26] production.DEBUG: Found NO existing bills.  
> [2017-09-28 20:01:26] production.INFO: Imported new journal #588 with description "Raw Description" and amount EUR -63.  


As you can see the hashes look the same. 

I stripped the logs from the date to check for any difference and the only relevant thing I found is that for the 1st import, the Expanse account is created since it didn't exist beforehand (1st ever transaction created in this database).

All I can see here is that the hash is the same but that doesn't stop the second import from completing successfully.

Kind regards,

Olivier

**Comment by Aquariu** [comment] 2017-09-29 15:13
DId it again today with the same csv file as yesterday, and it also imported the transaction into the database with the same hash
`[2017-09-29 15:12:09] production.DEBUG: Going to set "importHash" with value ""3d361a20308ddf4a2b1a3eb492989952bd13a0586cfc2de6b2f4a56768e1257f""`

**Comment by JC5** [comment] 2017-09-29 15:33
Thanks for this info, I appreciate your efforts!

I believe this issue is fixed in the next release. You'll have to upgrade to PHP7.1 though, but I've tested it and it should work.

**Comment by pkoziol** [comment] 2017-09-29 16:58
@Aquariu: quick Github tip: user three backticks (` ``` `) to create code block - it prevents auto-linking other issues and mentioning users.

For example:
````
```
[2017-09-28 20:01:26] production.DEBUG: Found NO existing bills.
[2017-09-28 20:01:26] production.INFO: Imported new journal #588 with description "Raw Description" and amount EUR -63.
```
````

produces:

```
[2017-09-28 20:01:26] production.DEBUG: Found NO existing bills.
[2017-09-28 20:01:26] production.INFO: Imported new journal #588 with description "Raw Description" and amount EUR -63.
```

Or use [GitHub Gist](https://gist.github.com/) ;)

**Closed** 2017-10-09 18:58 UTC
Labels: question, waiting-for-user
