### ISSUE TITLE
Autocomplete dropdown list does not decode special characters properly

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#4011] opened 2020-10-29 11:49 UTC
**Bug description**
I am running Firefly III version 5.4.5, and my problem is:
When no filter is set, there is an encoding issue:
![image](https://user-images.githubusercontent.com/34862846/97564289-a536c500-19e4-11eb-87eb-2f77e4775359.png)
When you start searching for a term, the decoding issue no longer exists:
![image](https://user-images.githubusercontent.com/34862846/97564299-a8ca4c00-19e4-11eb-9a0f-bd861c3af6f7.png)

I suppose it's a side-effect of fixing #3990

**Comment by sephrat** [comment] 2020-10-29 11:50
I overlooked #4005 while submitting this issue. Seems not to be duplicate though, the issue still happens on demo site.

**Comment by JC5** [comment] 2020-10-29 12:17
Same root cause, I'll pick it up

**Comment by JC5** [comment] 2020-10-29 13:42
A fix is up on the demo site, let me know :+1:

**Comment by sephrat** [comment] 2020-10-29 16:09
Description is good, but account list isn't:
![image](https://user-images.githubusercontent.com/34862846/97600519-6e26da80-1a09-11eb-8805-ad2f1ef1036e.png)

**Comment by JC5** [comment] 2020-10-29 16:21
Should be fixed :+1:

**Comment by sephrat** [comment] 2020-10-29 17:34
Demo site seems to be late on updating, but I tested it locally and couldn't reproduce it anymore. Thanks!

**Comment by JC5** [comment] 2020-10-29 17:35
:+1:

**Closed** 2020-11-07 16:40 UTC
Labels: bug, fixed
