### ISSUE TITLE
Bunq import no longer seems to be working

### ISSUE THREAD

**Issue by paul999** [firefly-iii/firefly-iii#1857] opened 2018-11-07 13:57 UTC
**Bug description**
I am running Firefly III version DEVELOP branch

The bunq import is no longer working, no idea since when, I imported it last week and back then it worked. I know bunq made a pretty bug update this week, might be related to that?

**Steps to reproduce**
Import bunq items

**Expected behavior**
Imported items

**Extra info**
Stack trace:
Not sure if stack trace actually helps, as a class seems to be missing?
```
[2018-11-07 13:52:28] local.ERROR: Class 'bunq\exception\BunqException' not found {"userId":1,"email":"paul@sohier.me","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0
): Class 'bunq\\exception\\BunqException' not found at /var/www/sohier/firefly-iii/vendor/bunq/sdk_php/src/Model/Generated/Endpoint/MonetaryAccount.php:179)
[stacktrace]
#0 /var/www/sohier/firefly-iii/app/Support/Import/Routine/Bunq/StageNewHandler.php(104): bunq\\Model\\Generated\\Endpoint\\MonetaryAccount->getReferencedObject()
#1 /var/www/sohier/firefly-iii/app/Support/Import/Routine/Bunq/StageNewHandler.php(66): FireflyIII\\Support\\Import\\Routine\\Bunq\\StageNewHandler->listAccounts()
#2 /var/www/sohier/firefly-iii/app/Import/Routine/BunqRoutine.php(65): FireflyIII\\Support\\Import\\Routine\\Bunq\\StageNewHandler->run()
#3 /var/www/sohier/firefly-iii/app/Http/Controllers/Import/JobStatusController.php(171): FireflyIII\\Import\\Routine\\BunqRoutine->run()
#4 [internal function]: FireflyIII\\Http\\Controllers\\Import\\JobStatusController->start(Object(FireflyIII\\Models\\ImportJob))
#5 /var/www/sohier/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#6 /var/www/sohier/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('start', Array)
#7 /var/www/sohier/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(FireflyIII\\Http\
\Controllers\\Import\\JobStatusController), 'start')
``` (If needed I can give the whole log)

**Comment by JC5** [comment] 2018-11-07 16:37
I see I've forgotten to import a class, but the cause of the bug is still unknown. Thanks for letting me know! I'll keep you updated.

**Comment by filoor** [comment] 2018-11-08 06:51
Having the same issue

**Comment by colinerd** [comment] 2018-11-09 14:40
I have the same issue on 4.7.8 - do not believe that is a dev-version?

**Comment by JC5** [comment] 2018-11-09 16:31
Sorry, looking more closely, it seems to be a bug in the bunq code. @OGKevin, could you take a look at this real quick? I am browsing the bunq code but it seems to be present.

@paul999 could you share the content of the /debug page? It might be that I shipped a master version with this particular issue in it. If that is the case, the following command could fix it. Use at your own risk!

```
composer update --no-dev --no-scripts
```

**Comment by OGKevin** [comment] 2018-11-09 16:55
@paul999 @filoor @colinerd do you all happen to have one of those new savings accounts? 🙃 If so, that explains why this line is being reached in the first place. 

Why it can't find the class is another mystery.

**Comment by OGKevin** [comment] 2018-11-09 16:56
Ah found it, you guys are probably running linux. Which uses a case sensitive file system. 

https://github.com/bunq/sdk_php/blob/982bd08d43293c2766c7fcc094cd55b4e6b06687/src/Exception/BunqException.php#L2

https://github.com/bunq/sdk_php/blob/982bd08d43293c2766c7fcc094cd55b4e6b06687/src/Model/Generated/Endpoint/MonetaryAccount.php#L4

**Comment by OGKevin** [comment] 2018-11-09 16:57
So it's a bug ad bunq's side...  🙄

**Comment by OGKevin** [comment] 2018-11-09 17:07
Reference: https://together.bunq.com/d/5398-savings-account-has-been-added-to-the-pub-api

**Comment by paul999** [comment] 2018-11-09 17:10
Yes, running Linux and added a new savings account. Will add the rest of the info once I am home as I can't login to my server from here.

**Comment by OGKevin** [comment] 2018-11-09 17:11
> Will add the rest of the info once I am home as I can't login to my server from here.

No need, problem has already been identified :).

**Comment by colinerd** [comment] 2018-11-09 17:13
Yes, running Linux here as well and I do have a savings accounts with Bunq. 
Thanks for finding the issue so quickly already, let me know if you still need more info for the resolution.

**Comment by OGKevin** [comment] 2018-11-20 19:13
see my latest comment: https://together.bunq.com/d/5398-savings-account-has-been-added-to-the-pub-api/29

@JC5 I want to apologize for pushing you to use the official SDK. 11 days is really not acceptable. Unfortunately (fortunate for me though 😝) I don't work there anymore so don't have full access as I did. I only help with bug fixes that don't require regeneration of the code. In this particular case, code regeneration is needed. However, it can be fixed without regeneration but then it will be manual labor.

If bunq cant, literally just regenerate the SDK's, ill just fork the repo and do the manual labor.

**Comment by JC5** [comment] 2018-11-21 04:41
I saw that, it's a shame you left! But if you have other cool endeavors I won't stop you of course :wink:.

At the end of the month, I plan to push a new release. I hope I can include new bunq code. If not, I'll disable it and push 4.7.9.1 once it's back up.

**Comment by OGKevin** [comment] 2018-11-21 19:11
Alright, @JC5 please pull the latest version and it should be fixed. Double check if the attributes that you are accessing are also in the new MA class: https://github.com/bunq/sdk_php/blob/e9511e1c158a2c8d768d167bc05a66d7d88ea5d5/src/Model/Generated/Endpoint/MonetaryAccountSavings.php if so that no further code modifications are needed on your side, all you got to do is update.

**Comment by JC5** [comment] 2018-11-22 06:12
Very cool, I'll work on it this weekend :+1:

**Comment by JC5** [comment] 2018-11-23 07:02
![bunq-new](https://user-images.githubusercontent.com/5889984/48931338-0cdd5f00-eef6-11e8-9107-b47802f5e6b7.png)

**Comment by OGKevin** [comment] 2018-11-23 10:07
Nice, can you add the saving goal "overview" also on the account level? when you view the details of that saving account.

**Comment by colinerd** [comment] 2018-11-23 14:40
Great to see this fixed 👍 
When can we expect a new master release that contains this fix?

**Comment by JC5** [comment] 2018-11-24 06:13
@OGKevin, I'll see what I can come up with.
@colinerd End of the month.

**Comment by paul999** [comment] 2018-11-24 11:06
Just tested, and works perfect again 👍

**Comment by filoor** [comment] 2018-12-04 15:07
@JC5 ANy upodate about the update :D

**Comment by filoor** [comment] 2018-12-04 20:04
@JC5 thanks for your reply.

Is there a workaround if I want to import data from bunq?

**Comment by JC5** [comment] 2018-12-05 04:32
You’ll have to import by hand for the time being.

**Comment by JC5** [comment] 2018-12-05 04:32
Aka write the transactions yourself ;)

**Closed** 2018-12-23 16:15 UTC
Labels: bug, fixed
