### ISSUE TITLE
income balance is negative

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#2402] opened 2019-08-11 19:43 UTC
Hello :-)

Since 4.8.0, my income is negative.

![image](https://user-images.githubusercontent.com/1318140/62838781-f09a7180-bc80-11e9-8066-f10ab67b3738.png)

I already tried to flush.
I tried to delete and recreate the transaction too.

It's the same if I go back in time and check other period.

**Comment by jlauwers** [comment] 2019-08-11 19:48
Should have tested the develop branch before posting.
It's working with the latest docker:develop

**Comment by jlauwers** [comment] 2019-08-11 19:51
I should go sleep...
It's seems to be fixed but not everywhere (not in the screenshot)
I will try to post more details tomorrow.

**Comment by JC5** [comment] 2019-08-12 14:44
It's a bug, thanks for reporting!

**Comment by agilob** [comment] 2019-08-12 15:48
Duplicate of https://github.com/firefly-iii/firefly-iii/issues/2397

**Comment by JC5** [comment] 2019-08-12 15:55
I think this is a different issue, it's something in the default report.

**Comment by JC5** [comment] 2019-08-13 16:50
Fixed in the next release.

**Closed** 2019-08-17 10:38 UTC
Labels: bug, fixed
