### ISSUE TITLE
2FA - Class 'BaconQrCode\Renderer\Image\Png' not found

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1716] opened 2018-09-23 17:12 UTC
**Bug description**
I am running Firefly III version 4.7.6.2@develop branch

(please give a clear and concise description of what the bug is)

**Steps to reproduce**
What do you need to do to trigger this bug?

1. Navigate to: /profile/2fa/code
![image](https://user-images.githubusercontent.com/550499/45930727-5815d880-bf6c-11e8-857c-3d333c8ebc20.png)

**Extra info**
2018-09-23T17:02:12.324772+00:00 app[web.1]: [2018-09-23 17:02:12] heroku.ERROR: Class 'BaconQrCode\Renderer\Image\Png' not found {"userId":1,"email":"email@here.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'BaconQrCode\\Renderer\\Image\\Png' not found at /app/vendor/pragmarx/google2fa/src/Support/QRCode.php:54)
2018-09-23T17:02:12.324897+00:00 app[web.1]: [stacktrace]
2018-09-23T17:02:12.325267+00:00 app[web.1]: #0 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): PragmaRX\\Google2FA\\Google2FA->getQRCodeInline('domain.hero...', 'email@here.co...', '2FASECRETCODE...', 200)
2018-09-23T17:02:12.325551+00:00 app[web.1]: #1 /app/app/Http/Controllers/ProfileController.php(118): Illuminate\\Support\\Facades\\Facade::__callStatic('getQRCodeInline', Array)
2018-09-23T17:02:12.325771+00:00 app[web.1]: #2 [internal function]: FireflyIII\\Http\\Controllers\\ProfileController->code()

2018-09-23T17:02:12.326023+00:00 app[web.1]: #3 /app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
2018-09-23T17:02:12.326321+00:00 app[web.1]: #4 /app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('code', Array)
2018-09-23T17:02:12.326724+00:00 app[web.1]: #5 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(FireflyIII\\Http\\Controllers\\ProfileController), 'code')
2018-09-23T17:02:12.326983+00:00 app[web.1]: #6 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
2018-09-23T17:02:12.327234+00:00 app[web.1]: #7 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(679): Illuminate\\Routing\\Route->run()
2018-09-23T17:02:12.327599+00:00 app[web.1]: #8 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.327902+00:00 app[web.1]: #9 /app/app/Http/Middleware/IsSandStormUser.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.328253+00:00 app[web.1]: #10 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\IsSandStormUser->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.328588+00:00 app[web.1]: #11 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.328887+00:00 app[web.1]: #12 /app/app/Http/Middleware/IsDemoUser.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.329227+00:00 app[web.1]: #13 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\IsDemoUser->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.329594+00:00 app[web.1]: #14 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.329906+00:00 app[web.1]: #15 /app/app/Http/Controllers/ProfileController.php(71): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.330299+00:00 app[web.1]: #16 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(133): FireflyIII\\Http\\Controllers\\ProfileController->FireflyIII\\Http\\Controllers\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.330633+00:00 app[web.1]: #17 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.330952+00:00 app[web.1]: #18 /app/app/Http/Controllers/Controller.php(88): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.331336+00:00 app[web.1]: #19 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(133): FireflyIII\\Http\\Controllers\\Controller->FireflyIII\\Http\\Controllers\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.331696+00:00 app[web.1]: #20 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.332001+00:00 app[web.1]: #21 /app/app/Http/Middleware/Binder.php(78): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.332337+00:00 app[web.1]: #22 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\Binder->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.332678+00:00 app[web.1]: #23 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.332967+00:00 app[web.1]: #24 /app/app/Http/Middleware/Range.php(60): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.333359+00:00 app[web.1]: #25 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\Range->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.333700+00:00 app[web.1]: #26 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.334012+00:00 app[web.1]: #27 /app/app/Http/Middleware/AuthenticateTwoFactor.php(86): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.334365+00:00 app[web.1]: #28 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\AuthenticateTwoFactor->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.334741+00:00 app[web.1]: #29 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.335061+00:00 app[web.1]: #30 /app/app/Http/Middleware/Authenticate.php(73): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.335402+00:00 app[web.1]: #31 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.335877+00:00 app[web.1]: #32 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.336372+00:00 app[web.1]: #33 /app/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.336869+00:00 app[web.1]: #34 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.337337+00:00 app[web.1]: #35 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.337898+00:00 app[web.1]: #36 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.338467+00:00 app[web.1]: #37 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.338767+00:00 app[web.1]: #38 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.339135+00:00 app[web.1]: #39 /app/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.339570+00:00 app[web.1]: #40 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.339907+00:00 app[web.1]: #41 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.340343+00:00 app[web.1]: #42 /app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.340830+00:00 app[web.1]: #43 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.341305+00:00 app[web.1]: #44 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.341822+00:00 app[web.1]: #45 /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.342199+00:00 app[web.1]: #46 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.342534+00:00 app[web.1]: #47 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.342905+00:00 app[web.1]: #48 /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.343293+00:00 app[web.1]: #49 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.343797+00:00 app[web.1]: #50 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.344213+00:00 app[web.1]: #51 /app/app/Http/Middleware/Sandstorm.php(54): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.344683+00:00 app[web.1]: #52 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\Sandstorm->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.345157+00:00 app[web.1]: #53 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.345636+00:00 app[web.1]: #54 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.346041+00:00 app[web.1]: #55 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
2018-09-23T17:02:12.346886+00:00 app[web.1]: #56 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.347037+00:00 app[web.1]: #57 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
2018-09-23T17:02:12.347476+00:00 app[web.1]: #58 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(611): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.347933+00:00 app[web.1]: #59 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.348286+00:00 app[web.1]: #60 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.348598+00:00 app[web.1]: #61 /app/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.348930+00:00 app[web.1]: #62 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.349346+00:00 app[web.1]: #63 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.349865+00:00 app[web.1]: #64 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.350387+00:00 app[web.1]: #65 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.350824+00:00 app[web.1]: #66 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.351211+00:00 app[web.1]: #67 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.351632+00:00 app[web.1]: #68 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.352016+00:00 app[web.1]: #69 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.352489+00:00 app[web.1]: #70 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.353156+00:00 app[web.1]: #71 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.353630+00:00 app[web.1]: #72 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.354177+00:00 app[web.1]: #73 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.354700+00:00 app[web.1]: #74 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.355100+00:00 app[web.1]: #75 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.355404+00:00 app[web.1]: #76 /app/app/Http/Middleware/SecureHeaders.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.355900+00:00 app[web.1]: #77 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2018-09-23T17:02:12.356334+00:00 app[web.1]: #78 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.356823+00:00 app[web.1]: #79 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.357231+00:00 app[web.1]: #80 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
2018-09-23T17:02:12.357716+00:00 app[web.1]: #81 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.357997+00:00 app[web.1]: #82 /app/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
2018-09-23T17:02:12.358122+00:00 app[web.1]: #83 {main}
2018-09-23T17:02:12.358263+00:00 app[web.1]: "}

**Comment by JC5** [comment] 2018-09-23 17:50
I’ll check it out. Please note that the develop branch could be broken often :wink:

**Comment by JC5** [comment] 2018-09-26 18:09
Could you run `composer update` and try again?

**Comment by JC5** [comment] 2018-09-26 18:47
Ehm, never mind. Perhaps I should do that 😅 This will be fixed in the next release.

**Comment by JC5** [comment] 2018-09-27 12:45
Closed pending the next release this weekend.

**Closed by JC5** 2018-09-27 12:45 UTC
Labels: bug, fixed

**Comment by kosciCZ** [comment] 2019-03-12 12:14
Hi, 
I encountered this issue again in 4.7.16 (docker hosted) and after looking around a bit I found out you seemed to reintroduce the cause for the bug in commit https://github.com/firefly-iii/firefly-iii/commit/48219c9af35797a3fb5206b48fa9dfd8c29cd32b by upgrading to 2.* version of the bacon/bacon-qr-code. Perhaps there's another way to fix it than downgrading it?

**Comment by vitobotta** [comment] 2019-03-15 21:40
Just restored an existing database from a manual installation into a docker installation, at first I couldn't login so I reset the password, and now when I try to enable 2FA again I get the same error.

**Comment by kosciCZ** [comment] 2019-03-16 22:15
Looks like this is getting fixed #2173

**Comment by JC5** [comment] 2019-03-17 06:11
We're not running out of issue numbers, please continue the conversation in the current issue and refrain from rehashing old ones.
