### ISSUE TITLE
Categories overview graph not correct

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#602] opened 2017-02-26 11:19 UTC
For some categories in categories/show/N the overview graph don't show correct data:
![obraz](https://cloud.githubusercontent.com/assets/4746858/23339187/e5c12884-fc1c-11e6-9b6d-e1281683dafe.png)
What is specific about this category is that all records from January are from split transactions. Other categories that have normal transactions are displayed correctly:
![obraz](https://cloud.githubusercontent.com/assets/4746858/23339207/bb9f3518-fc1d-11e6-8ddc-a0f7ff5358e8.png)

**Comment by JC5** [comment] 2017-02-26 11:55
Mmmm. The code seems to use the journal collector, an internal thingie that _should_ account for split transactions. But I have to look into it and get some test use cases.

Thanks for the heads-up, I'll post when I have found something!

**Comment by JC5** [comment] 2017-02-26 12:55
I can't reproduce this. I've created a new category and both split and unsplit transactions in January or February show up just fine in both charts.

![screen shot 2017-02-26 at 13 54 07](https://cloud.githubusercontent.com/assets/5889984/23339855/27d4a8c8-fc2b-11e6-826d-ae26a44231fd.png)
![screen shot 2017-02-26 at 13 54 13](https://cloud.githubusercontent.com/assets/5889984/23339853/27d42b3c-fc2b-11e6-9c0e-a47cc7f05923.png)
![screen shot 2017-02-26 at 13 54 28](https://cloud.githubusercontent.com/assets/5889984/23339854/27d47614-fc2b-11e6-8ed1-bd5c7b39b129.png)

**Comment by skibbipl** [comment] 2017-02-26 17:41
Well, I'll try to debug little further. Perhaps it's not related to transaction type.

**Comment by skibbipl** [comment] 2017-02-27 14:36
OK I tried to debug a little deeper, but I'm not sure what's wrong. The issue lays in getting data from chart/category/all/N. The correct category calls 4 huge queries similar to this
```
select "transaction_journals"."id" as "journal_id", "transaction_journals"."description", "transaction_journals"."date", "transaction_journals"."encrypted", "transaction_currencies"."code" as "transaction_currency_code", "transaction_types"."type" as "transaction_type_type", "transaction_journals"."bill_id", "bills"."name" as "bill_name", "bills"."name_encrypted" as "bill_name_encrypted", "transactions"."id" as "id", "transactions"."amount" as "transaction_amount", "transactions"."description" as "transaction_description", "transactions"."account_id", "transactions"."identifier", "transactions"."transaction_journal_id", "accounts"."name" as "account_name", "accounts"."encrypted" as "account_encrypted", "account_types"."type" as "account_type", "category_transaction_journal"."category_id" as "transaction_journal_category_id", "transaction_journal_categories"."encrypted" as "transaction_journal_category_encrypted", "transaction_journal_categories"."name" as "transaction_journal_category_name", "category_transaction"."category_id" as "transaction_category_id", "transaction_categories"."encrypted" as "transaction_category_encrypted", "transaction_categories"."name" as "transaction_category_name" from "transactions" left join "transaction_journals" on "transaction_journals"."id" = "transactions"."transaction_journal_id" left join "transaction_currencies" on "transaction_currencies"."id" = "transaction_journals"."transaction_currency_id" left join "transaction_types" on "transaction_types"."id" = "transaction_journals"."transaction_type_id" left join "bills" on "bills"."id" = "transaction_journals"."bill_id" left join "accounts" on "accounts"."id" = "transactions"."account_id" left join "account_types" on "accounts"."account_type_id" = "account_types"."id" left join "category_transaction_journal" on "category_transaction_journal"."transaction_journal_id" = "transaction_journals"."id" left join "categories" as "transaction_journal_categories" on "transaction_journal_categories"."id" = "category_transaction_journal"."category_id" left join "category_transaction" on "category_transaction"."transaction_id" = "transactions"."id" left join "categories" as "transaction_categories" on "transaction_categories"."id" = "category_transaction"."category_id" where "transactions"."deleted_at" is null and "transaction_journals"."deleted_at" is null and "transaction_journals"."user_id" = '1' and "transaction_journals"."date" >= '2017-01-01' and "transaction_journals"."date" <= '2017-01-31' and "transaction_types"."type" in ('Withdrawal') and ("category_transaction"."category_id" in ('5') or "category_transaction_journal"."category_id" in ('5')) and "transactions"."account_id" in ('1', '3', '5', '11', '9', '7') and "transactions"."deleted_at" is null order by "transaction_journals"."date" desc, "transaction_journals"."order" asc, "transaction_journals"."id" desc;
```
Each pair of SQL queries represent Withdrawals and Deposits, and the difference is in date range. The bad category calls only 2 queries for February. Why it ignores January?

**Comment by JC5** [comment] 2017-02-27 15:40
I know the chart ignores transfers, they're not displayed although they do account for the date range used in the chart. The only reason I can think of now why this would fail would be when the system thinks there are no transactions in January. 

Assuming you run the latest version you could find this line: https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Controllers/Chart/CategoryController.php#L69

And change it to: 
```var_dump($start);
exit;
```

Which would tell you (for both charts) which date the system thinks is the first transaction ever in the category. If it's 1900 the system thinks nothing ever happened in the category.

To make sure no bad data is cached, run `php artisan cache:clear` on the command line.

**Comment by skibbipl** [comment] 2017-02-27 18:46
Yep, I've got 1900:
```
object(Carbon\Carbon)#843 (3) {
  ["date"]=>
  string(26) "1900-01-01 00:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(3) "UTC"
}
```

**Comment by JC5** [comment] 2017-02-27 19:43
I think I found the issue. It's possible to end up with a null because my original comparison was way too complex.

You can test this by opening this file: https://github.com/firefly-iii/firefly-iii/blob/master/app/Repositories/Category/CategoryRepository.php#L110

Replace everything between line 112 and 136 (so everything between the brackets with the following code:

```
        $first = new Carbon;

        /** @var TransactionJournal $firstJournal */
        $firstJournal = $category->transactionJournals()->orderBy('date', 'ASC')->first(['transaction_journals.date']);

        // if transaction journal exists and date is before $first, then
        // new date:
        if (!is_null($firstJournal) && $firstJournal->date->lessThanOrEqualTo($first)) {
            $first = $firstJournal->date;
        }

        // check transactions:
        $firstTransaction = $category->transactions()
                                     ->leftJoin('transaction_journals', 'transaction_journals.id', '=', 'transactions.transaction_journal_id')
                                     ->orderBy('transaction_journals.date', 'ASC')->first(['transaction_journals.date']);


        // transaction exists, and date is before $first, this date becomes first.
        if (!is_null($firstTransaction) && Carbon::parse($firstTransaction->date)->lessThanOrEqualTo($first)) {
            $first = $firstTransaction->date;
        }

        return $first;
```

If it works, I'll push an update!

**Comment by skibbipl** [comment] 2017-02-27 21:26
Confirmed - it works as expected:
![obraz](https://cloud.githubusercontent.com/assets/4746858/23380620/d266814c-fd3b-11e6-8fd0-0d3250fdfcba.png)

**Comment by JC5** [comment] 2017-02-28 06:43
Nice. I'll push the update tonight and it'll be fixed in the next release. Thanks for helping me debug!

**Closed** 2017-03-06 20:07 UTC
