### ISSUE TITLE
issue after successfull upgrade from 4.7.9 to 4.7.15

### ISSUE THREAD

**Issue by GaneshKandu** [firefly-iii/firefly-iii#2144] opened 2019-03-04 07:10 UTC
**Bug description**
I am getting Error when login after upgrading from **4.7.9** to **4.7.15**

```
FireflyIII
Whoops! An error occurred.

Unfortunately, this error was not recoverable. Firefly III broke. The error is:

updateStartDate cannot handle range "eyJpdiI6IjlGVDV6RTlOVkRGdzYwUGk5eUlpbXc9PSIsInZhbHVlIjoiSHlpck5SUHZ6eUxxTDlpbmVlY1Bydz09IiwibWFjIjoiMmY1YjYyOWY3N2YwOGUwNjg5ZTRhZjMyMzcxYmRlMTEwOGEwZmRkZmM0MTc2YzY1MGVlM2E1MmY4YzhjYWY4NiJ9"

More information about this error may be available in the log files. Search for the error above and a stack trace will appear. This stack trace may help you track down what's going wrong.

If you cannot find the cause of this error or when you need some help, please open a ticket on GitHub.

```

**Steps to reproduce**
upgrade from 4.7.9 to 4.7.15 using web and login after successful upgrade

**Extra info**
System Environment

.| Version
--- | ---
PHP | 7.2.8
MySQL | 5.6.42
Server API  | Apache 2.0

[ff3-apache2handler-2019-03-04.log](https://github.com/firefly-iii/firefly-iii/files/2924667/ff3-apache2handler-2019-03-04.log)

**Comment by JC5** [comment] 2019-03-04 07:21
Empty the table `preferences` and run the following on the command line: `php artisan cache:clear`.

I'll make sure it's fixed in the next release.

**Comment by JC5** [comment] 2019-03-05 15:55
Sorry about this. I pushed a fix for this. It was caused by me testing only consecutive upgrades, and not regression testing. 

4.7.16 will be released this weekend.

**Closed** 2019-03-17 08:23 UTC
Labels: bug, fixed
