### ISSUE TITLE
Search: amount_more not working

### ISSUE THREAD

**Issue by enra64** [firefly-iii/firefly-iii#2729] opened 2019-10-12 09:32 UTC
**Bug description**
I am running Firefly III version 4.8.1.4, and my problem is that when searching for transactions with an "amount_more:10.00" filter, it doesn't get picked up. Instead, the description seems to be searched for 10.00. See also the screenshot:
![firefly](https://user-images.githubusercontent.com/7622426/66698994-4cb25e00-ece3-11e9-80e4-8800dac8efd5.png)

Please not that it also doesn't work when searching for 5.00. An additional filter of type:withdrawal gets picked up, btw.

**Steps to reproduce**

Just use the search function as described.

**Extra info**

I'm using linux, and the bug happens in Firefox and Chromium.

**Bonus points**
Sorry, I don't really have a log here. The query is `/search?search=amount_more%3A5.00`

**Comment by JC5** [comment] 2019-10-12 11:03
Same root cause as https://github.com/firefly-iii/firefly-iii/issues/2713, and will be fixed in the next release. Thanks for reporting :+1:

**Closed by JC5** 2019-10-12 11:03 UTC
