### ISSUE TITLE
Duplicate transfers

### ISSUE THREAD

**Issue by oswdr** [firefly-iii/firefly-iii#2841] opened 2019-11-18 16:49 UTC
**Bug description**
I am running Firefly III version 4.8.1.8, and my problem is:

When importing transactions from two different accounts duplicate transfers are created. It seems that this is caused by the description being empty.  Not sure if this is a bug or intended behavior.

**Steps to reproduce**
Import the following CSV's:

Rekeningnummer|Transactiedatum|Valutacode|CreditDebet|Bedrag|Tegenrekeningnummer|Tegenrekeninghouder|Valutadatum|Betaalwijze|Omschrijving|Type betaling|Machtigingsnummer|Incassant ID|Adres|Referentie|Boekdatum
---|---|-|-|-|-|-|-|-|-|-|-|-|-|-|-
GB33BUKB20201555555555|15-10-2019|EUR|D|300|DE75512108001245126199|J. Doe|15-10-2019|Overboeking|||||||15-10-2019

[CSV 1.txt](https://github.com/firefly-iii/firefly-iii/files/3859840/CSV.1.txt)

Rekeningnummer|Transactiedatum|Valutacode|CreditDebet|Bedrag|Tegenrekeningnummer|Tegenrekeninghouder|Valutadatum|Betaalwijze|Omschrijving|Type betaling|Machtigingsnummer|Incassant ID|Adres|Referentie|Boekdatum
-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-
DE75512108001245126199|15-10-2019|EUR|C|300|GB33BUKB20201555555555|John Doe|15-10-2019|Ontvangen betaling|||||||15-10-2019|

[CSV 2.txt](https://github.com/firefly-iii/firefly-iii/files/3859839/CSV.2.txt)
[import-configuration.json](https://github.com/firefly-iii/firefly-iii/files/3859691/import-configuration.json.txt)

**Extra info**
Debug information generated at 2019-11-18 17:32:29 Europe/Amsterdam for Firefly III version **4.8.1.8**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.8 |
| FF API version | 0.10.5 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2019-10-19 00:00:00 |
| Session end | 2019-11-18 00:00:00 |
| Session first | 2018-10-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 3 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Comment by JC5** [comment] 2019-11-18 16:52
That shouldn't happen of course. Could you share some debug logs with me, over email if possible? I'll try it out as well.

**Comment by JC5** [comment] 2019-11-18 16:52
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on GitHub, please [send them to me over (encrypted) email](https://firefly-iii.org/contact-information.html).

**Comment by JC5** [comment] 2019-11-18 18:07
I found the issue. Because your transactions have no description, Firefly III falls back to "(empty description)". However, the comparison is done with an empty string (""). Since "" and "(empty string)" don't match, the transactions aren't recognised.

I've pushed a fix that will go live in the next release. To try it, you'll have to install the latest alpha (will be out shortly) or wait for a beta / stable release.

**Closed** 2019-11-18 18:14 UTC
Labels: bug, fixed

**Comment by oswdr** [comment] 2019-11-18 19:14
Hi @JC5, great catch. Thanks a lot for the quick response and fix! Just updated to 4.8.2-alpha.5 and can verify that the files supplied no longer create duplicate transfers. Awesome :-). 


...However, I found another issue. 

I have two transactions, one from A to B and one from B to C. It consists of the same amount, same date, same target IBAN (B) and empty description. The only difference is the external ID and the target IBAN. The import returns an error that the transaction from B to C is a duplicate.

Rekeningnummer|Transactiedatum|Valutacode|CreditDebet|Bedrag|Tegenrekeningnummer|Tegenrekeninghouder|Valutadatum|Betaalwijze|Omschrijving|Type betaling|Machtigingsnummer|Incassant ID|Adres|Referentie|Boekdatum
-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-
DE75512108001245126199|15-10-2019|EUR|D|300|NL02ABNA0123456789|J. Doe|15-10-2019|Overboeking|||||||15-10-2019
DE75512108001245126199|15-10-2019|EUR|C|300|GB33BUKB20201555555555|John Doe|15-10-2019|Ontvangen betaling|||||||15-10-2019

[CSV.1.txt](https://github.com/firefly-iii/firefly-iii/files/3860238/CSV.1.txt)

**Comment by JC5** [comment] 2019-11-18 19:25
That could be caused by the mapping, but I’ll run it and see what the logs say. Thanks for letting me know :)

**Comment by JC5** [comment] 2019-11-18 19:41
Also fixed :+1:
