### ISSUE TITLE
Bills Issue

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#2983] opened 2020-01-09 18:06 UTC
BUG: The bills index is not working properly in 5.0.0 at least Beta 1 not sure about the last alpha version.

Reproduced in demo site using IOS 12.x.x Safari Browser.

Steps are technically already there if the demo saves everything.
Set range 2019-01-01 to 2019-01-31
I created a bill "My Rent" dated 2019-01-01 repeat monthly 
Created simple rule for it
Created expense account "My Landlord"
Created Transaction "My Rent" 2019-01-01
Still in range 2019-01-01 ti 2019-01-31
Visit bills page says "not yet" for payment this period
Click on "My Rent" bill link and it clearly states the transaction linked to the bill.

Also look at the weird results displayed for next payment due. even when current date is selected some show as November. This is reproducible on local install with data from only January 2019

Unable to verify other bug since I can't see all the fields in the bills section on my phone
4.8.2 any bill paid on a date after the scheduled bill date gets it's next payment date changed to the month following the expected next month
ex: if I create a bill for a specific date ex: "rent" January 1, 2019 and repeat monthly and pay it after the date in this case Jan 1 a holiday so pay rent Jan 2 then next payment due changes from February to March while still on the January 2019 date range

**Comment by JC5** [comment] 2020-01-09 18:27
I pushed a fix that may or may not involve me leaving debug code in the code somewhere 😊

**Comment by GaryQ** [comment] 2020-01-09 18:39
Bug regarding display of Bills index is fixed.

I then changed the My Rent payment to Jan 2nd and it says next payment Due March
You can see for yourself on the demo site

**Comment by JC5** [comment] 2020-01-09 19:05
I recreated your bill (the demo has just reset) and I believe the issue is fixed now.

**Closed** 2020-01-18 05:10 UTC
Labels: bug, fixed
