### ISSUE TITLE
Dashboard Net worth doesn't sum up all assets account

### ISSUE THREAD

**Issue by jinformatique** [firefly-iii/firefly-iii#1088] opened 2018-01-02 11:15 UTC
I am running Firefly III version 4.6.12

I just started fresh from a new install to record all my assets account for 2018 and put an initial balance. It seems the total of all my assets account is not taking into account. The net worth is based only on one asset account. Same goes for the details on the account graph. You can check on the screenshots. Maybe is it part of the #1040?

![firefly4612home](https://user-images.githubusercontent.com/487038/34482101-3ba640b2-efb6-11e7-8882-ad1160c38ab9.png)
![firefly4612assets](https://user-images.githubusercontent.com/487038/34482102-3bc1d610-efb6-11e7-992a-34abdcc4cd53.png)

**Comment by JC5** [comment] 2018-01-02 12:17
I see what's happening. I can't reproduce it.

I created three normal asset accounts with everything on default.

- No balance: empty
- 1 dec: balance of 1000 on 1 dec 2017 (opening balance)
- 1 jan: balance of 1000 on 1 jan 2018 (opening balance)

All accounts are correct, net worth is 2000.

Did you do something with foreign / not-foreign balances?

**Comment by jinformatique** [comment] 2018-01-03 14:41
So, I just connected today and the NET WORTH is the amount of all the asset accounts. Good.
I don't have any  foreign / not-foreign balances, what is it?

But still in the graphic below, I have 0 for all asset accounts:
![image](https://user-images.githubusercontent.com/487038/34524594-6327a7de-f09c-11e7-9d90-499bf66bfcc0.png)

**Comment by JC5** [comment] 2018-01-03 18:10
Could you run the following query for me? Share the info over email.

Instead of the number XXX, enter one of the account numbers of an asset account that has a balance, but shows 0 in the chart.

```sql
select

	`transaction_journals`.`date`,
	`transactions`.`transaction_currency_id`,
	SUM(transactions.amount) AS modified,
	`transactions`.`foreign_currency_id`,
	SUM(transactions.foreign_amount) AS modified_foreign
from
	`transactions`
	left join `transaction_journals` on `transactions`.`transaction_journal_id` = `transaction_journals`.`id`
where
	`transactions`.`account_id` = 'xxxxxxx' and 
	`transactions`.`account_id` is not null and 
	`transaction_journals`.`date` >= '2018-01-01' and 
	`transaction_journals`.`date` <= '2018-02-01' and 
	`transaction_journals`.`deleted_at` is null and 
	`transactions`.`deleted_at` is null 

group by
	`transaction_journals`.`date`,
	`transactions`.`transaction_currency_id`,
	`transactions`.`foreign_currency_id`
order by `transaction_journals`.`date` asc

```

**Comment by Nik-vr** [comment] 2018-01-11 09:27
I use SQLite database. How do I make this query?

**Comment by JC5** [comment] 2018-01-11 11:12
Use a program like [DB browser for sqlite](http://sqlitebrowser.org/). This should work in that program. I believe there is an option to run a query:

```sql
select

	transaction_journals.date,
	transactions.transaction_currency_id,
	SUM(transactions.amount) AS modified,
	transactions.foreign_currency_id,
	SUM(transactions.foreign_amount) AS modified_foreign
from
	transactions
	left join transaction_journals on transactions.transaction_journal_id = transaction_journals.id
where
	transactions.account_id = 'xxxxxxx' and 
	transactions.account_id is not null and 
	transaction_journals.date >= '2018-01-01' and 
	transaction_journals.date <= '2018-02-01' and 
	transaction_journals.deleted_at is null and 
	transactions.deleted_at is null 

group by	
	transaction_journals.date,
	transactions.transaction_currency_id,
	transactions.foreign_currency_id
order by transaction_journals.date asc
```

**Comment by Nik-vr** [comment] 2018-01-11 13:07
I run the specified query. It returns part of the transactions, not all.

![assets](https://user-images.githubusercontent.com/520760/34826874-53aea08e-f6e9-11e7-8b5c-837c73ba68b5.jpg)

![assets2](https://user-images.githubusercontent.com/520760/34826876-53d8a438-f6e9-11e7-995b-239e707d51f9.jpg)

**Comment by JC5** [comment] 2018-01-11 17:57
That's no problem, the amounts are summed up. But good news: I think I have found the problem. It will be fixed in the next release.

**Comment by Nik-vr** [comment] 2018-01-12 03:59
OK!

**Comment by Nik-vr** [comment] 2018-01-12 06:11
I tested your fix. Now the chart works! Thank you!

**Closed** 2018-01-31 06:14 UTC
Labels: bug, fixed
