### ISSUE TITLE
Cloning Transaction -> 404 Error

### ISSUE THREAD

**Issue by mattdageek96** [firefly-iii/firefly-iii#7192] opened 2023-03-11 05:06 UTC
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I tried to clone a transaction and get a 404 error page

### Debug information

Debug information generated at 2023-03-10 00:00:00 America/Los_Angeles for Firefly III version **6.0.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.1 |
| Firefly III API | 2.0.1 |
| Build | 413, 10-03-2023 19:20:57 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/Los_Angeles |
| Browser TZ | America/Los_Angeles |
| App environment | production |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-01-01 00:00:00 |
| Session end | 2023-03-10 23:59:59 |
| Session first | 2023-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15 |

### Expected behaviour

Go to cloned transaction

### Steps to reproduce

1. Try to clone transaction
2. Gets 404 error page.

**Comment by JC5** [comment] 2023-03-11 06:13
Same root cause as https://github.com/firefly-iii/firefly-iii/issues/7186, will be fixed in the next release :+1:

**Closed by JC5** 2023-03-11 06:13 UTC
