### ISSUE TITLE
Tags are not deleted

### ISSUE THREAD

**Issue by fabricionu** [firefly-iii/firefly-iii#4916] opened 2021-07-12 13:50 UTC
**Bug description**
I am running Firefly III version 5.5.11, and my problem is:

Deleted tags still appears on the transaction after saving.

**Steps to reproduce**
Edit a transaction with a tag. Delete the tag and save.

**Extra info**
Debug information generated at 2021-07-12 10:45:49 America/Sao_Paulo for Firefly III version **5.5.11**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.11 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.6 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 2d2f6aa0-b180-441d-ab60-e211097ae606 |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| System TZ | America/Sao_Paulo |
| Browser TZ | America/Sao_Paulo |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | pt_BR |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-07-01 00:00:00 |
| Session end | 2021-07-31 23:59:59 |
| Session first | 2021-04-30 00:00:00 |
| User ID | 1 |
| User language | pt_BR |
| User locale | pt_BR |
| Attempt at "pt_BR.utf8" | 'pt_BR.utf8' |
| Attempt at "pt_BR.UTF-8" | 'pt_BR.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 |

**Comment by JC5** [comment] 2021-07-12 14:01
Thanks, I'll check it out!

**Comment by JC5** [comment] 2021-07-17 01:20
Not a bug or already fixed in 5.5.12 and higher.

**Closed by JC5** 2021-07-17 01:20 UTC
Labels: question
