### ISSUE TITLE
Issue importing .csv file after update 4.8.0.1

### ISSUE THREAD

**Issue by airbillion** [firefly-iii/firefly-iii#2417] opened 2019-08-13 16:38 UTC
Debug information generated at 2019-08-13 12:30:38 America/New_York for Firefly III version **4.8.0.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.0.1 |
| FF API version | 0.10.0 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.21 |
| Display errors | Off |
| Session start | 2019-08-01 00:00:00 |
| Session end | 2019-08-31 23:59:59 |
| Session first | 2018-08-10 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 2 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| Is Docker (.env) | 'unknown' |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

When I try and import a csv file I receive the following error no matter which account I choose:

Warning! You have selected an invalid account to import into.

![firefly error](https://user-images.githubusercontent.com/11315828/62959689-4f6a0300-bdc7-11e9-808b-e6b527c04bcc.jpg)

It looks like I cannot choose the right account to import into...

Is this a known issue?  Should

 I revert to an older release?

Thank you!

Please see the attached picture...

**Comment by JC5** [comment] 2019-08-13 16:47
I see the issue, and this issue has the same root cause as #2414. This will be fixed in the next release. Until then, you'll have to hold off importing data.

**Comment by airbillion** [comment] 2019-08-13 18:51
Great!  Thank you!

**Comment by adamzimnyy** [comment] 2019-08-15 13:37
@JC5 any idea when would this release be available?

**Comment by JC5** [comment] 2019-08-15 14:50
No.

**Closed** 2019-08-17 10:38 UTC
Labels: bug, fixed
