### ISSUE TITLE
Feature request: Redirection after editing a transaction

### ISSUE THREAD

**Issue by ragnarkarlsson** [firefly-iii/firefly-iii#1169] opened 2018-02-08 16:31 UTC
I am running Firefly III version 4.7.0

#### Description of my issue:

When I go to budgets and check for transactions without a budget, if I edit a transaction to set the budget I am not returned to the prior page which lists other transactions without a budget but rather the dashboard.

#### Steps to reproduce 

- Go to Budgets
- Click Expenses without budget
- Edit a transaction listed
- Update the budget
- Save transaction
- See Dashboard

#### Expected result

Instead of being returned to the Dashboard, I would prefer to be returned to the page of other transactions without a budget. 

Whilst most of my transactions have budgets set immediately through bills and rules, there are a variety each month which are missed by rules. If I import a list of transactions going to budgets > without budget > edit transaction > dashboard > repeat adds overhead and feels illogical.

**Comment by JC5** [comment] 2018-02-09 05:01
Yes, most redirects are a bit messy. I apologize for this one, it should go back to the "no-budget list" but clearly it does not. I'm looking into a better method of redirecting.

The problem at the moment is that when you delete stuff you used to get redirected back to the item you just deleted, resulting in embarrassing 404's. So I fixed that by avoiding URL's with the word "show" in it, which were usually the items you just deleted. However, Firefly III cannot remember all your visited pages going back forever so it just sent you back to the index.

I'll fix it for the next release :)

**Comment by ragnarkarlsson** [comment] 2018-02-09 12:34
I don't think it needs to remember every stage of history, but 2 pages ago? That way if you go direct to a transaction from Dashboard, it returns to Dashboard, but if you're in an account, category, budget review, it takes you to those. 

Its not a high priority by any means I suspect, nothing is fundamentally broken its just a positive UX thought :-)

**Comment by JC5** [comment] 2018-02-09 14:18
That's true, but it means that every visit must be logged somehow, even if only the last two have to be remembered.

**Comment by phosphotungstic** [comment] 2018-02-09 16:09
Hi! I'm not able to reproduce this bug? Can we get some details on how you're hosting firefly and what browser you're using?

**Comment by ragnarkarlsson** [comment] 2018-02-09 20:12
Centos 7
PHP 7.1.13
Nginx 1.13.8
MariaDB 10.1.30
Chrome 64

**Comment by JC5** [comment] 2018-02-10 07:10
I'm having a hard time reproducing this. It seems to work on the demo site as well.

Could you test this on the [demo site](https://demo.firefly-iii.org/)? Just edit some transactions and remove their budget, and add them again from the "no budget"-view. 

It seems to work fine in both Chrome and Firefox.

**Comment by ragnarkarlsson** [comment] 2018-02-10 10:52
Ok, odd, can confirm it works fine on the demo site for me as well. Damn, that means there is something hinky in my setup :-/

**Comment by JC5** [comment] 2018-02-12 06:46
Mmm. Let me know if you need some pointers. The code to track the previous page isn't particularly complex. Perhaps you've disabled referers? Although that would not explain why it works on the demo site.

I'm closing this one, feel free to open an issue if necessary!

**Closed by JC5** 2018-02-12 06:46 UTC
Labels: possible bug

**Comment by ragnarkarlsson** [comment] 2018-02-21 13:56
FYI @JC5 I figured out what was causing the issue on my setup. I was running with a specific HTTP header of Referrer-Policy: strict-origin which as a result was passing back just the base URL. Changing this to Referrer-Policy: same-origin enables the functionality correctly.

**Comment by JC5** [comment] 2018-02-22 06:59
Hey thanks for getting back to me! I will update the documentation to reflect your experience. Possibly others can be saved he efforts :+1:
