### ISSUE TITLE
File permissions are wrong /var/www/firefly-iii/storage/framework/cache/data/1e

### ISSUE THREAD

**Issue by jerheij** [firefly-iii/firefly-iii#3453] opened 2020-06-09 09:22 UTC
**Bug description**
I am running Firefly III docker tag latest, and my problem is:
There are some permissions on root in /var/www/firefly-iii. When I start up my container I get the following error (see attached screenshot):
`file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/1e/fc/1efcdd65ad8aff35c68926a79f26ded50701e334): failed to open stream: No such file or directory 
`

All files and folders owned by root in /var/www/firefly-iii:
```
root@ef062bcd7371:/var/www/firefly-iii# find ./ -user root
./storage/framework/cache/data/1e
./storage/framework/cache/data/1e/61
./storage/framework/cache/data/1e/61/1e613425200610d3170539bae6fcd5b4e03c359a
./bootstrap/cache/packages.php
./bootstrap/cache/services.php
./bootstrap/cache/config.php
```

**Steps to reproduce**
1. docker stop firefly
2. docker rm firefly
3. docker-compose up -d
4. logging in to firefly webinterface

**Extra info**
I was able to solve this issue by running the following command from within the container:
`chown -R www-data: ./storage/framework/cache/ `

But after stopping, removing and restarting the container the issue reappeared and I could see the file permissions were wrong again.

**Log file**
```
[2020-06-09 09:08:13] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"file_put_contents(\/var\/www\/firefly-iii\/storage\/framework\/cache\/data\/1e\/fc\/1efcdd65ad8aff35c68926a79f26ded50701e334): failed to open stream: No such file or directory","time":"Tue, 09 Jun 2020 09:08:13 +0000","file":"\/var\/www\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Filesystem\/Filesystem.php","line":133,"code":0,"version":"5.2.8","url":"https:\/\/budget.thuis.local\/accounts\/show\/2\/all?page=1","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko\/20100101 Firefox\/77.0","json":true}
[2020-06-09 09:08:13] local.ERROR: Exception when mailing: Address in mailbox given [] does not comply with RFC 2822, 3.6.2.
[2020-06-09 09:08:13] local.ERROR: file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/1e/fc/1efcdd65ad8aff35c68926a79f26ded50701e334): failed to open stream: No such file or directory {"userId":1,"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/1e/fc/1efcdd65ad8aff35c68926a79f26ded50701e334): failed to open stream: No such file or directory at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133)
```
![firefly_error](https://user-images.githubusercontent.com/14292978/84130417-8b034700-aa43-11ea-92fe-267e7035dc88.PNG)

**Comment by JC5** [comment] 2020-06-09 09:32
This is an ongoing issue I hope to have fixed in the next release. I'm not sure yet about the root cause. Check out recently closed issues as well.

**Comment by jerheij** [comment] 2020-06-09 09:39
I see, thanks for the super quick response and update!

When do you think you'll have the next release ready so I know whether it's worth it to quickly implement something as a hotfix.

**Comment by JC5** [comment] 2020-06-09 11:25
When I know more, you do.

**Comment by JC5** [comment] 2020-06-09 14:57
https://github.com/firefly-iii/firefly-iii/issues/3456

**Closed by JC5** 2020-06-09 14:57 UTC
Labels: question
