### ISSUE TITLE
Bills: next expected match - incorrect day of month if day > 28

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#847] opened 2017-09-15 19:59 UTC
Not a bug but a - inconvenience. Bills set to re-occur e.g. on the 31th of August have the next expected match set to the 1st of October

How to reproduce.
1. Have a bill to repeat monthly (start 31.08)
2. Pay said bill on 30.08
3. Next expected date is 01.10

I know there were some CodeIgniter helpers for this issue, don't know if you can find something for Laravel, but the thing is, I use them for my manually paid monthly bills. My issue here is as follows:

I have to pay my rent every 1st of every month. I do not want to wait till that day, because of bank transfer times (1-2 days), so, just to be on the safe side, I pay it a few days ahead, on the 28th-29th of every month. If I pay my rent on the 28.08 instead of 01.09, the system tells me I still need to pay my rent until the end of the month where I pay the next one, so basically, I'm always on rent behind, in theory. A workaround for this would be to "cheat" the system and tell it I need to pay my rent on the last day of the month, but, that does not really work...

you could add an [inconvenience] tag to this one, not really a [bug] :)

**Comment by JC5** [comment] 2017-09-16 05:09
I'll see if I can't fix that. It should fall back to the last day of the month of course. :)

**Comment by gavu** [comment] 2017-09-20 15:52
Let’s assume the following scenario:

- rent is due on the 1st of every month
- rent is due 01.09.2017
- 01.08.2017 I pay the august rent
- 28.08.2017 I win the lottery and decide to pay september’s rent a few days in advance

- is the rent due 01.09.2017 marked as paid?
- did I just overpay my landlord by an extra rent and owe him another one on 01.09.2017?

I am just trying to understand the bill-payment procedures in the app

**Comment by JC5** [comment] 2017-09-25 05:34
Bills expect a payment each month. Payments can happen twice but they're not transferred to the next month. The system works by checking the current period, not the number of transactions.

* Created a bill due on Aug 31. Did not pay in August.
* System expects next payment Sep 30 (yes, bug is fixed :wink:)

I pay the bill on Sep 25.

* New expected payment is October 30.

I pay the bill again on Sep 25 (or 26, or 27)

Date remains Oct 30.

So if you pay a bill twice in one month, both are matched but the due date for the next one does not change. This is intended behaviour.

To fix this properly Firefly should start using the processing date as well. I'll open another ticket for this.

**Closed** 2017-09-30 05:51 UTC
Labels: bug, fixed
