### ISSUE TITLE
bcadd(): bcmath function argument is not well-formed"). 

### ISSUE THREAD

**Issue by jinformatique** [firefly-iii/firefly-iii#3154] opened 2020-02-27 05:38 UTC
**Bug description**
I am running Firefly III version 5.0.5, and my problem is:

> Whoops! An error occurred.
> Unfortunately, this error was not recoverable. Firefly III broke. The error is:
> An exception has been thrown during the rendering of a template ("bcadd(): bcmath function argument is not well-formed").

I was inserting new expenses in my firefly account and the next thing I know is this error is coming up.

The only thing I did is:
```php artisan cache:clear```
But nothing changed.

**Steps to reproduce**
Each time I log into my ff3 account, I see the same error.

**Extra info**

**Error**

This error occured in file /home/location/jean/resources/views/v1/index.twig on line 88 with code 0.
Stack trace
#0 /home/location/jean/vendor/rcrowe/twigbridge/src/Engine/Twig.php(93): TwigBridge\Engine\Twig->handleTwigError(Object(Twig\Error\RuntimeError))
#1 /home/location/jean/vendor/laravel/framework/src/Illuminate/View/View.php(143): TwigBridge\Engine\Twig->get('/home/jinforma/...', Array)
#2 /home/location/jean/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\View\View->getContents()
#3 /home/location/jean/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#4 /home/location/jean/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\View\View->render()
#5 /home/location/jean/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#6 /home/location/jean/vendor/laravel/framework/src/Illuminate/Routing/Router.php(749): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#7 /home/location/jean/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\Routing\Router::toResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#8 /home/location/jean/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /home/location/jean/app/Http/Middleware/Installer.php(80): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Installer->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /home/location/jean/app/Http/Controllers/Controller.php(96): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(153): FireflyIII\Http\Controllers\Controller->FireflyIII\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#14 /home/location/jean/app/Http/Middleware/InterestingMessage.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\InterestingMessage->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /home/location/jean/app/Http/Middleware/Binder.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Binder->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /home/location/jean/app/Http/Middleware/Range.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Range->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/location/jean/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): PragmaRX\Google2FALaravel\Middleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /home/location/jean/app/Http/Middleware/Authenticate.php(73): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /home/location/jean/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/location/jean/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/location/jean/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home/location/jean/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/location/jean/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /home/location/jean/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home/location/jean/app/Http/Middleware/Sandstorm.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Sandstorm->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /home/location/jean/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#40 /home/location/jean/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#41 /home/location/jean/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#42 /home/location/jean/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#43 /home/location/jean/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#44 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#45 /home/location/jean/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /home/location/jean/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /home/location/jean/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /home/location/jean/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /home/location/jean/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /home/location/jean/app/Http/Middleware/SecureHeaders.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\SecureHeaders->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /home/location/jean/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /home/location/jean/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#59 /home/location/jean/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#60 /home/location/jean/public/index.php(76): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#61 {main}

![Screenshot_2020-02-27 Firefly III](https://user-images.githubusercontent.com/487038/75415190-27895980-592b-11ea-8105-631135ded9da.png)

**Comment by JC5** [comment] 2020-02-27 06:39
Thanks for reporting. It looks to be something in one of your accounts. Could you browse to /preferences and select one or two other asset accounts to be put on the frontpage? Maybe that way we can isolate which account is the culprit.

**Comment by jinformatique** [comment] 2020-02-27 09:00
Ok many thanks, I was able to find out the account responsible for the error.When I made an expense that put the account balance to 0 then the page with that account crashes. I just reproduce this error!

**Comment by JC5** [comment] 2020-02-27 13:26
Thanks for letting me know! Which currency?

**Comment by jinformatique** [comment] 2020-02-27 14:15
I use only € for all my accounts

**Comment by JC5** [comment] 2020-02-27 16:26
Are you running PHP7.4 by any chance?

**Comment by JC5** [comment] 2020-02-27 16:35
I pushed some fixes to the develop branch that I hope will fix this in 5.1.0

**Comment by JC5** [comment] 2020-03-06 06:44
Fixed in 5.1.0

**Closed by JC5** 2020-03-06 06:44 UTC
Labels: bug, fixed

**Comment by jinformatique** [comment] 2020-03-14 08:51
Hi, I just upgraded to 5.1.1 and when go to /public/accounts/asset, I got the following error again:

> Whoops! An error occurred.
> Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:
> bcadd(): bcmath function argument is not well-formed

I'm running PHP Version 7.4.3.
I only use € and one of my account has a balance of 0.

**Comment by JC5** [comment] 2020-03-14 09:31
Can you enable debug and look for these lines?

```
Steam::balance. Native balance is 
Steam::balance. Foreign balance is 
```

**Comment by JC5** [comment] 2020-03-14 09:32
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://docs.firefly-iii.org/faq/other#how-do-i-enable-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on GitHub, please [send them to me over (encrypted) email](https://docs.firefly-iii.org/contact/contact).

**Comment by JC5** [comment] 2020-03-14 15:40
Thanks for sending me the logs. I know the cause. Not yet the solution, but the cause at least. :+1:

**Comment by vlcty** [comment] 2020-03-22 22:17
This is going to be fixed in 5.1.2, right?

**Comment by JC5** [comment] 2020-03-23 10:04
5.2.0, probably.

**Comment by vlcty** [comment] 2020-03-23 17:55
Thanks! My receips are slowly piling up ^^

**Comment by jinformatique** [comment] 2020-03-23 23:27
Hi, I'm less motivated to log my expenses because I cannot see the total.
I continue to log them by going to Transactions, Expenses. I just cannot see the total of my account. I just can't see the total of my accounts on the page: Asset accounts.
I'll wait patiently and eagerly for 5.2.0.
