### ISSUE TITLE
The standard financial report does not show all transactions for the income categories

### ISSUE THREAD

**Issue by Neroxeles** [firefly-iii/firefly-iii#9427] opened 2024-11-04 21:39 UTC
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The standard financial report does not show all transactions for the income categories. The transfer on September 30, 2024 in the amount of 1.82 € is shown correctly (as shown in the figure below). The transfer on October 31, 2024 of 80 € is not shown in the table. However, it can be seen in the graphical representation. The transfer comes from the same source account. The September transfer goes to a normal balance sheet account and the October transfer goes to a savings account that is not included in equity. The bug could not be reproduced on the demo website.

### Debug information

Debug information generated at 2024-11-04 22:14:29 for Firefly III version **v6.1.21**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.21 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.12 (64bits) / apache2handler / Linux aarch64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1131, base <span>#</span>91</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Berlin + Europe/Berlin</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>de_DE + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-11-03 23:00:00 (22 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-11-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-11-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>de_DE</td></tr><tr><td>User locale</td><td>de_DE</td></tr><tr><td>Locale(s) supported</td><td>de_DE.utf8: :white_check_mark:<br>de_DE.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0</td></tr></tbody></table>

### Expected behaviour

The value for October should be 80 € and not 0 €.

### Additional info

![Image](https://github.com/user-attachments/assets/ded6fbcb-b690-4370-8511-989e8b0a610a)

**Comment by Neroxeles** [comment] 2024-11-04 21:42
As soon as I have more time, I'll take another closer look. Maybe I'll even find a way to reproduce the error. I will create a new stack on Docker with a fresh Firefly instance.

**Comment by JC5** [comment] 2024-11-05 04:15
Hi, thanks for opening an issue. 

Transfers between accounts that are both included in the report are not displayed as income or expenses. This is not a bug.

**Comment by JC5** [comment] 2024-11-05 05:35
I can't replicate this issue, I look forward to more details. In the mean time, let me know what happens when you browse to `/flush`, it may clear out the cache.

**Comment by JC5** [comment] 2024-11-05 18:35
Mmmm, that could still be a bug. The chart should be report specific. Thanks for sharing these details, I will look into it for sure!

**Comment by JC5** [comment] 2024-11-06 10:43
This is indeed a bug. The chart will be fixed in the next release of Firefly III.

**Closed** 2024-11-09 05:35 UTC
Labels: fixed
