### ISSUE TITLE
Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by bradc87** [firefly-iii/firefly-iii#1053] opened 2017-12-17 16:57 UTC
I am running Firefly III version 4.6.11

Parameter must be an array or an object that implements Countable

this happens when trying to import csv

#### Other important details (log files, system info):

Please visit the /debug page to get extra debug information.

**Comment by JC5** [comment] 2017-12-17 17:04
Hi! Thanks for reporting this problem. I need some more information to debug this.

Could you describe during which step of the import routine the error occurred?

Could you go to `storage/logs` and open the latest log file? It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down.

Does the error occur even when you import just one line of your CSV file? If so, would you be willing to share that particular line, and your configuration file with me?

This would greatly help me figure out what went wrong. Thanks!

**Comment by bradc87** [comment] 2017-12-17 18:06
This happens when I importa a csv, just after the first dconfigurration page, when I click the button that says "step 2/3" 

Then it just gives me a full screen "we'll be right back" message

ig" at line 56. {"userId":1,"email":"brad87@gmail.com","exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"count(): Parameter must be an array or an object that implements Countable\") in \"/srv/http/firefly-iii/resources/views/import/csv/roles.twig\" at line 56. at /srv/http/firefly-iii/vendor/twig/twig/lib/Twig/Template.php:230, ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at /srv/http/firefly-iii/vendor/twig/twig/lib/Twig/Extension/Core.php:1203)"} 
[2017-12-17 16:45:31] local.ERROR: An exception has been thrown during the rendering of a template ("count(): Parameter must be an array or an object that implements Countable") in "/srv/http/firefly-iii/resources/views/import/csv/roles.twig" at line 56. {"userId":1,"email":"brad87@gmail.com","exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"count(): Parameter must be an array or an object that implements Countable\") in \"/srv/http/firefly-iii/resources/views/import/csv/roles.twig\" at line 56. at /srv/http/firefly-iii/vendor/twig/twig/lib/Twig/Template.php:230, ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at /srv/http/firefly-iii/vendor/twig/twig/lib/Twig/Extension/Core.php:1203)"} 
[2017-12-17 16:45:32] local.ERROR: An exception has been thrown during the rendering of a template ("count(): Parameter must be an array or an object that implements Countable") in "/srv/http/firefly-iii/resources/views/import/csv/roles.twig" at line 56. {"userId":1,"email":"brad87@gmail.com","exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"count(): Parameter must be an array or an object that implements Countable\") in \"/srv/http/firefly-iii/resources/views/import/csv/roles.twig\" at line 56. at /srv/http/firefly-iii/vendor/twig/twig/lib/Twig/Template.php:230, ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at /srv/http/firefly-iii/vendor/twig/twig/lib/Twig/Extension/Core.php:1203)"} 
[2017-12-17 16:45:33] local.ERROR: An exception has been thrown during the rendering of a template ("count(): Parameter must be an array or an object that implements Countable") in "/srv/http/firefly-iii/resources/views/import/csv/roles.twig" at line 56. {"userId":1,"email":"brad87@gmail.com","exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"count(): Parameter must be an array or an object that implements Countable\") in \"/srv/http/firefly-iii/resources/views/import/csv/roles.twig\" at line 56. at /srv/http/firefly-iii/vendor/twig/twig/lib/Twig/Template.php:230, ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at /srv/http/firefly-iii/vendor/twig/twig/lib/Twig/Extension/Core.php:1203)"} 
[2017-12-17 16:47:03] local.ERROR: An exception has been thrown during the rendering of a template ("count(): Parameter must be an array or an object that implements Countable") in "/srv/http/firefly-iii/resources/views/import/csv/roles.twig" at line 56. {"userId":1,"email":"brad87@gmail.com","exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"count(): Parameter must be an array or an object that implements Countable\") in \"/srv/http/firefly-iii/resources/views/import/csv/roles.twig\" at line 56. at /srv/http/firefly-iii/vendor/twig/twig/lib/Twig/Template.php:230, ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at /srv/http/firefly-iii/vendor/twig/twig/lib/Twig/Extension/Core.php:1203)"} 
[2017-12-17 16:48:06] local.ERROR: An exception has been thrown during the rendering of a template ("count(): Parameter must be an array or an object that implements Countable") in "/srv/http/firefly-iii/resources/views/import/csv/roles.twig" at line 56. {"userId":1,"email":"brad87@gmail.com","exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"count(): Parameter must be an array or an object that implements Countable\") in \"/srv/http/firefly-iii/resources/views/import/csv/roles.twig\" at line 56. at /srv/http/firefly-iii/vendor/twig/twig/lib/Twig/Template.php:230, ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at /srv/http/firefly-iii/vendor/twig/twig/lib/Twig/Extension/Core.php:1203)"} 
[2017-12-17 16:50:06] local.ERROR: An exception has been thrown during the rendering of a template ("count(): Parameter must be an array or an object that implements Countable") in "/srv/http/firefly-iii/resources/views/import/csv/roles.twig" at line 56. {"userId":1,"email":"brad87@gmail.com","exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"count(): Parameter must be an array or an object that implements Countable\") in \"/srv/http/firefly-iii/resources/views/import/csv/roles.twig\" at line 56. at /srv/http/firefly-iii/vendor/twig/twig/lib/Twig/Template.php:230, ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at /srv/http/firefly-iii/vendor/twig/twig/lib/Twig/Extension/Core.php:1203)"}

**Comment by JC5** [comment] 2017-12-17 18:14
That's a very strange error. How did you configure your columns?

**Comment by bradc87** [comment] 2017-12-18 00:51
The only thing that I changed from default values was the date string m/d/Y

**Comment by JC5** [comment] 2017-12-18 04:19
Could you share one or two lines of your CSV file with me?

**Comment by bradc87** [comment] 2017-12-19 15:01
11/20/2017,CANADA           CCB,,153.46,8430.95
11/20/2017,TD ATM W/D    001266,440.00,,7990.95
11/20/2017,LOBLAWS RCSS #1     ,25.24,,7965.71
11/21/2017,SSV TO:  32036389945,7.00,,7958.71
11/22/2017,PAYPAL           MSP,15.93,,7942.78
11/23/2017,WSIB             PAY,,1818.63,9761.41
11/24/2017,LN PYMT   *150525101,115.34,,9646.07
11/24/2017,PC MASTRCRD  A2J8X6 ,250.00,,9396.07
11/24/2017,SCOTIA VISA  A2J8X7 ,130.00,,9266.07
11/24/2017,GC 3203-CASH WITHDRA,15.00,,9251.07

**Comment by JC5** [comment] 2017-12-19 17:58
OK, I've been able to import your data into a newer version of Firefly. That means either the issue is now fixed, or maybe something went wrong configuring the columns.

Here's what I did, and the result.

![screen shot 2017-12-19 at 18 56 37](https://user-images.githubusercontent.com/5889984/34171407-86d1c58e-e4ee-11e7-910c-4f091d543b2f.png)

![screen shot 2017-12-19 at 18 57 06](https://user-images.githubusercontent.com/5889984/34171412-8bc1d0f2-e4ee-11e7-97fb-8054e7ba0647.png)

**Comment by bradc87** [comment] 2017-12-19 19:56
Seems to have something to do with file size

try my full file


- Brad

**Comment by JC5** [comment] 2017-12-19 20:12
I shall, could you send it to me over mail?

**Comment by bradc87** [comment] 2017-12-21 16:43
email addy?

- Brad

**Comment by JC5** [comment] 2017-12-21 17:58
There's nothing there, I think Github strips them. You can send them to me personally at thegrumpydictator@gmail.com.

**Comment by Findus23** [comment] 2017-12-22 10:01
Just a quick note:
`Parameter must be an array or an object that implements Countable` happens normally because of a change in PHP 7.2.

**Comment by JC5** [comment] 2017-12-22 10:04
I wasn’t aware, thanks. @bradc87, are you running PHP7.1?

**Comment by JC5** [comment] 2017-12-22 10:05
Errr, 7.2?

**Comment by bradc87** [comment] 2017-12-23 19:38
yes running 7.2


- Brad

**Comment by JC5** [comment] 2017-12-27 20:52
Thanks for sending me the file. It works on my server when I use both PHP7.1 and PHP7.2.

What did you set the columns to?

**Comment by JC5** [comment] 2018-01-07 11:45
Release is live, issue will be closed.

**Closed by JC5** 2018-01-07 11:45 UTC
Labels: fixed, possible bug
