### ISSUE TITLE
Upgrade from 4.6.4 or 4.6.5 to 4.6.7 failed

### ISSUE THREAD

**Issue by uffer** [firefly-iii/firefly-iii#927] opened 2017-10-14 18:39 UTC
Hi JC5,

Upgrade from 4.6.5 or 4.6.6 to 4.6.7 was failed with following errors:

With install method:
`composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii-updated 4.6.7`

>
>
> grumpydictator/firefly-iii (4.6.7)
> - Installing grumpydictator/firefly-iii (4.6.7): Downloading (100%)
>Created project in firefly-iii-updated
>> @php -r "file_exists('.env') || copy('.env.example', '.env');"
>Loading composer repositories with package information
>Installing dependencies from lock file
>Your requirements could not be resolved to an installable set of packages.
>
> Problem 1
>    - Installation request for php-coveralls/php-coveralls v1.0.1 -> >satisfiable                                                                                         by php-coveralls/php-coveralls[v1.0.1].
>   - php-coveralls/php-coveralls v1.0.1 requires ext-simplexml * -> the >request                                                                                        ed PHP extension simplexml is missing >from your system.
>

and after: `php artisan migrate --env=production `

`user@server:/var/www/firefly-iii-updated# php artisan migrate --env=production
PHP Warning:  require(/var/www/firefly-iii-updated/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/firefly-iii-updated/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/var/www/firefly-iii-updated/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/firefly-iii-updated/artisan on line 18
`
I was on version 4.6.5 and now on 4.6.6.

Is this bug related?

Thanx!

**Comment by JC5** [comment] 2017-10-14 18:56
It can be fixed by installing the `php-xml` or `php7.0-xml` package, depending on your system.

Root cause is that I accidentally put the wrong dependency in the composer file, which makes composer look for packages you normally don't need.

**Comment by uffer** [comment] 2017-10-14 18:59
Ah ok thanx! will try that and report back.

**Comment by JC5** [comment] 2017-10-15 07:01
I've pushed a new release so installing the package should no longer be necessary. Please open an issue when you run into trouble!

**Closed by JC5** 2017-10-15 07:01 UTC
