### ISSUE TITLE
date-transaction is cleared with Select Transactions -> Edit.

### ISSUE THREAD

**Issue by downforce** [firefly-iii/firefly-iii#2082] opened 2019-02-13 06:36 UTC
**Bug description**
I am running Firefly III version 4.7.11 (docker jc5x/firefly-iii:develop), and my problem is: 
- When editing a list of transactions after an import, the date-transaction field is cleared from the edit screen. Once pressing save, the date is set to NOW.

**Steps to reproduce**
- View a list of  transactions (import tag, category of transactions etc)
- Bottom right "Select Transaction"
- Select some transactions
- Bottom left: Action -> Edit
- Date is viewed as 'dd/mm/yyyy' (as per my settings), not with a real date (01/01/2019).
- NOTE: Going to a single transcation and pressing Edit is OK.

**Expected behavior**
- See the original date as per the transaction

**Other Info**
Could this be related to the date issue in #2071? 

**Bonus points**
- Correct imported date 👍 :
![Correct Date](https://user-images.githubusercontent.com/246960/52691594-41643280-2f9c-11e9-9b96-2c7bddacb773.png)
- Date cleared! 👎 
![Date Cleared](https://user-images.githubusercontent.com/246960/52691614-5214a880-2f9c-11e9-9112-75507c3a2a38.png)
- Date changed to now 💩 
![Date changed to now](https://user-images.githubusercontent.com/246960/52691644-6e184a00-2f9c-11e9-8ba9-968b1a6e65ee.png)

Thanks.

**Comment by JC5** [comment] 2019-02-13 06:37
Thanks for letting me know. I think I know the cause and I'll push a fix :)

**Comment by NanneHuiges** [comment] 2019-02-13 16:26
I've just experienced this when editing. I know you're aware but not sure if the fix was pushed. If so, it didn't work, if there was no push yet just sorta ignore this comment for the 'me too' that it is :D

Running develop now as per the other thread, so that was a medium good idea :)
I'll wait for the next release and will switch back to  master I guess

**Comment by JC5** [comment] 2019-02-13 17:02
I pushed a fix. The build is running. Once it's finished the Docker image will be updated:

https://travis-ci.com/firefly-iii/firefly-iii/builds/100806516

**Closed** 2019-02-16 18:35 UTC
Labels: bug, fixed

**Comment by JC5** [comment] 2019-02-16 18:37
4.7.12 has been released. Follow the status of the Docker build on [Travis CI](https://travis-ci.com/firefly-iii/firefly-iii/builds).
