### ISSUE TITLE
/accounts/asset missing

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#3816] opened 2020-09-21 11:51 UTC
Version 5.4.0

When I go to /accounts/asset firefly-iii shows an empty page and want's me to create accounts even if I already have accounts.
(same for expense, revenue and liabilities)

**Comment by JC5** [comment] 2020-09-21 13:06
I need some more info than this. Output of /debug please.

**Comment by ralawa** [comment] 2020-09-21 13:18
I have exactly the same issue:

Debug information generated at 2020-09-21 13:16:50 UTC for Firefly III version **5.4.0**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.0 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | c3c0bb49-b6e5-4444-a707-9b73ea83dc39 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-09-01 00:00:00 |
| Session end | 2020-09-30 23:59:59 |
| Session first | 2018-12-31 00:00:00 |
| User ID | 1 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0 |

```
Truncated from this point <----|[2020-09-21 13:14:26] local.INFO: Configured DB version (15) equals expected DB version (15)  
[2020-09-21 13:14:26] local.INFO: Installed Firefly III version (5.4.0) equals expected Firefly III version (5.4.0)  
[2020-09-21 13:14:26] local.INFO: Update check is not enabled.  

```

Do you need something else?

**Comment by JC5** [comment] 2020-09-21 13:21
How did you upgrade, exactly?

**Comment by sephrat** [comment] 2020-09-21 13:24
Same issue when upgrading from beta to stable by changing tag in Docker. Reverting to beta fixes it.
I'll try and see what happens.

**Comment by JC5** [comment] 2020-09-21 13:25
Check, I see it too.

**Comment by JC5** [comment] 2020-09-21 13:46
Found it. May have a fix in a minute.

**Comment by JC5** [comment] 2020-09-21 13:52
Latest `develop` image has a fix. Not sure what's happening. But I believe this will fix the issue. Since this is serious enough, 5.4.1 will follow later today. Thanks for reporting this!

**Comment by sephrat** [comment] 2020-09-21 13:59
On my dev system, upgrading to 5.4.0 did not trigger the issue, but running composer upgrade did. Probably a regression from some library.

**Comment by JC5** [comment] 2020-09-21 14:10
Some Twig libs have updated and I expect an issue there. No matter, should be fixed soon!

**Comment by mehalter** [comment] 2020-09-21 14:53
This seems like it is being handled already, but just wanted to report I also got this issue while updating with `composer` from 5.3.3 → 5.4.0. Looking forward to the 5.4.1 update! Thanks @JC5 !

**Comment by fightforlife** [comment] 2020-09-21 16:47
Same issue, fast response as always!

**Comment by JC5** [comment] 2020-09-21 17:55
5.4.1 is here :+1:

**Closed by JC5** 2020-09-21 17:55 UTC
Labels: bug, fixed
