### ISSUE TITLE
Accept Header processed differently in PUT requests

### ISSUE THREAD

**Issue by adyanth** [firefly-iii/firefly-iii#6829] opened 2023-01-10 17:35 UTC
_Originally posted by @adyanth in https://github.com/firefly-iii/firefly-iii/discussions/6820_

With PUT requests, only `Accept: application/json` works, whereas in GET/POST requests, `Accept: */*` and no Accept headers work as well. In PUT, these redirect to the login page.

**Comment by JC5** [comment] 2023-01-11 04:58
I pushed a fix for this to the demo site, I was hoping you could verify it works as expected.

**Comment by adyanth** [comment] 2023-01-11 05:08
Can test once I am back at my desk

**Comment by adyanth** [comment] 2023-01-11 06:03
[demo.fire](https://demo.firefly-iii.org) seems to be down?

**Comment by JC5** [comment] 2023-01-11 06:12
Should be up and running again, I was wrestling with the reset script.

**Comment by adyanth** [comment] 2023-01-11 06:26
It is up now, but I am getting a 403. Not sure what is going on. I verified the JWT to be good

```bash
❯ curl -X POST \
-H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiMDhhNzliOGQyZTUyZDhjZDdlODJjMjZjOWE5ODMwMWQ5YTY1YWVlMmRhN2E0N2I0ODE5NGFiNWFiZTcwMzEwZTkxMzlkMDczOTk0ODBlN2MiLCJpYXQiOjE2NzM0MTc1MTQuMzI3NzI4LCJuYmYiOjE2NzM0MTc1MTQuMzI3NzMsImV4cCI6MTcwNDk1MzUxMy43MDU3MjQsInN1YiI6IjEiLCJzY29wZXMiOltdfQ.YRkODRglErHJPPE6FXG6f1qG_K0pYMNv_n5m_r0-dTIKkieZrgNuRsuhEzbKr0QicDLW9F-hQ9dKH-sPQLU40C1Y9cegYdQmFQcUrD30FLcgd7DeKWp6R-2fMg11NMoAUeTds31h4h0YPk5OfNU4Ognd71EhmfsAmIeIISRPtw29iXGysYoERI6dXbdy4IZE_p-fXdmwlBbkf09Q7CCwZy7vlDv5ceFHt9azZw5oRZCwHNzIf8VfBuXPZWEsnBowFSWH4Wy2JoIIcJPea8o51VWrzGc5VDXB1xbVuwYDPrgeH9r-KRr_XWq7934u74OFsFIcDI_JBLGvacIk5fuM6XgrfiH1ifxJshv14GNLHBn7hRsJZlcE5E8NvEIu5UXDVkONvK1YB6w3U3943OirO4YlLX_9YZr_zgesWDXVMJEXH3S_4x0DTPJZaF6tlQfnD_SxDDS6hE_ZgXv0ceCiBJhEkPW5kwhZ0STHjjvz9TKo1LyegXxS3CFxEZrZa1bSpzuEWvCU2EkTK-ExeJ2mUtCB87PWOMFg2F421K7Bt9jd_iTo4V0T8pvlS_x6opbdvMhOIWqt0dJDb2H7161hhdZQD8gD6fIRh3LjwpOEDeSezS8utISS2e1YybOwARALG5iPmZo5-a-2Ku6Mrzt3pz2WL5oVCMADEOH5o4c32Zw' \
-H 'Accept: */*' \
-H 'Connection: keep-alive' \
-H 'Content-Length: 2' \
-H 'Content-Type: application/json' \
-H 'User-Agent: python-requests/2.28.1' \
-d '{}' \
https://demo.firefly-iii.org/api/v1/transactions -v
> connection: keep-alive
> content-length: 2
> content-type: application/json
> user-agent: python-requests/2.28.1
> 
* We are completely uploaded and fine
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 403 
< date: Wed, 11 Jan 2023 06:24:00 GMT
< content-type: text/html
< cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=0lxU42vo8GjslwxF9TTZOw%2BXd4cHRtr9v62efX74r4fRtt8cwlJ7pW%2Bb22wrsYRmPvuj3FWVCGq5m2MIkPRjY5RrTzJyhfUsAZVkfwdaIoynx9l4r1igy4YYRvPoqqKEMBQBdSlx5g%3D%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< strict-transport-security: max-age=0; includeSubDomains; preload
< x-content-type-options: nosniff
< server: cloudflare
< cf-ray: 787b911f7a375214-LAX
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
< 
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty/1.21.4.1</center>
</body>
</html>
* Connection #0 to host demo.firefly-iii.org left intact
```

**Comment by JC5** [comment] 2023-01-11 06:32
> python-requests/2.28.1

Sorry, this UA is banned on the demo site because of endless bots. 

I see that your code works but when you send `*/*` it won't respond with a JSON response. I think that's Laravel's issue but I'll see what I can do.

**Comment by adyanth** [comment] 2023-01-11 06:51
Haha, interesting solution for bots :)

Sure, let me know once you change for `*/*`, I will overwrite the UA and try again.

**Comment by JC5** [comment] 2023-01-11 07:14
> Haha, interesting solution for bots :)

You'd be surprised how well it works 😁 

Try again if you would!

**Comment by adyanth** [comment] 2023-01-11 07:33
Does not look like the transaction is being updated, I get the old response back in the PUT API response?

```bash
curl -X PUT -H 'Accept: */*' \
-H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiMWUyMWQyMzlmMTgyNDRiZDI4ZDMyNTQzZDE1M2VjNjlhZDg0MzY1NDA2NGVmMDg5NGZiNTQ2YzZkYTRlYjMwMzNjYjY0MDg4YzdiOGFlMjAiLCJpYXQiOjE2NzM0MjE1MjguMjI4MzQ2LCJuYmYiOjE2NzM0MjE1MjguMjI4MzQ4LCJleHAiOjE3MDQ5NTc1MjcuODI0MjYxLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.HyoaK2tU4MVdjSUVdEbk2QFij76HLYngzyHKu9phPy9AKm9WqSoWqtWr5F95wtyFuqxYBDDtT4AOqf1dRJQb7pg4wMoEH4TFFr4Mj-D5JrkteM1t7YznWieF1l_rkrvwO1yBWhEIsYxgN2UvHvuLoFqqA68BxaUjdzdseeYJb9utVQTQ8poqGOSZyMFT0OafXdetteA7HxRAiSBmI2HwMhKYxE0oMjKZ8Fd2vHu6WxeNZ-N2eFDGVoMT0A4bcuh6SaAhXxmhRWRXiUP70iOxf-7Kz1u25KESjnTdSZstxe3i60ouLnetB64KbrTz5CGM3fRylUghBJbC4BeNhZbDHUSddAID0gq6pFHoGxFsO1jN02xT8FioIuQEw4lesFVzI1K1uVgO4dkIWuD7NwuK_HOX7BETFHzZuVt-amDHnobpKzkM7FyxiwmA3bmUKxUpmt0qWMCgE-ipZI9VLAR6jtj3BamkdrhVNrKTxuAbisUgzErR1cbLARCbAeH1SSZa1rJpgTrJt4MM3ZpzQc-n0SImdwCgHxK9urK6PexKEjzVJuyGQ_TwMAYC3mvnkO9bMaW5CU7gihwsf8I2pjurWwp9Phynk7UzANssKE9Wh85IZ3C_AI9cpCXOACIeL-l8G3Gu7gkL2a9M-YdZg053bAlc7eniF769NC0eRFVcNus' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15' \
-d '{"created_at":"2023-01-11T08:23:13+01:00","updated_at":"2023-01-11T08:23:13+01:00","user":"1","group_title":"Subway","transactions":[{"user":"1","transaction_journal_id":"453","type":"withdrawal","date":"2023-01-11T01:39:35+00:00","order":0,"currency_id":"8","currency_code":"USD","currency_name":"US Dollar","currency_symbol":"$","currency_decimal_places":2,"foreign_currency_id":"0","foreign_currency_code":"None","foreign_currency_symbol":"None","foreign_currency_decimal_places":0,"amount":"4.76","foreign_amount":"None","description":"Subway","source_id":"45","source_name":"Amex","source_iban":"None","source_type":"Asset account","destination_id":"46","destination_name":"Subway","destination_iban":"None","destination_type":"Expense account","budget_id":"0","budget_name":"None","category_id":"11","category_name":"Dining","bill_id":"None","bill_name":"None","reconciled":false,"notes":"None","tags":[],"internal_reference":"None","external_id":"None","original_source":"ff3-v5.8.0-alpha.1|api-v2.0.0-alpha.1","recurrence_id":"None","recurrence_total":"None","recurrence_count":"None","bunq_payment_id":"None","external_url":"https://secure.splitwise.com/expenses/2123102217","import_hash_v2":"697635073dcc16ea074693e4e39b8602d55a5035357087db8208c39e809e9f3c","sepa_cc":"None","sepa_ct_op":"None","sepa_ct_id":"None","sepa_db":"None","sepa_country":"None","sepa_ep":"None","sepa_ci":"None","sepa_batch_id":"None","interest_date":"None","book_date":"None","process_date":"None","due_date":"None","payment_date":"2023-01-10T20:56:09+00:00","invoice_date":"None","longitude":"None","latitude":"None","zoom_level":"None","has_attachments":false}]}' \
https://demo.firefly-iii.org/api/v1/transactions/448
```

I changed the description on the UI, and sending this body which has a different description and a different amount does not change.

**Comment by JC5** [comment] 2023-01-11 08:17
I see it too, but I'm getting 405's at the moment, I'm not sure what the issue is.

**Comment by JC5** [comment] 2023-01-11 16:35
It looks like Laravel refuses to play nice with `*/*`, even when I do. Sorry, this is not something I can fix.

**Comment by adyanth** [comment] 2023-01-11 16:40
Ohh is it? I can always set the Accept header, and that can be documented somewhere in the API docs too, but I am thinking if you can replace the */* with application/json and let Laravel continue.

I would have loved to contribute, but PHP is not a weapon in my arsenal 😅

**Comment by JC5** [comment] 2023-01-11 16:43
> documented somewhere in the API docs too

It's documented in the Swagger docs, but i'll make it more explicit. Not really sure why it refuses to play nice but it looks like it doesn't like to respond to validation errors (422) nicely.

**Closed** 2023-01-15 15:10 UTC
Labels: bug, fixed
