### ISSUE TITLE
Splitting transactions displays incorrect currency

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#738] opened 2017-08-08 10:24 UTC
Firefly 4.6.3.1
I recorded a transaction for an account with different currency (EUR) than the default one (PLN). Then I decided to split the transaction. The split transaction window displays default currency (PLN) instead of account currency (EUR):
![firefly-error](https://user-images.githubusercontent.com/4746858/29067805-b10a43b4-7c3c-11e7-8a11-bb9395087611.png)

**Comment by JC5** [comment] 2017-08-08 11:09
I'll get on it! Actually changing the currency as well may just be a bridge to far but we'll get there.

**Comment by JC5** [comment] 2017-08-09 15:02
I can't reproduce this. EUR is default in my test instance.

* EUR expense on EUR account in EUR: Firefly displays EUR
* USD expense on USD account in USD: Firefly displays USD.
* USD expense on EUR account (must be entered in both USD and EUR): Firefly displays both.

Could you run these queries?

`select * from account_meta where account_id=X` where X is source account ID.

`select id,account_id,transaction_currency_id,amount,foreign_amount,foreign_currency_id from transactions where transaction_journal_id=X` where X is the journal ID.

**Comment by skibbipl** [comment] 2017-08-13 09:24
First query:
```
id | created_at | updated_at | account_id | name | data
9 | 2017-01-01 12:43:31 | 2017-01-01 12:43:31 | 5 | accountRole | "defaultAsset"
10 | 2017-01-01 12:43:31 | 2017-01-01 12:43:31 | 5 | accountNumber | "XXXXXXXXX"
11 | 2017-01-01 12:43:31 | 2017-01-01 12:43:31 | 5 | currency_id | 1
12 | 2017-01-01 12:43:31 | 2017-01-01 12:43:31 | 5 | BIC | ""
55 | 2017-04-09 11:23:44 | 2017-04-09 11:23:44 | 5 | ccMonthlyPaymentDate | ""
56 | 2017-04-09 11:23:44 | 2017-04-09 11:23:44 | 5 | ccType | ""
```
Second query:
```
id | account_id | transaction_currency_id | amount | foreign_amount | foreign_currency_id
897 | 5 | 1 | -20.0000 | NULL | NULL
898 | 123 | 1 | 20.0000 | NULL | NULL
899 | 5 | 1 | -16.3300 | NULL | NULL
900 | 123 | 1 | 16.3300 | NULL | NULL
901 | 5 | 1 | -3.2000 | NULL | NULL
902 | 123 | 1 | 3.2000 | NULL | NULL
```

**Comment by JC5** [comment] 2017-08-13 09:30
Final query:

```
select transaction_currency_id from transaction_journals where id = X
```

I'm going to assume the answer isn't `1`?

**Comment by skibbipl** [comment] 2017-08-14 07:19
Nope, the result is 1

**Comment by JC5** [comment] 2017-08-16 05:34
Strange. But we'll just have to dig deeper!

Could you tell me the result of the following queries?

`select * from journal_meta where transaction_journal_id=X`
`select * from transactions where transaction_journal_id=X`

**Comment by skibbipl** [comment] 2017-08-16 10:13
First query returns no data.
Second query:
```
id	created_at	updated_at	deleted_at	account_id	transaction_journal_id	description	amount	identifier	transaction_currency_id	foreign_amount	foreign_currency_id
897	2017-08-08 09:16:34	2017-08-08 09:36:51	2017-08-08 09:36:51	5	323	NULL	-20.0000	0	1	NULL	NULL
898	2017-08-08 09:16:34	2017-08-08 09:36:51	2017-08-08 09:36:51	123	323	NULL	20.0000	0	1	NULL	NULL
899	2017-08-08 09:36:51	2017-08-08 09:36:51	NULL	5	323	 	-16.3300	0	1	NULL	NULL
900	2017-08-08 09:36:51	2017-08-08 09:36:51	NULL	123	323	 	16.3300	0	1	NULL	NULL
901	2017-08-08 09:36:51	2017-08-08 09:36:51	NULL	5	323	 	-3.2000	1	1	NULL	NULL
902	2017-08-08 09:36:51	2017-08-08 09:36:51	NULL	123	323	 	3.2000	1	1	NULL	NULL
```

**Comment by JC5** [comment] 2017-08-16 10:55
Thanks @skibbipl for providing me with all this data. I'm going to find some time to recreate this transaction (journal) as close as I am able to see what happens. Should trigger the bug.

**Comment by JC5** [comment] 2017-08-19 19:59
Found it, should be fixed in the next release.

**Comment by JC5** [comment] 2017-09-03 07:55
Closed to clear the list.

**Closed by JC5** 2017-09-03 07:55 UTC
Labels: enhancement, fixed
