### ISSUE TITLE
Combining withdrawal and deposit into transfer

### ISSUE THREAD

**Issue by oal** [firefly-iii/firefly-iii#1345] opened 2018-04-15 16:37 UTC
I am running Firefly III version 4.7.2.2

#### Description of my issue:
I've imported my entire banking history into Firefly, and overall it works really well. However, I had to export and import one bank account at a time, so all my transfers between my own bank accounts show up as withdrawals and deposits. Is there a way to detect when a sum has been withdrawed from one account, then deposited into another account during the same day, and convert these into a transfer?

Example:
01.01.2018, Account A: -500 NOK
01.01.2018, Account B: +500 NOK

=> a transfer of 500 NOK from Account A to Account B.

**Comment by JC5** [comment] 2018-04-15 17:33
Even when you import one bank account at a time, Firefly III is capable of creating transfers instead of withdrawals and deposits.

Does the export from your bank feature both your source account and destination account? For example their names or their IBANs?

**Comment by notDavid** [comment] 2018-05-29 13:48
fyi, i'm seeing the same problem.

Perhaps what caused this is, at first when i started importing i had set the source account and destination account fields to "IBAN". If i remember correct what happened was, importing succeeded but it silently _skipped_ all records where the account-number was too long or pehaps didn't fit in an IBAN format ?!

So from then on, when importing, instead of "Asset account (IBAN)" i set the source account and destination account fields to "Asset account (account number).

This change, i assume, messed things up.

@JC5 question: 

1. It's not completely clear to me, what the difference is between setting an [account](https://demo.firefly-iii.org/accounts/create/asset) / imported transaction to "IBAN" vs "account number".

2. is it possible to delete all transactions and accounts to completely start over, but retain rules & categories?

3. It seems i cannot modify an asset account field "IBAN" and set it to "account number". Does this even have any impact?

Thank you! :)

**Comment by JC5** [comment] 2018-05-29 16:34
If you match a field's value to be "IBAN" (either opposing account IBAN or asset account IBAN) Firefly III will silently fail when the value is not a valid IBAN. [Here](https://www.mobilefish.com/download/iban/random_generated_iban.txt) is a list of examples of valid IBANs. If this fails, I am very curious to see the actual IBAN values you try to import.

To answer your questions:

1. The "account number" field is free-format, so you can use whatever you want. The IBAN field only accepts IBAN numbers. If you are sure it's a valid IBAN, I would suggest you use the IBAN field.
2. Yes. There is a delete button next to each asset account.
3. I see that it's not possible to clear the account number. I will fix that in the next release. This is already fixed on the demo site.

**Comment by notDavid** [comment] 2018-05-29 20:51
Thanks for your reply!

> If this fails, I am very curious to see the actual IBAN values you try to import.

No, you are correct. The ones failing are not IBAN numbers. At the first import i saw a few examples which were all IBAN so i figured that would be the best choice. And i was unaware of the consequences. But obviously my transactions also contain foreign non-IBAN numbers.


So, i have:
1. deleted all asset accounts
2. manually deleted all expense accounts and revenue accounts.
3. created a new "Default asset account" and a new "Savings Account" and set both "Account number" fields. (i tripple checked them, they are the same as in the .csv)
4. Re-imported the .csv (and also set the account number fields to "account number" (instead of IBAN.)

However, still i see the money i moved from the "Default asset account" to the "Savings account" as withdrawals and deposits.

PS. I notice that the **descriptions** "FROM" and "TO" do not match. So when i do 1 transaction of €100 from my saving account to my asset account, and lookup the 2 related transactions, and hover over the "From" and "To" fields, i see 4 different account numbers.

**Comment by JC5** [comment] 2018-05-30 05:16
OK, that's a use case I'll have to check out.

I'm not sure what you mean with your PS. One row in your CSV should only result in one transaction (/transactions/show/x).

**Comment by JC5** [comment] 2018-05-30 16:39
OK in the new version, I can safely map to account numbers and Firefly III will resolve them. I created similar accounts as you did, and I gave them account numbers only (and a name).


Then, importing using the account numbers would automatically match the correct accounts.

**Comment by notDavid** [comment] 2018-05-30 19:47
Okay, i managed to reproduce part of the problem on a completely new database. What i did is:
1. Created the 2 accounts
2. Imported the 2 files of both accounts (which each have 1 line/transaction inside)

Here's all the files, including a db dump with the problem. Hope that helps identify the problem. And i hope it's not a stupid mistake on my side... ;-)
https://notdavid.keybase.pub/firefely/Archive.zip?dl=1

Thanks!

**Comment by JC5** [comment] 2018-05-31 05:10
Thanks for sharing, I'll look into it! :+1:

**Comment by notDavid** [comment] 2018-06-01 13:17
Strange! I just checked and i am on version 4.7.3. Also I remember applying 1 fix of 1 line to some file, because i had some issue with importing (can't remember what it was.)

I assume you tested on the latest version, so I'll install 4.7.3.2 and try to reproduce again...

**Comment by JC5** [comment] 2018-06-01 18:29
Alright, I'm closing this one to clear up the list. Final testing is underway and a new release will probably arrive today or tomorrow :).

**Closed by JC5** 2018-06-01 18:29 UTC
Labels: bug, fixed

**Comment by notDavid** [comment] 2018-06-01 19:40
👍 I'll install it as soon as i can get my hands on it :)
