### ISSUE TITLE
Current year not depicted in budget and category graph in all time default financial report

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#2328] opened 2019-07-03 11:39 UTC
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:
The category and budget tables and graphs within the all time default financial report do only show full past years, but not the current one. As you can see in the screenshots, the column for 2019 is missing:

![image](https://user-images.githubusercontent.com/317179/60588559-91029980-9d97-11e9-81ad-7c318caf3ac5.png)

![image](https://user-images.githubusercontent.com/317179/60588587-9fe94c00-9d97-11e9-85e3-e03dd4f1d0b2.png)

Yet, in the sum column, the current year's values are correctly considered.

**Comment by JC5** [comment] 2019-07-03 14:22
What's the range for the report you're viewing? Yearly, I assume?

**Comment by JC5** [comment] 2019-07-03 14:23
I see what you mean. Using currentMonthEnd seems to fix this. Not sure what the cause is. I'll  write it down as a bug and dive into it.

**Comment by JC5** [comment] 2019-08-02 03:23
Will be fixed in the next release.

**Closed** 2019-08-09 19:03 UTC
Labels: bug, fixed
