### ISSUE TITLE
Budget option missing from new withdrawal

### ISSUE THREAD

**Issue by tgkenney** [firefly-iii/firefly-iii#2393] opened 2019-08-10 21:51 UTC
**Bug description**
I am running Firefly III version 4.8.0 (Docker), and my problem is:
There is no budget drop-down when creating a new withdrawal

**Steps to reproduce**

Create a new withdrawal transcation

**Expected behavior**

Should be able to select which budget the withdrawal goes into

**Extra info**

I'm using the official docker container, and my browser is Firefox

I was able to go to the page that shows all transactions without a budget and assign it correctly after the fact, but even editing the transaction after creation did not show the budget option.

![image](https://user-images.githubusercontent.com/48830958/62827123-2fec9380-bb97-11e9-830d-bf6595c9dec2.png)

**Comment by tgkenney** [comment] 2019-08-10 21:53
I'm not sure if I need to create a whole separate issue for it, bu the "Balance" highlight box on the dashboard also seems to be having an issue compared to the last version.  It is showing both income and expenses as negative numbers so my balance is the total of those two negative numbers.

Thanks!

**Comment by JC5** [comment] 2019-08-11 05:16
Yes, this is by design. It will show itself once you select the correct accounts under Source and Destination to create a withdrawal.

Despite the 3 buttons for withdrawal, deposit and transfer, the form behind them is exactly the same in all cases, and will respond dynamically to what you select or type. 

However if the expense account (destination) is new the budget will never appear. I'll fix that.

**Comment by JC5** [comment] 2019-08-11 05:22
I've written both issues down in #2379

**Comment by tgkenney** [comment] 2019-08-11 13:10
Yep that does seem to be the case.  The transaction I noticed it on was a new expense account so that would be why.  Thanks

**Comment by JC5** [comment] 2019-08-13 17:00
This will be fixed in the next release. You might see the budget thing on other types of transactions instead but that really can't be helped I'm afraid.

**Closed** 2019-08-17 10:38 UTC
Labels: bug, fixed
