### ISSUE TITLE
Graph with wrong x-label values (?)

### ISSUE THREAD

**Issue by maxicasa** [firefly-iii/firefly-iii#8041] opened 2023-10-09 07:19 UTC
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I think there is a problem with the graph in the transaction view. Sometimes the value reported on the monthly row doesn't match the value reported in the report view (the correct value is the report): 
![image](https://github.com/firefly-iii/firefly-iii/assets/2181924/a02831c2-9873-44e2-823d-a86cac6cd726)

I have checked the values with my bank reports and the transactions between dates are correct.

### Debug information

Debug information generated at 2023-10-09 09:12:54 for Firefly III version **v6.0.26**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.26 / v2.0.9 / 20 (exp. 20)</td></tr><tr><td>PHP version</td><td>8.2.10 / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>674, base <span>#</span>38</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td> + CET</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>it_IT + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td>:wrench: :email:</td></tr><tr><td>Session start</td><td>2023-10-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-12-31 00:00:00</td></tr><tr><td>View range</td><td>3M</td></tr><tr><td>User language</td><td>it_IT</td></tr><tr><td>User locale</td><td>it_IT</td></tr><tr><td>Locale(s) supported</td><td>it_IT.utf8: :white_check_mark:<br>it_IT.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

The monthly value in the graph and the value in the report (at 31st of the month) must be equal.

**Comment by JC5** [comment] 2023-10-09 09:14
I see what you mean. What happens to the chart after you browse to `/flush`?

Since your chart on the right is per month I cannot be certain what the date range is for which it calculates the balance. It only says "march 2018".

**Comment by maxicasa** [comment] 2023-10-09 09:47
After `/flush` command, nothing changed, same result before.

Do you mean the balance used by month or for all graph?
In the screenshot, the date range used in the transaction view is all transactions for the specific account (in my case between `06/2017` to `09/2023`). In the report view is from `2017-12-31` to `2018-03-31`.

After a little investigation I think I found the problem. The graph does not take the last transactions on the last day of the month, see the new screenshot (the range is `2018-01-01` to `2018-01-31`): 
![image](https://github.com/firefly-iii/firefly-iii/assets/2181924/af5645c7-f0ce-4c5d-8c0b-de9a55537ed2)
Do you agree?

**Comment by JC5** [comment] 2023-10-09 10:50
That seems to be the cause, I will investigate!

**Comment by maxicasa** [comment] 2023-10-09 10:52
Thanks!

**Comment by JC5** [comment] 2023-10-14 04:40
So the chart is "correct", but confusing: it does not have start on the first OR last day of the month, it could be anything. So even though it says "march 2018" perhaps it really means "27 march 2018".

This is a bug of course, and it will be fixed in the next release. Thanks for reporting!

**Closed** 2023-10-15 11:31 UTC
Labels: bug, fixed
