### ISSUE TITLE
Problem when typing Chinese/Japanese characters in Safari

### ISSUE THREAD

**Issue by wilchn** [firefly-iii/firefly-iii#3126] opened 2020-02-17 11:12 UTC
**Bug description**
I am running Firefly III version 5.0.5, when typing Chinese/Japanese characters in text fields that has auto-complete (Ex. Description, Destination account) it will show extra characters.

**Steps to reproduce**
Click New withdrawal -> in Description, type any Chinese characters (ex. da)
Result will be: dda大

**Extra info**
Using Safari (macOS and iOS)

<img width="455" alt="Screenshot 2020-02-17 at 18 55 43" src="https://user-images.githubusercontent.com/40131841/74648791-4e23f380-51b9-11ea-873f-af29ac1fad92.png">

**Comment by JC5** [comment] 2020-02-17 18:15
I'll try to replicate this but to be honest I have no way to do so. Stay tuned for mixed results.

**Comment by JC5** [comment] 2020-02-19 18:53
I'm sorry, I don't even know where to begin to debug this.

**Comment by wilchn** [comment] 2020-02-20 00:46
You can try it in Mobile, can replicate in iPhone. 

1. First add Chinese inputs in Phone settings. 
2. Then using Safari/Chrome navigate to firefly iii
3. Add a transaction, change the input language to Chinese

Or in Windows, can also add Keyboard Input to have Chinese Traditional

**Comment by JC5** [comment] 2020-02-20 04:01
So far nothing weird has happened. Which characters are problematic and how do I type them?

**Comment by wilchn** [comment] 2020-02-20 09:33
![057E0FDD-7B72-4284-8474-5E94567815F1](https://user-images.githubusercontent.com/40131841/74919671-e3b3c300-5405-11ea-88bd-e6796043dbdf.gif)

Suppose I want to type only “大” (da). When first key in d, the text field will immediately put “d” inside the text field causing extra character. Try typing similar “da” in Tags field, it behave properly.

**Comment by zhangriyueming** [comment] 2020-03-10 05:31
> So far nothing weird has happened. Which characters are problematic and how do I type them?

Another bug in this field is that while you insert/delete a character in this filed, the indicator goes the end always. Say you have "ab(indicator here)cd", after you delete 'b', it goes to "acd(indicator here", and then you must tap left twice to "a(indicator here)cd" and again after you tap 'b' it goes to "abcd(indicator here)"

**Comment by JC5** [comment] 2020-06-23 18:20
I'm afraid that this is, ultimately, caused by the ancient autocomplete code I'm using. Since I'm working on a new layout, this bug won't be fixed in the current layout. Sorry about this.

**Closed by JC5** 2020-06-23 18:20 UTC
Labels: bug
