### ISSUE TITLE
Duplicate issues when importing a file

### ISSUE THREAD

**Issue by firsttiger** [firefly-iii/firefly-iii#3351] opened 2020-05-11 00:02 UTC
Hi there, I'm noticing that when I import a particular file, it is duplicating the entire file each time I load it again.

Here are the two records:
Record 1:
```
 {
    "created_at": "2020-05-10 19:19:47",
    "deleted_at": null,
    "id": 1150,
    "title": null,
    "transaction_journals": [
        {
            "attachments": [
            ],
            "bill_id": null,
            "book_date": null,
            "budgets": [
            ],
            "categories": [
            ],
            "completed": true,
            "created_at": "2020-05-10 19:19:46",
            "date": "2020-01-29 00:00:00",
            "deleted_at": null,
            "description": "Email Trfs",
            "id": 1150,
            "interest_date": null,
            "links": [
            ],
            "locations": [
            ],
            "meta": [
                {
                    "created_at": "2020-05-10 19:19:47",
                    "data": "505b0c025de6ba861c08f4cd80f442c49624543eba2a828c3a57e79055f6766b",
                    "deleted_at": null,
                    "hash": "50a2231e7232caba7407283031ee9b9570b303d4f9729dca6750f98e78f5c596",
                    "id": 3095,
                    "name": "import_hash_v2",
                    "transaction_journal_id": 1150,
                    "updated_at": "2020-05-10 19:19:47"
                },
                {
                    "created_at": "2020-05-10 19:19:47",
                    "data": "ff3-v5.2.5|api-v1.1.0",
                    "deleted_at": null,
                    "hash": "d8ee7719b84c0efa18c353b17032b0c93e8bc5d930fc782e52803ae2146f5fee",
                    "id": 3096,
                    "name": "original_source",
                    "transaction_journal_id": 1150,
                    "updated_at": "2020-05-10 19:19:47"
                }
            ],
            "notes": [
                {
                    "created_at": "2020-05-10 19:19:46",
                    "deleted_at": null,
                    "id": 151,
                    "noteable_id": 1150,
                    "noteable_type": "FireflyIII\\Models\TransactionJournal",
                    "text": "INTERAC E-TRF- 4868",
                    "title": null,
                    "updated_at": "2020-05-10 19:19:46"
                }
            ],
            "order": 0,
            "piggy_bank_events": [
            ],
            "process_date": null,
            "tag_count": 0,
            "tags": [
                {
                    "created_at": "2020-05-10 19:18:44",
                    "date": "2020-05-10 00:00:00",
                    "deleted_at": null,
                    "description": "",
                    "id": 7,
                    "pivot": {
                        "tag_id": 7,
                        "transaction_journal_id": 1150
                    },
                    "tag": "CSV Import on 2020-05-10 @ 23:18",
                    "tagMode": "nothing",
                    "updated_at": "2020-05-10 19:18:44",
                    "user_id": 2
                }
            ],
            "transaction_currency_id": 9,
            "transaction_group_id": 1150,
            "transaction_type_id": 2,
            "transactions": [
                {
                    "account": {
                        "account_type_id": 5,
                        "active": true,
                        "created_at": "2020-05-10 19:18:48",
                        "deleted_at": null,
                        "iban": null,
                        "id": 22,
                        "name": "(no name)",
                        "updated_at": "2020-05-10 19:18:48",
                        "user_id": 2,
                        "virtual_balance": null
                    },
                    "account_id": 22,
                    "amount": "-1361.960000000000",
                    "budgets": [
                    ],
                    "categories": [
                    ],
                    "created_at": "2020-05-10 19:19:46",
                    "deleted_at": null,
                    "description": null,
                    "foreign_amount": null,
                    "foreign_currency_id": null,
                    "id": 2299,
                    "identifier": 0,
                    "reconciled": false,
                    "transaction_currency_id": 9,
                    "transaction_journal_id": 1150,
                    "updated_at": "2020-05-10 19:19:46"
                },
                {
                    "account": {
                        "account_type_id": 3,
                        "active": true,
                        "created_at": "2020-05-09 21:29:47",
                        "deleted_at": null,
                        "iban": null,
                        "id": 9,
                        "name": "RBC Joint Chequing Account",
                        "updated_at": "2020-05-09 21:29:47",
                        "user_id": 2,
                        "virtual_balance": null
                    },
                    "account_id": 9,
                    "amount": "1361.960000000000",
                    "budgets": [
                    ],
                    "categories": [
                    ],
                    "created_at": "2020-05-10 19:19:46",
                    "deleted_at": null,
                    "description": null,
                    "foreign_amount": null,
                    "foreign_currency_id": null,
                    "id": 2300,
                    "identifier": 0,
                    "reconciled": false,
                    "transaction_currency_id": 9,
                    "transaction_journal_id": 1150,
                    "updated_at": "2020-05-10 19:19:46"
                }
            ],
            "updated_at": "2020-05-10 19:19:47",
            "user_id": 2
        }
    ],
    "updated_at": "2020-05-10 19:19:47",
    "user_id": 2
```
Record 2:
```
{
    "created_at": "2020-05-10 19:29:02",
    "deleted_at": null,
    "id": 1277,
    "title": null,
    "transaction_journals": [
        {
            "attachments": [
            ],
            "bill_id": null,
            "book_date": null,
            "budgets": [
            ],
            "categories": [
            ],
            "completed": true,
            "created_at": "2020-05-10 19:29:02",
            "date": "2020-01-29 00:00:00",
            "deleted_at": null,
            "description": "Email Trfs",
            "id": 1277,
            "interest_date": null,
            "links": [
            ],
            "locations": [
            ],
            "meta": [
                {
                    "created_at": "2020-05-10 19:29:02",
                    "data": "505b0c025de6ba861c08f4cd80f442c49624543eba2a828c3a57e79055f6766b",
                    "deleted_at": null,
                    "hash": "50a2231e7232caba7407283031ee9b9570b303d4f9729dca6750f98e78f5c596",
                    "id": 3349,
                    "name": "import_hash_v2",
                    "transaction_journal_id": 1277,
                    "updated_at": "2020-05-10 19:29:02"
                },
                {
                    "created_at": "2020-05-10 19:29:02",
                    "data": "ff3-v5.2.5|api-v1.1.0",
                    "deleted_at": null,
                    "hash": "d8ee7719b84c0efa18c353b17032b0c93e8bc5d930fc782e52803ae2146f5fee",
                    "id": 3350,
                    "name": "original_source",
                    "transaction_journal_id": 1277,
                    "updated_at": "2020-05-10 19:29:02"
                }
            ],
            "notes": [
                {
                    "created_at": "2020-05-10 19:29:02",
                    "deleted_at": null,
                    "id": 247,
                    "noteable_id": 1277,
                    "noteable_type": "FireflyIII\\Models\TransactionJournal",
                    "text": "INTERAC E-TRF- 4868",
                    "title": null,
                    "updated_at": "2020-05-10 19:29:02"
                }
            ],
            "order": 0,
            "piggy_bank_events": [
            ],
            "process_date": null,
            "tag_count": 0,
            "tags": [
                {
                    "created_at": "2020-05-10 19:27:58",
                    "date": "2020-05-10 00:00:00",
                    "deleted_at": null,
                    "description": "",
                    "id": 8,
                    "pivot": {
                        "tag_id": 8,
                        "transaction_journal_id": 1277
                    },
                    "tag": "CSV Import on 2020-05-10 @ 23:27",
                    "tagMode": "nothing",
                    "updated_at": "2020-05-10 19:27:58",
                    "user_id": 2
                }
            ],
            "transaction_currency_id": 9,
            "transaction_group_id": 1277,
            "transaction_type_id": 2,
            "transactions": [
                {
                    "account": {
                        "account_type_id": 5,
                        "active": true,
                        "created_at": "2020-05-10 19:18:48",
                        "deleted_at": null,
                        "iban": null,
                        "id": 22,
                        "name": "(no name)",
                        "updated_at": "2020-05-10 19:18:48",
                        "user_id": 2,
                        "virtual_balance": null
                    },
                    "account_id": 22,
                    "amount": "-1361.960000000000",
                    "budgets": [
                    ],
                    "categories": [
                    ],
                    "created_at": "2020-05-10 19:29:02",
                    "deleted_at": null,
                    "description": null,
                    "foreign_amount": null,
                    "foreign_currency_id": null,
                    "id": 2553,
                    "identifier": 0,
                    "reconciled": false,
                    "transaction_currency_id": 9,
                    "transaction_journal_id": 1277,
                    "updated_at": "2020-05-10 19:29:02"
                },
                {
                    "account": {
                        "account_type_id": 3,
                        "active": true,
                        "created_at": "2020-05-09 21:29:47",
                        "deleted_at": null,
                        "iban": null,
                        "id": 9,
                        "name": "RBC Joint Chequing Account",
                        "updated_at": "2020-05-09 21:29:47",
                        "user_id": 2,
                        "virtual_balance": null
                    },
                    "account_id": 9,
                    "amount": "1361.960000000000",
                    "budgets": [
                    ],
                    "categories": [
                    ],
                    "created_at": "2020-05-10 19:29:02",
                    "deleted_at": null,
                    "description": null,
                    "foreign_amount": null,
                    "foreign_currency_id": null,
                    "id": 2554,
                    "identifier": 0,
                    "reconciled": false,
                    "transaction_currency_id": 9,
                    "transaction_journal_id": 1277,
                    "updated_at": "2020-05-10 19:29:02"
                }
            ],
            "updated_at": "2020-05-10 19:29:02",
            "user_id": 2
        }
    ],
    "updated_at": "2020-05-10 19:29:02",
    "user_id": 2
}
```

**Comment by JC5** [comment] 2020-05-11 04:30
OK. Make sure you pull the latest develop branch for the CSV importer, which I assume you're using.

**Comment by bjornaelvoet** [comment] 2020-05-11 11:56
Hi,

  Experiencing the same behaviour.
  
  After some trials with several files; it seems like the web GUI checkbox "Do not import already existing transactions." is behaving oppositely as it should behave?
 
  So checking the box creates transactions although they are duplicate ones. Unchecking the box provides the import message "Line #0: transactions.0.description: Duplicate of transaction #10384. (original value: "C0C31INLR28YXDYE")".

  So solution seems simple; either adapt the description or adapt the logic.

  Thanks!

**Comment by JC5** [comment] 2020-05-11 12:29
I pushed a fix for this 2 days ago, which should be part of the *latest* `develop` build. Make sure you pull the last Docker image or code.

It's kind of a dumb bug, sorry about that.

https://github.com/firefly-iii/csv-importer/commit/4e6c2f5aaf16fb2cca6aa7dffb20dff7e171d611

**Comment by bjornaelvoet** [comment] 2020-05-11 13:16
I cannot confirm yet as I am using entire dockerized firefly services. Will wait until an update of the fireflyiii/csv-importer come out.

Thanks for the great work!

**Comment by JC5** [comment] 2020-05-11 13:19
Which tag are you using for fireflyiii/csv-importer?

**Comment by bjornaelvoet** [comment] 2020-05-11 13:38
fireflyiii/csv-importer:develop

Just pulled an hour ago.

**Comment by JC5** [comment] 2020-05-11 14:17
Alright I'll verify! I swore I got this :grin:

**Comment by JC5** [comment] 2020-05-11 17:17
Sorry, somehow my brain fried in the meantime. Issue is fixed, new Docker build should be ready 5m after this post.

**Comment by bjornaelvoet** [comment] 2020-05-11 18:20
Confirming the fix 👍

**Closed** 2020-05-14 04:33 UTC
Labels: bug, fixed
