### ISSUE TITLE
Error after successful login

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1079] opened 2017-12-30 10:15 UTC
I am using tve latest pull (on my mobile, sorry for not using the template)

Did the following:
Git pull
Composer update
Cache clear

Get following error on dashboard after logging in:
"An exception has been thrown during the rendering of a template ("Undefined property: stdClass::$last (View: /var/www/firefly-iii/vendor/davejamesmiller/laravel ▶"

Please let me know if there’s anything else i can get you

**Comment by JC5** [comment] 2017-12-30 10:24
Many packages have been updated to the latest major version. Your vendor directory might be lagging behind.

Try this:

```bash
rm -rf vendor
rm composer.lock
composer update --no-dev
```

Should do the trick.

**Comment by gavu** [comment] 2017-12-30 11:37
I just did all that. Now the error page looks different and the error is:


(3/3) Twig_Error_Runtime
An exception has been thrown during the rendering of a template ("Undefined property: stdClass::$last (View: /var/www/firefly-iii/vendor/davejamesmiller/laravel-breadcrumbs/views/bootstrap3.blade.php)") in "/var/www/firefly-iii/resources/views/index.twig" at line 4.

**Comment by JC5** [comment] 2017-12-30 19:08
Sorry, I've not been able to reproduce this all day. Any other changes in your environment?

**Comment by gavu** [comment] 2017-12-31 09:26
No changes, no updates, nothing. No worries, I’ll do a fresh install and change the database. I’m on vacation now so it’ll have to wait another week or so.

**Comment by Findus23** [comment] 2017-12-31 09:40
Hi,
I just got the same Error after updating. The exact error was (I reformatted it a bit to make it readable)
```
[2017-12-31 09:27:23] production.ERROR: An exception has been thrown during the rendering of a template 
("Undefined property: stdClass::$last (View: /var/www/firefly-iii/vendor/davejamesmiller/laravel-breadcrumbs/views/bootstrap3.blade.php)")
in "/var/www/firefly-iii/resources/views/index.twig" at line 4. 
{
    "userId":1,
    "email":"myemail@example.com",
    "exception":"[object] (Twig_Error_Runtime(code: 0): 
        An exception has been thrown during the rendering of a template 
            (\"Undefined property: stdClass::$last (View: /var/www/firefly-iii/vendor/davejamesmiller/laravel-breadcrumbs/views/bootstrap3.blade.php)\")
            in \"/var/www/firefly-iii/resources/views/index.twig\" at line 4. 
            at /var/www/firefly-iii/vendor/twig/twig/lib/Twig/Template.php:230, 
        ErrorException(code: 0): 
            Undefined property: stdClass::$last 
            (View: /var/www/firefly-iii/vendor/davejamesmiller/laravel-breadcrumbs/views/bootstrap3.blade.php)
            at /var/www/firefly-iii/storage/framework/views/f4236e9b3730a3728e9710f329a07c821cfa2f3c.php:4,
        ErrorException(code: 0):
        Undefined property: stdClass::$last at /var/www/firefly-iii/storage/framework/views/f4236e9b3730a3728e9710f329a07c821cfa2f3c.php:4)
    "
} 
```

The mentioned file looks like this:
```blade
@if (count($breadcrumbs))

    <ol class="breadcrumb">
        @foreach ($breadcrumbs as $breadcrumb)

            @if ($breadcrumb->url && !$loop->last)
                <li><a href="{{ $breadcrumb->url }}">{{ $breadcrumb->title }}</a></li>
            @else
                <li class="active">{{ $breadcrumb->title }}</li>
            @endif

        @endforeach
    </ol>

@endif
```

I simply removed the `&& !$loop->last` and then firefly loaded without an issue.
Even when I reverted it by deleting the `vendor` folder and doing an `composer install --no-dev` it still works.

**Comment by JC5** [comment] 2017-12-31 09:44
Could you share the info from URL firefly.app/debug with me?

**Comment by Findus23** [comment] 2017-12-31 09:45
Debug information generated at 2017-12-31 09:44:50 UTC for Firefly III version **4.6.12**.

| Variable | Content |
| --- | --- |
| FF version | 4.6.12 |
| PHP version | 7.2.0-1+0\~20171201111333.14+stretch\~1.gbp47ee8a |
| Host | Linux vServer 4.13.0-0.bpo.1-amd64 #1 SMP Debian 4.13.13-1~bpo9+1 (2017-11-22) x86_64 |
| Interface | fpm-fcgi |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, geoip, gettext, iconv, intl, json, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |
| UserID | 1 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| Is Docker (.env) | 'unknown' |
| Trusted proxies (.env) | (none) |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0 |

**Comment by JC5** [comment] 2017-12-31 09:49
7.2? That explains at least something, it's not something I test against and it's a major version up. I'll check it out.

**Comment by JC5** [comment] 2017-12-31 10:12
OK I still get no errors in PHP7.2. My dev-machine is Ubuntu, not debian. No idea what it could be. I've pushed a fix that will use Twig instead of Laravel Blade which might help.

**Comment by Findus23** [comment] 2017-12-31 10:38
I am also not able to reproduce it anymore after I fixed it the first time. Even deleting the cache doesn't change anything.

**Comment by gavu** [comment] 2017-12-31 11:15
It works again. Thanks for the quick fix

**Comment by gavu** [comment] 2017-12-31 11:23
Here’s mu debug info:

Debug information generated at 2017-12-31 11:21:58 UTC for Firefly III version **4.7.0**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.0 |
| PHP version | 7.1.8-1 |
| Host | Linux budget 4.9.41+ #1023 Tue Aug 8 15:47:12 BST 2017 armv6l |
| Interface | apache2handler |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |
| UserID | 1 |
| DB drivers | mysql |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | 'unknown' |
| Is Docker (.env) | 'unknown' |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_1 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0 Mobile/15C153 Safari/604.1 |

**Comment by JC5** [comment] 2018-01-07 11:45
Release is live, issue will be closed.

**Closed by JC5** 2018-01-07 11:45 UTC
Labels: fixed, possible bug
