### ISSUE TITLE
Unknown error preventing to make transfer

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#7215] opened 2023-03-12 14:16 UTC
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I am trying to make a simple transfer from my checking account (sek) to my PayPal account (eur).
This has always worked correctly in the past, but it's seemingly not working now. 

The main issue is that Firefly doesn't give any feedback of what might be going wrong here. 

I have no idea how to further debug this.

![image](https://user-images.githubusercontent.com/706110/224550202-2f87132d-b4d6-4683-9d4d-387a823ece52.png)

### Debug information

Debug information generated at 2023-03-12 00:00:00 Europe/Stockholm for Firefly III version **6.0.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.2 |
| Firefly III API | 2.0.1 |
| Build | 415, 11-03-2023 08:36:01 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Stockholm |
| Browser TZ | Europe/Stockholm |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2015-01-01 00:00:00 |
| Session end | 2023-03-12 23:59:59 |
| Session first | 2015-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0 |

### Expected behaviour

Transfer should be successful, or Firefly should give ma an actual error explaining what is going wrong.

### Steps to reproduce

1. Have sek account
2. Have eur account
3. Create transfer from one to the other

### Additional info

I have not used Firefly for 3 months, but upgraded now to 6.0.2, so I am not sure when things could have broken

**Comment by JC5** [comment] 2023-03-12 14:45
Please upgrade to 6.0.3 and let me know what happens.

**Comment by AlexKalopsia** [comment] 2023-03-12 14:54
Still receiving the same error on 6.0.3

**Comment by JC5** [comment] 2023-03-12 15:00
I see what you mean, I'll check it out!

**Comment by JC5** [comment] 2023-03-12 15:02
Duplicate of https://github.com/firefly-iii/firefly-iii/issues/7214

**Closed by JC5** 2023-03-12 15:02 UTC
