### ISSUE TITLE
[FIDI] error "Could not create transaction. Unexpected empty response from Firefly III. Check the logs."

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#5978] opened 2022-04-08 17:38 UTC
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hey @JC5 
Since I updated FFIII to 5.7.1 (stable) and FIDI to 0.9.1 (develop branch) I'm getting these errors to all previous transactions that are considered as duplicates:

> Line #1: Could not create transaction. Unexpected empty response from Firefly III. Check the logs.

In the FFIII logs I have this:
[2022-04-06 19:06:28] local.DEBUG: Will verify duplicate!  
[2022-04-06 19:06:28] local.WARNING: Found a duplicate in errorIfDuplicate because hash a345372f4281c862c86eb66d942e3ef0b3186ec17675ca7b496e7f6f6c6b69b5 is not unique!  
[2022-04-06 19:06:28] local.WARNING: TransactionJournalFactory::create() caught a duplicate journal in createJournal()  
[2022-04-06 19:06:28] local.ERROR: Duplicate of transaction #23334.  
[2022-04-06 19:06:28] local.ERROR: #0 /var/www/html/app/Factory/TransactionJournalFactory.php(157): FireflyIII\Factory\TransactionJournalFactory->errorIfDuplicate()
#1 /var/www/html/app/Factory/TransactionJournalFactory.php(120): FireflyIII\Factory\TransactionJournalFactory->createJournal()
#2 /var/www/html/app/Factory/TransactionGroupFactory.php(68): FireflyIII\Factory\TransactionJournalFactory->create()
#3 /var/www/html/app/Repositories/TransactionGroup/TransactionGroupRepository.php(479): FireflyIII\Factory\TransactionGroupFactory->create()
#4 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(94): FireflyIII\Repositories\TransactionGroup\TransactionGroupRepository->store()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\Api\V1\Controllers\Models\Transaction\StoreController->store()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\Routing\ControllerDispatcher->dispatch()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\Route->runController()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route->run()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#11 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(68): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\Api\V1\Controllers\Models\Transaction\StoreController->FireflyIII\Api\V1\Controllers\Models\Transaction\{closure}()
#13 /var/www/html/app/Api/V1/Controllers/Controller.php(69): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\Api\V1\Controllers\Controller->FireflyIII\Api\V1\Controllers\{closure}()
#15 /var/www/html/app/Http/Middleware/Binder.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\Binder->handle()
#17 /var/www/html/app/Http/Middleware/Authenticate.php(75): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\Authenticate->handle()
#19 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->Laravel\Sanctum\Http\Middleware\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\Pipeline\Pipeline->then()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(727): Illuminate\Pipeline\Pipeline->then()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\Routing\Router->runRouteWithinStack()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(666): Illuminate\Routing\Router->runRoute()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Routing\Router->dispatchToRoute()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#31 /var/www/html/app/Http/Middleware/InstallationId.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\InstallationId->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#45 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\SecureHeaders->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#50 /var/www/html/public/index.php(76): Illuminate\Foundation\Http\Kernel->handle()
#51 {main}  
[2022-04-06 19:06:28] local.DEBUG: forceDeleteOnError on collection size 0 item(s)  
[2022-04-06 19:06:28] local.WARNING: GroupFactory::create() caught journalFactory::create() with a duplicate!  
[2022-04-06 19:06:28] local.WARNING: Group repository caught group factory with a duplicate exception!  
[2022-04-06 19:06:28] local.WARNING: Caught a duplicate transaction. Return error message.  

### Expected behaviour

Just list as an error and not showing this error message

### Debug information

N/A

**Comment by JC5** [comment] 2022-04-08 17:40
Thanks, I'll check it out. The underlying library has had some changes.

**Comment by JC5** [comment] 2022-04-08 17:51
Found it. Check out the latest develop build of the data importer.

**Comment by MacPaille** [comment] 2022-04-08 18:21
Much better now the email does not provide any error for duplicate transactions :)

Thanks for the quick fix!

**Comment by wouterdt** [comment] 2022-04-09 11:10
i'm still observing something similar(?) on the `develop` branch of the FIDI (using FFIII 5.7.1 stable)

the import aborts in error

Error(s)

    Line #0: Internal error: Undefined array key "data" in file /var/www/html/vendor/firefly-iii/api-support-classes/src/Request/PostTransactionRequest.php:76 



`[root@localhost ~]# docker pull fireflyiii/csv-importer:develop
Trying to pull repository docker.io/fireflyiii/csv-importer ...
develop: Pulling from docker.io/fireflyiii/csv-importer
Digest: sha256:7808f9eb57207a7fde4a3c38a030448a9216a013ebabd14bc3f7d9b7a3979957
Status: Image is up to date for docker.io/fireflyiii/csv-importer:develop
[root@localhost ~]#`

`docker run --rm -e FIREFLY_III_ACCESS_TOKEN=*removed* -e FIREFLY_III_URL=192.168.2.132 -e APP_LOG_LEVEL=debug -e  MAIL_DRIVER=log -p 81:8080 fireflyiii/csv-importer:develop`


i got FIDI running with debug on:
[2022-04-09 13:07:10] production.DEBUG: Submitting to Firefly III: {"group_title":null,"error_if_duplicate_hash":true,"transactions": *removed this*
[2022-04-09 13:07:10] production.DEBUG: Now in setJobStatus(job_errored)
[2022-04-09 13:07:10] production.DEBUG: Found "GeQAVmU7WzB7sqrZ" in the session
[2022-04-09 13:07:10] production.DEBUG: Now in startOrFindJob(GeQAVmU7WzB7sqrZ)
[2022-04-09 13:07:10] production.DEBUG: Try to see if file exists for job GeQAVmU7WzB7sqrZ.
[2022-04-09 13:07:10] production.DEBUG: Status file exists for job GeQAVmU7WzB7sqrZ.
[2022-04-09 13:07:10] production.DEBUG: Now in storeJobStatus(GeQAVmU7WzB7sqrZ): job_errored
[2022-04-09 13:07:10] production.ERROR: Undefined array key "data"
[2022-04-09 13:07:10] production.ERROR: #0 /var/www/html/vendor/firefly-iii/api-support-classes/src/Request/PostTransactionRequest.php(76): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/app/Services/Import/Routine/APISubmitter.php(236): GrumpyDictator\FFIIIApiSupport\Request\PostTransactionRequest->post()
#2 /var/www/html/app/Services/Import/Routine/APISubmitter.php(82): App\Services\Import\Routine\APISubmitter->processTransaction()
#3 /var/www/html/app/Services/Import/ImportRoutineManager.php(190): App\Services\Import\Routine\APISubmitter->processTransactions()
#4 /var/www/html/app/Http/Controllers/Import/RunController.php(139): App\Services\Import\ImportRoutineManager->start()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Import\RunController->start()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\Routing\Route->run()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#11 /var/www/html/app/Http/Middleware/ReadyForImport.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

FFIII side (for some reason the time is in UTC here?)


[2022-04-09 11:07:10] local.INFO: Will trigger duplication alert for this journal.
[2022-04-09 11:07:10] local.WARNING: Found a duplicate in errorIfDuplicate because hash d072e506af36f91783bc96321cc39afc5a9fbdd7dc0e22a0d72f3993a53e8373 is not unique!
[2022-04-09 11:07:10] local.WARNING: TransactionJournalFactory::create() caught a duplicate journal in createJournal()
[2022-04-09 11:07:10] local.ERROR: Duplicate of transaction #793.
[2022-04-09 11:07:10] local.ERROR: #0 /var/www/html/app/Factory/TransactionJournalFactory.php(157): FireflyIII\Factory\TransactionJournalFactory->errorIfDuplicate()
#1 /var/www/html/app/Factory/TransactionJournalFactory.php(120): FireflyIII\Factory\TransactionJournalFactory->createJournal()
#2 /var/www/html/app/Factory/TransactionGroupFactory.php(68): FireflyIII\Factory\TransactionJournalFactory->create()
#3 /var/www/html/app/Repositories/TransactionGroup/TransactionGroupRepository.php(479): FireflyIII\Factory\TransactionGroupFactory->create()
#4 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(94): FireflyIII\Repositories\TransactionGroup\TransactionGroupRepository->store()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\Api\V1\Controllers\Models\Transaction\StoreController->store()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\Routing\ControllerDispatcher->dispatch()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\Route->runController()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route->run()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#11 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(68): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\Api\V1\Controllers\Models\Transaction\StoreController->FireflyIII\Api\V1\Controllers\Models\Transaction\{closure}()
#13 /var/www/html/app/Api/V1/Controllers/Controller.php(69): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\Api\V1\Controllers\Controller->Fi

**Comment by JC5** [comment] 2022-04-09 11:18
You seem to be pulling the CSV importer, not the data importer.

**Comment by wouterdt** [comment] 2022-04-09 11:27
oops! missed that, fixed indeed  with `fireflyiii/data-importer:latest`

**Comment by JC5** [comment] 2022-04-09 17:33
New release is out where this is fixed :+1:

**Closed by JC5** 2022-04-09 17:33 UTC
Labels: bug, fixed
