### ISSUE TITLE
Sandstorm package needs hints for connecting FireflyMobile.

### ISSUE THREAD

**Issue by searoso** [firefly-iii/firefly-iii#1965] opened 2019-01-03 03:39 UTC
I am running Firefly III  Version 4.7.9 on Sandstorm

**Description**
Trying to connect https://github.com/emansih/FireflyMobile to Sandstorm grain it's confusing what should I choose a URL for authentication personal token.
Should it be a grain URL (which strange and they change AFAIK), or can be another URL be acquired in the app?

**Steps to reproduce** 
Generate _personal access token_ and try different URLs provided by Sandstorm to authenticate in "https://github.com/emansih/FireflyMobile".

**Bonus points**
![screenshot_20190103-063537_firefly_iii_mobile](https://user-images.githubusercontent.com/110407/50622929-2c6a9d00-0f22-11e9-847e-19c44440d638.png)

**Comment by JC5** [comment] 2019-01-03 06:36
It has to be the grain URL, because that's where the authentication takes place.

**Comment by searoso** [comment] 2019-01-03 21:57
I retried it several times now, ensured that all data is correct; but no. It just says _authentication failed._ I would post it to FireflyMobile, but for me it looks like Sandstorm package issues.

By the way the link _delete_ at the page with personal tokens doesn't work. (A new issue?)

**Comment by JC5** [comment] 2019-01-04 06:07
Could you check your console for errors? The delete button works fine in my own installation. I will do some debugging later to see what's going on.

**Comment by searoso** [comment] 2019-01-04 06:15
Correct me, if it's not what you wanted.

```
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
JQMIGRATE: Migrate is installed, version 1.4.1
jquery-migrate.min.js:2:542
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Error: Request failed with status code 500
app.js:1:11263
Error: Request failed with status code 500
app.js:1:11263
```

**Comment by JC5** [comment] 2019-01-04 06:58
I know what the issue is with the delete button, and I'll try to fix it asap.

But the jquery-migrate library is not mine and I don't see it in my Sandstorm installation either. Are you running particular extensions?

**Comment by JC5** [comment] 2019-01-04 07:05
I'll have to check what the best way is to open a link to the OAuth2 API with @ocdtrekkie. I found the option for "webkeys" already but I'm not sure how it works. Stay tuned.

**Comment by ocdtrekkie** [comment] 2019-01-04 07:15
This is Sandstorm's documentation on enabling mobile apps: https://docs.sandstorm.io/en/latest/developing/http-apis/

Generally the Sandstorm app uses an "offer template" to create a URL for a mobile app to access the app's API. A good example app that I use daily is Tiny Tiny RSS (the offer template is located in Actions > Preferences > Mobile App on the Sandstorm version.

**Comment by emansih** [comment] 2019-01-04 13:09
Do I have to do anything special for sandstorm?

**Comment by JC5** [comment] 2019-01-04 13:15
It won't work until the next release. The current authentication middleware doesn't recognize a Sandstorm-filtered API request.

**Comment by searoso** [comment] 2019-01-04 16:07
I think it was /PureOS browser/.

**Comment by searoso** [comment] 2019-01-04 16:08
Great to hear! Thank you. )

Could you drop a pop-up in the package, so we see the updates after
first load of new version? Or Sandstorm handles it something different?

**Comment by JC5** [comment] 2019-01-04 16:17
That would also need an update, so I can't warn you about it. I'll close this issue when the release is nearing its completion and then you'll know about it :+1:

**Comment by JC5** [comment] 2019-04-08 18:25
https://github.com/firefly-iii/firefly-iii/projects/5#card-19975121

**Closed by JC5** 2019-04-08 18:25 UTC
Labels: enhancement

**Comment by JC5** [comment] 2019-12-28 09:00
I'm not going to maintain the package on Sandstorm anymore, due to the dwindling support for Sandstorm and the complexities of packaging the app for the Sandstorm environment. So this feature isn't going to be implemented.

**Comment by ocdtrekkie** [comment] 2019-12-28 15:49
@JC5 Just as an FYI, we are currently working to get active development going again, but it may take some time before there's noticeable uptick in interest and porting ease. Hopefully down the road someone might pick up updating the package or the like if we're lucky.

Thanks for working with us. :)

**Comment by JC5** [comment] 2019-12-29 14:19
Please keep me posted! :+1:
