### ISSUE TITLE
APP_URL doesn't works

### ISSUE THREAD

**Issue by setevoy2** [firefly-iii/firefly-iii#1081] opened 2017-12-30 18:59 UTC
I am running Firefly III version 

#### Description of my issue:

Images, CSS, JS-files doesn't load if run Docker container behind a proxy.

#### Steps to reproduce 

NGINX on the frontend with SSL and an `upstream` to Docker container:

```
...
upstream firefly_iii_dev {
    server 127.0.0.1:9091;
}
...
    location / {

        allow 188.***.***.114;

        auth_basic_user_file /var/www/vhosts/firefly-iii/.htpasswd;
        auth_basic "Password-protected Area";

        add_header X-Forwarded-Proto "https";
        proxy_pass http://firefly_iii_dev;
    }
...
```

`docker-compose.yml` have added:

```
...
- APP_URL=https://dev.money.domain.org.ua
- TRUSTED_PROXIES=**
...
```

#### Other important details (log files, system info):

In Chromium dev tools:

> Request URL:http://firefly_iii_dev/lib/bootstrap/css/bootstrap.min.css?v=4.6.12
(and others)

Possible reason: https://github.com/firefly-iii/firefly-iii/blob/master/.env.docker have `APP_URL=http://localhost` instead of `APP_URL=${APP_URL}` (or most likely it must be `${FF_APP_URL}`:

> # docker-compose up                                                                                                                                                                          
> Creating fireflyiii_firefly_iii_app_dev_1 ... done
> Attaching to fireflyiii_firefly_iii_app_dev_1
> firefly_iii_app_dev_1  | APP_ENV=local
> firefly_iii_app_dev_1  | APP_DEBUG=false
> firefly_iii_app_dev_1  | APP_NAME=FireflyIII
> firefly_iii_app_dev_1  | APP_KEY=Naes7oheisahga8ahp0aeshoof3OuFei
> firefly_iii_app_dev_1  | APP_LOG=daily
> firefly_iii_app_dev_1  | APP_LOG_LEVEL=warning
> firefly_iii_app_dev_1  | APP_URL=http://localhost
> firefly_iii_app_dev_1  | TRUSTED_PROXIES=
> ...

**Comment by JC5** [comment] 2017-12-30 19:04
`APP_URL` can be overruled by a environment variable with or without `${APP_URL}` but it isn't used for these things.

Since your proxy pass URL is `http://firefly_iii_dev` I can see why FF3 is using it as an URL.

Try 

```
    proxy_set_header Host dev.money.domain.org.ua;
```


https://firefly-iii.org/using-docker.html

**Comment by setevoy2** [comment] 2017-12-30 19:25
Thanks for such quick review, @JC5 - now it almost works, but now have "blocked mixed content" instead:
> Request URL:http://dev.money.domain.org.ua/lib/bootstrap/css/bootstrap.min.css?v=4.6.12
Trying to add `Content-Security-Policy-Report-Only` header as well - but no luck yet.

**Comment by JC5** [comment] 2017-12-30 19:27
That one is on the site so I know the answer :D

RequestHeader set X-Forwarded-Proto "https"

**Comment by setevoy2** [comment] 2017-12-30 19:31
Great, @JC5! Thanks a lot.

This works for NGINX:

`proxy_set_header X-Forwarded-Proto $scheme;`

All works now.

P.S. Thanks for the FF3 - will contribute to `ru_RU` Translations :-)

**Comment by JC5** [comment] 2017-12-30 19:34
That would be great!

For the translations: whenever you see something like `:start` or `:name` or `:title`, don't translate it. They're placeholders and will be filled in by FF3 itself.

There is a page on the wiki with some tips as well:

https://github.com/firefly-iii/help/wiki/Download-and-enable-an-incomplete-language

Just realise that some translating work has already be done for Russian so you don't need to start over by copying en_US.

**Comment by setevoy2** [comment] 2017-12-30 19:36
// offtopic
I have done some translations on the https://crowdin.com/project/firefly-iii/ru# page as it was mentioned in the documentation.

Btw - the documentation is great too)

**Comment by JC5** [comment] 2017-12-30 19:39
I just keep getting compliments! :grin:

I'm going to close this one because the original issue is fixed. If you have questions, just send me a message or open a new issue. 

Thanks!

**Closed by JC5** 2017-12-30 19:39 UTC
Labels: question

**Comment by t-rascal** [comment] 2018-01-10 11:51
Hi JC5,

First up - thanks so much for building Firefly-III. My wife and I are trialling it at the moment and so far, very impressed!

Just on the above, I seem to have experienced the same issue where environment variables are not passing from the Docker run command through to .env.docker. The show-stopper one is APP_URL which stays at http://localhost and prevents my set-up from working at all (I get a server did not respond error). 

The issue seems to be resolved (at least, Firefly starts working as normal) after I manually edit the .env.docker file to add the APP_URL (which is a https://... served by a NGINX reverse proxy) and then restarting the container so the new values are loaded.

However of course when the container is recreated, the issue re-presents. I think it would be a simple fix to update the .env.docker file to use ${APP_URL} so that others don't encounter the same issue. Of course, it may not be quite that simple - I'm not expert. In fact, this is my first ever Github comment!

Thanks again for your hard work!

**Comment by JC5** [comment] 2018-01-10 18:51
Hi! Thanks for the compliments! I'm glad to hear you like it.

As you can see I've updated the `.env.docker` file, meaning that it will be easier to overrule this config  variable. I've added the often used `TRUSTED_PROXIES` as well.

Let me know if this works, when the next release hits. Should be end of the month.

**Comment by t-rascal** [comment] 2018-01-14 07:33
Hey JC,

I can confirm this now works as expected. Many thanks!
