### ISSUE TITLE
Current balance incorrect due to date filter

### ISSUE THREAD

**Issue by colinerd** [firefly-iii/firefly-iii#1998] opened 2019-01-12 14:39 UTC
**Bug description**
I am running Firefly III version 4.7.9

When looking at the assets (accounts) you can see your current balance however that appears to be incorrect as it looks like it is look at the date range you have selected. Select last month and the figures change.

**Steps to reproduce**
Have a few accounts with transactions in different periods. 
Activate a filter on a specific period.
Look at the assets/accounts current balance.
Change the date range to another period, current balance will change.

**Expected behavior**
Current balance should always display the balance as of right now, hence the name “Current”.

**Comment by JC5** [comment] 2019-01-12 14:44
That’s by design. It will show you the balance of your income and expenses for the selected period. Use “net worth” if you want to know the total amount.

**Comment by colinerd** [comment] 2019-01-12 14:52
I see, bit confusing as I would expect Current to actually show the current. I was hoping this would explain my problems around the balances I currently have with the bunq import as I keep having issues on the import and showing really off figures. Net Worth is showing incorrect figures so will investigate further why I keep having wrong figures on a clean install with the bunq import.

**Comment by colinerd** [comment] 2019-01-12 16:35
I did manage to find something strange earlier today as well, 3 transactions (from 2017) that suddenly wanted to be imported but then disappeared later in the import tag (see screenshots). My net worth (and current balance) changed after this import but did not reflect current conditions, even had the feeling the amounts changed with different values then the import but did not record before I imported.

I have seen this before last week when a lot of older transactions suddenly were being imported, same thing happend on the balance but not sure if the transactions were already present in the database or not.... will keep a closer eye on new imports and if I see older transactions again coming in, deep dive to see what those are and look through my backups to see if they were already present or not.

These were 3 transactions either going or coming from my Rabobank account. They were in the import of today but afterwards when I opened the import again by its tag, they were gone.

![df512709-12dc-4440-aad6-9ce45d46b27d](https://user-images.githubusercontent.com/15741333/51075700-ae2f9880-168f-11e9-9c96-ed5c77eb3652.jpeg)

![0071d1ed-5304-45f5-8bf5-362d266ce2fe](https://user-images.githubusercontent.com/15741333/51075699-ae2f9880-168f-11e9-8dd9-38305eba1f3c.jpeg)

**Comment by JC5** [comment] 2019-01-12 16:40
Are they visible when you click on "show everything" in the middle right of your screenshot?

**Comment by JC5** [comment] 2019-01-12 16:41
Also: thanks for the pointers. It might have to do with the way bunq handles their transaction lists. Thanks for letting me know.

**Comment by colinerd** [comment] 2019-01-12 16:45
Ah, yes they do show now and that did help me find back the import I did earlier where I had multiple old transactions come in the import and.... they are all transactions involving my Rabobank account.

Lets see if I can get some more details on that......

**Comment by colinerd** [comment] 2019-01-13 16:39
#1895 Just referring back to this bug, it looks like it is not resolved fully yet and could explain some differences I still experience regarding auto-save transactions.

On January 1st, had a lot of auto-save transactions due to monthly payments. See screenshot from Bunq and from Firefly below. There are 3 transactions with the amount of 5 euro’s, 2 from the main account and 1 from a saving account. I am missing one of the main account in Firefly as a transaction.

Bunq shows 8 auto-save transactions for the auto-save account however in Firefly I only see 7. I have more examples with the same situation for different dates.

![b7d866eb-dcae-4ad4-9167-3edb26ad809c](https://user-images.githubusercontent.com/15741333/51087914-a76d5800-1759-11e9-96af-63aebe286177.jpeg)

![a0112c80-f904-4263-8117-e4e641b990c6](https://user-images.githubusercontent.com/15741333/51087917-adfbcf80-1759-11e9-8a46-68371059efdf.jpeg)

**Comment by JC5** [comment] 2019-01-14 06:01
Thanks for the screenshots, I'll check it out :+1:

**Comment by JC5** [comment] 2019-01-29 18:40
I'll mark this as a bug to prevent it from closing.

**Comment by colinerd** [comment] 2019-02-02 19:33
Thanks @JC5,
Just to let you know that I have not found any other “missing transactions” besides what I have noted earlier above. Ignoring the differences from this bug, I have got a correct set of data in Firefly by the looks of it.

Hopefully you will find the issue with the auto saving transaction. :-)

**Comment by JC5** [comment] 2019-02-08 15:49
yes, and this should be fixed with the next release. :+1:

**Closed** 2019-02-10 18:28 UTC
Labels: bug, fixed
