### ISSUE TITLE
Cache problems with attachment icon

### ISSUE THREAD

**Issue by wtercato** [firefly-iii/firefly-iii#1096] opened 2018-01-05 23:07 UTC
I am running Firefly III version 4.6.12 

#### Description of my issue:
Hello

Even when attaching a file to the transaction, the icon indicating an attached file does not appear in the transaction list (/public/transactions/withdrawal).

The icon only appears when the file is attach together the creation of the transaction.

The transaction changes are not actually displayed. I changed the name of a budget, but in the transaction list already created, the old name was still displayed, and when I enter the transaction editing screen, the name is correctly like updated. I figured I should have something related to the cache, so I did the cache cleaning (php artisan cache:clear), and the budget name was updated in the transaction listing, but clearing the cache did not solve the problem of displaying the icon indicating an attached file.

![attach01](https://user-images.githubusercontent.com/30444736/34632417-6ee3f76e-f25c-11e7-9ae6-46248212cbcb.jpg)
![attach02](https://user-images.githubusercontent.com/30444736/34632419-724e01a6-f25c-11e7-86cd-fe54174423d6.jpg)

**Comment by JC5** [comment] 2018-01-06 06:45
This looks like it is a caching issue: a lot of field-values and counts are cached.

I cannot reproduce the problem with the icon. It is stored in cache as well so the count should be fixed when you refresh the page. It does not matter how many transactions there are.

I've pushed an update that should clear the cache more aggressively, fixing this problem in a future release. I have no other tips or tricks I'm afraid.

**Comment by wtercato** [comment] 2018-01-06 15:13
Hello.
got it.
clearing the cache solves part of the problem.

is there any way I can disable the cache until a version that fixes this? I have a fairly strong server supporting the system, distributed between Amazon EC2 and Amazon RDS ... thus, the system can display correctly.

I put in the system dozens of transactions, current and winning, and as I am paying these transactions, attach the voucher, and just the icon of the attachment tells me that the transaction is complete.

**Comment by JC5** [comment] 2018-01-06 15:14
Yes, change the `CACHE_DRIVER` in your `.env` to "array". That resets the cache every view. I use it during development.

I will probably push a new release (with this fix) _tomorrow_ because sadly an issue I thought was very rare is cropping up for a lot of people.

**Comment by wtercato** [comment] 2018-01-06 15:30
great. Many thanks for the constant help!

**Comment by JC5** [comment] 2018-01-07 11:44
Release is live, issue will be closed.

**Closed by JC5** 2018-01-07 11:44 UTC
Labels: answered, question
