### ISSUE TITLE
Importing a CSV file causes a SQL error at end of import

### ISSUE THREAD

**Issue by paul999** [firefly-iii/firefly-iii#1858] opened 2018-11-07 14:59 UTC
**Bug description**
I am running Firefly III version DEVELOP branch

A SQL error is given when a file is imported into firefly (See below)

**Steps to reproduce**

Import a CSV file from ING

**Expected behavior**
All transactions are imported

**Extra info**
Log:
```
[2018-11-07 14:57:10] local.ERROR: The import storage routine crashed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'temp_amount' in 'field list' (SQL: update `transaction_journals` set `bill_id` =
 7, `temp_amount` = -73.050000000000, `updated_at` = 2018-11-07 14:57:10 where `id` = 978)
[2018-11-07 14:57:10] local.ERROR: #0 /var/www/sohier/firefly-iii/app/Http/Controllers/Import/JobStatusController.php(215): FireflyIII\Http\Controllers\Import\JobStatusController->storeTransactions(Object(Fi
reflyIII\Models\ImportJob))
#1 [internal function]: FireflyIII\Http\Controllers\Import\JobStatusController->store(Object(FireflyIII\Models\ImportJob))
#2 /var/www/sohier/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#3 /var/www/sohier/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('store', Array)
#4 /var/www/sohier/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(FireflyIII\Http\Contr
ollers\Import\JobStatusController), 'store')
#5 /var/www/sohier/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#6 /var/www/sohier/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(679): Illuminate\Routing\Route->run()
#7 /var/www/sohier/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/sohier/firefly-iii/app/Http/Controllers/Import/JobStatusController.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /var/www/sohier/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(133): FireflyIII\Http\Controllers\Import\JobStatusController->FireflyIII\Http\Controllers\Import\{closure}(Object(
Illuminate\Http\Request), Object(Closure))
#10 /var/www/sohier/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/sohier/firefly-iii/app/Http/Controllers/Controller.php(88): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/sohier/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(133): FireflyIII\Http\Controllers\Controller->FireflyIII\Http\Controllers\{closure}(Object(Illuminate\Http\Reques
t), Object(Closure))

```

**Comment by JC5** [comment] 2018-11-07 16:36
Thanks for reporting. I know the cause and I'll pick it up. Be aware that these breaking bugs might happen more often on the develop branch.

**Comment by JC5** [comment] 2018-11-09 18:00
I've pushed a fix. Could you verify?

**Comment by paul999** [comment] 2018-11-12 08:02
Just updated (Using https://firefly-iii.readthedocs.io/en/latest/installation/upgrading.html#straight-from-github ), and the same error comes up when importing the CSV. Checked the JournalUpdateService.php and the change from daa8aa5 is in there. 

(And yeah, I know running develop might not be the smartest thing :))

**Comment by JC5** [comment] 2018-11-12 08:13
No problem. I'll keep looking :wink:

**Comment by paul999** [comment] 2018-11-12 08:21
Some more info, I just had the same error when making 1 transaction manually, but not when making a bunch other transactions. The only difference between those was that that 1 transaction was for a contract

**Comment by JC5** [comment] 2018-11-12 18:17
I've removed the references to this field in the latest commit. That should solve it for good ;)

**Comment by paul999** [comment] 2018-11-24 11:05
Yep. worked now 👍

**Closed** 2018-12-23 16:15 UTC
Labels: bug, fixed
