### ISSUE TITLE
Triggering rule from Bills view leads to broken page

### ISSUE THREAD

**Issue by RobinWeitzel** [firefly-iii/firefly-iii#2188] opened 2019-03-22 07:05 UTC
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

When I trigger a rule from the Bills page it works but leads to a broken page. The error message Chrome gives is "To many redirects"

**Steps to reproduce**
* Go to /bills
* Select one bill which has a rule attached to it
* On the bills page click "Run rules again, on all transactions"
* Wait until rule has run and you are redirected to /bills/rescan/<some-id>
* This site gives the error (see screenshot)

**Expected behavior**
Not sure, probably a redirect back to the bill. Maybe a redirect to the rules page...

**Extra info**
Testes on Chrome and Edge.
Both give the same error.
Screenshot (in German but Error is English) attached.

![image](https://user-images.githubusercontent.com/12135433/54806027-7c374580-4c81-11e9-87a0-5a47291e408d.png)

Thanks for looking into this!

**Comment by JC5** [comment] 2019-03-22 08:07
Yep, that looks like a bug. Thanks!

**Comment by Codingroller** [comment] 2019-05-22 14:18
I have the same thing happening when running a rule. What can be the cause of this?

**Comment by JC5** [comment] 2019-05-22 15:11
It's a bug. I have not had the time to fix it. Sorry about that.

**Comment by chrisvel** [comment] 2019-07-11 07:03
Same here

**Comment by JC5** [comment] 2019-08-01 19:07
Will be fixed in the next release

**Closed** 2019-08-09 19:03 UTC
Labels: bug, fixed
