### ISSUE TITLE
Unauthenticated (401) on /transactions with remote auth

### ISSUE THREAD

**Issue by weimdall** [firefly-iii/firefly-iii#5847] opened 2022-03-03 22:47 UTC
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

-- This only happen while using remote guard headers to authenticate user --
When I try to edit / create a transaction, the resulting xhr request (`POST /api/v1/transactions?_token=XxXxXxXxXxX`) get the error code `401 Unauthorized` with the following body :
`{"message":"Unauthenticated","exception":"AuthenticationException"}`

### Expected behaviour

I expected to be able to edit / create / delete transactions as in 5.6.14

### Debug information

Debug information generated at 2022-03-03 17:40:54 America/XX for Firefly III version **5.6.16**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.16 |
| Firefly III API | 1.5.5 |
| Build | 113, 02-03-2022 19:39:22 CET |
| PHP | 8.0.16 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| Layout | v1 |
| System TZ | America/XX |
| Browser TZ | America/XX |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2022-03-01 00:00:00 |
| Session end | 2022-03-31 23:59:59 |
| Session first | 2018-08-16 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |

### Steps to reproduce

Configure firefly in "Remote Guard" mode.
Try to edit or create a transaction.
You should get the following error :
![2022-03-02-174043_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/156665450-d612cbc7-73f1-4773-bcc2-839bbda1bea3.png)

### Additional info

After a git bisect, I got the commit that introduced this bug : aa7d4a610b56829ff77ece47dbfd10629d8dba3e 
Therefore, I assume this is somehow due to Sanctum not knowing about remote authentication headers ?

**Comment by TheSander562** [comment] 2022-03-06 13:35
I got the same error after trying to create a transaction. But the weird thing is i could just create and edit a piggy-bank.
If you need some things to help locate the problem i would be willing to help.

**Comment by JC5** [comment] 2022-03-07 14:43
Which remote authentication proxy are you using? I can't replicate this using Authelia.

**Comment by TheSander562** [comment] 2022-03-07 14:50
I also use Authelia with Nginx Proxy Manager setup.
This is how i set it up:
`auth_request /authelia;
		auth_request_set $target_url $scheme://$http_host$request_uri;
		auth_request_set $user $upstream_http_remote_user;
		auth_request_set $groups $upstream_http_remote_groups;
		auth_request_set $name $upstream_http_remote_name;
		auth_request_set $email $upstream_http_remote_email;
		proxy_set_header Remote-User $email;
		proxy_set_header Remote-Groups $groups;
		proxy_set_header Remote-Name $name;
		proxy_set_header Remote-Email $email;
		proxy_set_header X-Forwarded-User $remote_user;`

So it uses Remote-User which uses the email of Authelia.
Maybe you did something else there?

**Comment by JC5** [comment] 2022-03-07 14:59
I have the exact same setup:

```
auth_request /authelia;

auth_request_set $target_url $scheme://$http_host$request_uri;

auth_request_set $user $upstream_http_remote_user;
auth_request_set $groups $upstream_http_remote_groups;
auth_request_set $name $upstream_http_remote_name;
auth_request_set $email $upstream_http_remote_email;

proxy_set_header Remote-User $email;
proxy_set_header Remote-Groups $groups;
proxy_set_header Remote-Name $name;
proxy_set_header Remote-Email $email;

error_page 401 =302 https://authelia.sd.home/?rd=$target_url;

```

Here's my `.env` (it's a basic debug setup):

```
AUTHENTICATION_GUARD=remote_user_guard
AUTHENTICATION_GUARD_HEADER=Remote-User
AUTHENTICATION_GUARD_EMAIL=
```

**Comment by JC5** [comment] 2022-03-07 16:29
What's the Firefly III config in authelia?

**Comment by TheSander562** [comment] 2022-03-07 16:33
What do you mean by that? Like do yoy want the full Custom Nginx Configuration?
Because in Authelia there is nothing specific specified for Firefly. Only the headers but the come through Nginx Proxy Manager.

**Comment by JC5** [comment] 2022-03-07 17:00
The email header doesn't change much. The root cause is something else, but I have no idea what.

**Comment by weimdall** [comment] 2022-03-07 17:28
I would propose a minimal configuration (dockerized version of firefly and Nginx)  to reproduce this bug.

### Firefly
I use the dockerized version of firefly, available on 127.0.0.1:8080 with the following conf :
```
[...]
AUTHENTICATION_GUARD=remote_user_guard
AUTHENTICATION_GUARD_HEADER=REMOTE_USER
AUTHENTICATION_GUARD_EMAIL=
```

### Nginx 
I configured Nginx as a reverse proxy, and added the REMOTE_USER header.
```
location / {
  proxy_pass                              http://127.0.0.1:8080;
  proxy_set_header REMOTE_USER            "me@foo.bar";
  proxy_set_header X-Forwarded-For        $remote_addr;                                                  
  proxy_set_header X-Forwarded-Host       $host;
  proxy_set_header X-Forwarded-Proto      $scheme;
  proxy_set_header X-Forwarded-Port       $server_port;
}
```

### Result
From there, I access firefly through nginx, authenticated as me@foo.bar.
I can navigate through the interface, but cannot edit / create / delete transactions (401).

**Comment by JC5** [comment] 2022-03-07 19:55
I have the exact same minimum set up, and it works.

```yaml
version: '3.3'

services:
  firefly:
    image: fireflyiii/core:develop
    env_file: /Users/sander/Sites/FF3/release/firefly-iii/.env
    #volumes:
      #- '/Users/sander/Sites/FF3/release/firefly-iii:/var/www/html'
    depends_on:
      - db
      - redis
  db:
    image: mariadb    
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - '/Users/sander/Sites/FF3/dev/authelia/db:/var/lib/mysql'
  reverse:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - '/Users/sander/Sites/FF3/dev/authelia/nginx-config:/etc/nginx'
    depends_on:
      - authelia
      - firefly
  authelia:
    hostname: authelia
    image: authelia/authelia
    env_file: .env
    volumes:
      - '/Users/sander/Sites/FF3/dev/authelia/config:/config'
  redis:
    image: redis
```

auth.conf
```
# Basic Authelia Config
# Send a subsequent request to Authelia to verify if the user is authenticated
# and has the right permissions to access the resource.
auth_request /authelia;

# Set the `target_url` variable based on the request. It will be used to build the portal
# URL with the correct redirection parameter.

auth_request_set $target_url $scheme://$http_host$request_uri;

# Set the X-Forwarded-User and X-Forwarded-Groups with the headers
# returned by Authelia for the backends which can consume them.
# This is not safe, as the backend must make sure that they come from the
# proxy. In the future, it's gonna be safe to just use OAuth.

auth_request_set $user $upstream_http_remote_user;
auth_request_set $groups $upstream_http_remote_groups;
auth_request_set $name $upstream_http_remote_name;
auth_request_set $email $upstream_http_remote_email;

proxy_set_header Remote-User $email;
proxy_set_header Remote-Groups $groups;
proxy_set_header Remote-Name $name;
proxy_set_header Remote-Email $email;

# If Authelia returns 401, then nginx redirects the user to the login portal.
# If it returns 200, then the request pass through to the backend.
# For other type of errors, nginx will handle them as usual.

error_page 401 =302 https://authelia.sd.home/?rd=$target_url;

```
authelia.conf
```
#
# Generic Authelia file that should be capable of validating ANY website.
#

set $upstream_authelia http://authelia:9091/api/verify;

# Virtual endpoint created by nginx to forward auth requests.
location /authelia {
    internal;
    proxy_pass_request_body off;
    proxy_pass $upstream_authelia;
    proxy_set_header Content-Length "";

    # Timeout if the real server is dead
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

    # [REQUIRED] Needed by Authelia to check authorizations of the resource.
    # Provide either X-Original-URL and X-Forwarded-Proto or
    # X-Forwarded-Proto, X-Forwarded-Host and X-Forwarded-Uri or both.
    # Those headers will be used by Authelia to deduce the target url of the user.
    # Basic Proxy Config
    
    client_body_buffer_size 128k;
    proxy_set_header Host $host;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Method $request_method;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Uri $request_uri;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_redirect  http://  $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 4 32k;

    # Advanced Proxy Config
    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;
}

```
default.conf
```
server {
    server_name firefly-authelia.sd.home;
    listen 80;
    return 301 https://$server_name$request_uri;
}

server {
    server_name firefly-authelia.sd.home;
    listen 443 ssl http2;
    include /etc/nginx/tls.conf;
    include /etc/nginx/authelia.conf; # Virtual endpoint to forward auth requests

    location / {
        proxy_pass http://firefly:8080;
        include /etc/nginx/auth.conf; # Activates Authelia for specified route/location, please ensure you have setup the domain in your configuration.yml
        include /etc/nginx/proxy.conf; # Reverse proxy configuration
    }
}

```

proxy.conf

```
#
# looks like this config is specific for the authelia portal, which is not hosted on the develop VM.
#

client_body_buffer_size 128k;

#Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Advanced Proxy Config
send_timeout 5m;
proxy_read_timeout 360;
proxy_send_timeout 360;
proxy_connect_timeout 360;

# Basic Proxy Config
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 64 256k;

# If behind reverse proxy, forwards the correct IP
set_real_ip_from 10.0.0.0/8;
set_real_ip_from 172.16.0.0/12;
set_real_ip_from 192.168.0.0/16;
set_real_ip_from fc00::/7;
real_ip_header X-Forwarded-For;
real_ip_recursive on;


proxy_headers_hash_max_size 512;
```

**Comment by TheSander562** [comment] 2022-03-07 20:36
> I have the exact same minimum set up, and it works.
> 
> ```yaml
> services:
>   firefly:
>     image: fireflyiii/core:develop
>     env_file: /Users/james/Sites/FF3/release/firefly-iii/.env
>     #volumes:
>       #- '/Users/james/Sites/FF3/release/firefly-iii:/var/www/html'
>     depends_on:
>       - db
>       - redis
> ```

So are you using the develop image all the time for testing? Maybe it is fixed in the develop and still exists in the :latest tag.

**Comment by andrewzah** [comment] 2022-03-07 21:09
I just tried it on `core/develop@sha256:e704ca3cb07be2b5c6476f6624f47f2018274ad97c96adbb468bfe3f7c6cdf96`, and the issue is the same. I've documented my traefik + eas + keycloak setup in #5850.

**Comment by andrewzah** [comment] 2022-03-07 21:26
This error does **not** occur on `fireflyiii/core:version-5.6.7@sha256:b236e8df74b1d2da3d5479efdcd3b4f8a8104f9a1f1d7ad8d0090aa63e6769bb`.

**Comment by weimdall** [comment] 2022-03-08 04:34
Can someone try the change in #5863
On my side, it fixed the issue.

Though, as I mentioned in the PR, it's probably not a suitable solution,
but that would prove we all have the exact same issue.

**Comment by JC5** [comment] 2022-03-08 04:43
> So are you using the develop image all the time for testing? Maybe it is fixed in the develop and still exists in the :latest tag.

It still works for me in `latest`. 

> This issue does occur for me on:

Don't forget to mention traefik + eas + keycloak. Is everybody running this combination?

**Comment by weimdall** [comment] 2022-03-08 17:48
I build a minimal self-contained composer file to reproduce the bug
There are 3 services as I described above : firefly, maria-db and nginx

Run `docker-compose up`
And then test the bug on http://127.0.0.1:8080


```
version: '3.3'
services:
  fireflyiii:
    image: fireflyiii/core:latest
    entrypoint: /usr/local/bin/entrypoint.sh
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=fireflyiiidb
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=password
      - AUTHENTICATION_GUARD=remote_user_guard
      - AUTHENTICATION_GUARD_HEADER=REMOTE_USER
      - AUTHENTICATION_GUARD_EMAIL=
      - APP_URL=http://127.0.0.1:8080
      - TRUSTED_PROXIES=**
      - APP_ENV=testing
      - APP_KEY=base64:lg1m/12MHBbBpiWTXjot98Q9MP/nSzPrvLEU2beD+2Y=
    depends_on:
      - fireflyiiidb
  fireflyiiidb:
    image: yobasystems/alpine-mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=firefly
    volumes:
    - firefly_iii_db:/var/lib/mysql
  nginx:
    image: nginx:latest
    ports:
      - 127.0.0.1:8080:8080
    command: |
      bash -c 'bash -s <<EOF
      cat > /etc/nginx/nginx.conf <<EON
      daemon off;
      user www-data;
      events {
        worker_connections 100;
      }
      http {
        include /etc/nginx/mime.types;
        server {
          listen 8080;
          location / {
            proxy_pass                              http://fireflyiii:8080;
            proxy_set_header REMOTE_USER            "me@foo.bar";
            proxy_set_header X-Forwarded-For        127.0.0.1;
            proxy_set_header X-Forwarded-Host       127.0.0.1;
            proxy_set_header X-Forwarded-Proto      http;
            proxy_set_header X-Forwarded-Port       8080;
          }
        }
      }
      EON
      nginx
      EOF'

volumes:
   firefly_iii_upload:
   firefly_iii_db:
```

**Comment by MaxG88** [comment] 2022-03-11 17:44
I'm also getting the same error with version 5.6.15-5.6.16. I'm using Authelia with Nginx.
I'm only getting a generic "impossible to save transaction" message however, though the requests still return 401.
While I am not able to create or modify transactions, cloning works.
As with the others, everything works fine after rolling back to 5.6.14.

**Comment by JC5** [comment] 2022-03-11 17:47
Could you share details of your setup? I'm curious to hear what the difference is with the test-setup I shared. With this, I hope to be able to replicate this.

**Comment by MaxG88** [comment] 2022-03-11 18:51
My Nginx config is pretty much identical to what you specified here: https://github.com/firefly-iii/firefly-iii/issues/5847#issuecomment-1061075836

The only difference would be that I don't use docker-compose, both Nginx and PostgreSQL run in their own LXC "container", Authelia runs in its own Docker container and same thing for Firefly.

After further testing, I am getting the "Unauthenticated!" error only when creating a transaction. When editing an existing one, I get this:
![image](https://user-images.githubusercontent.com/14253281/157932966-fa1eac6a-2b03-4cd9-9217-0270341ae737.png)
but the errors are still 401
![image](https://user-images.githubusercontent.com/14253281/157933024-2eff8129-49e0-4b92-a238-6a57941ff2f7.png)

**Comment by JC5** [comment] 2022-03-12 00:05
Thanks for sharing some more information. Sadly, if you say "my config is pretty much identical" then all I can say is "well then it's pretty much your problem". In order to debug this I need to know how your nginx is set up, for example.

If you can't share enough details, I can't look for a solution.

**Comment by MaxG88** [comment] 2022-03-12 01:23
Sorry about that. Here it is:

firefly.example.com.conf
```
server {
	listen 443 ssl http2;

	server_name firefly.example.com;

	include /etc/nginx/config/ssl.conf;

	include /etc/nginx/config/authelia/authelia.conf;

	location / {
			proxy_pass http://1.2.3.4:9876;

			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection $connection_upgrade;

			include /etc/nginx/config/authelia/auth.conf;
			include /etc/nginx/config/authelia/proxy.conf;
        }
}
```

proxy.conf
```
client_body_buffer_size 128k;
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

send_timeout 5m;
proxy_read_timeout 360;
proxy_send_timeout 360;
proxy_connect_timeout 360;

proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 64 256k;

set_real_ip_from 10.0.0.0/8;
set_real_ip_from 172.0.0.0/8;
set_real_ip_from 192.168.0.0/16;
#set_real_ip_from fc00::/7;
real_ip_header X-Forwarded-For;
real_ip_recursive on;
```

authelia.conf
```
set $upstream_authelia http://1.2.3.4:9092/api/verify;
location /auth {
	internal;

	proxy_pass_request_body off;
	proxy_pass $upstream_authelia;
	proxy_set_header Content-Length "";

	proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

	client_body_buffer_size 128k;
	proxy_set_header Host $host;
	proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-Method $request_method;
	proxy_set_header X-Forwarded-For $remote_addr; 
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Forwarded-Host $http_host;
	proxy_set_header X-Forwarded-Uri $request_uri;
	proxy_set_header X-Forwarded-Ssl on;
	proxy_redirect  http://  $scheme://;
	proxy_http_version 1.1;
	proxy_set_header Connection "";
	proxy_cache_bypass $cookie_session;
	proxy_no_cache $cookie_session;
	proxy_buffers 4 32k;

	send_timeout 5m;
	proxy_read_timeout 240;
	proxy_send_timeout 240;
	proxy_connect_timeout 240;
}
```

auth.conf
```
auth_request /auth;
auth_request_set $target_url $scheme://$http_host$request_uri;
auth_request_set $user $upstream_http_remote_user;
auth_request_set $groups $upstream_http_remote_groups;
auth_request_set $name $upstream_http_remote_name;
auth_request_set $email $upstream_http_remote_email;
proxy_set_header X-Forwarded-User $user;
proxy_set_header X-Forwarded-Groups $groups;
proxy_set_header X-Forwarded-Name $name;
proxy_set_header X-Forwarded-Email $email;
error_page 401 =302 https://auth.example.com/?rd=$target_url;
```

**Comment by JC5** [comment] 2022-03-12 09:37
I see that your location block has these lines.

```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;
```
If I add the bottom line, I get a fatal error about missing $connection_upgrade. Where is the variable coming from? 



This line is enabled for me, but it doesn't make a difference (still works for me :( )

```
#set_real_ip_from fc00::/7;
```

**Comment by StillLoading** [comment] 2022-03-13 00:47
Can everyone who has the same issue please check their `APP_URL=` variable ? If it is non-default try removing the protocol or set it back to the default.

I had mine set to `APP_URL=https://firefly.my.domain` at some point. After fiddling around with http headers for the last 3 hours I took a look at similar issues with laravel and 401 errors. Which in turn brought me to the `SANCTUM_STATEFUL_DOMAINS` variable that "inherits" the `APP_URL`. Since it looks like the stateful check strips the protocol anyway, I thought why not remove that and see what happens. That did the trick.
TBH I don't understand why it works with `APP_URL=http://localhost` since it should compare either the request referer or request origin header to the domain list. I assume neither are localhost.

**Comment by MaxG88** [comment] 2022-03-13 01:24
@JC5 I don't quite remember where the variable is coming from, I believe it's for upgrading websocket connections.

@StillLoading Very good call, I tried removing it and now I can create/edit/delete transactions on 5.6.16!
Thanks!

**Comment by JC5** [comment] 2022-03-13 06:35
Very cool, we're getting there! I'll check out its behaviour right now.

**Comment by andrewzah** [comment] 2022-03-14 18:28
@StillLoading 

> Can everyone who has the same issue please check their `APP_URL=` variable ? If it is non-default try removing the protocol or set it back to the default.

Can confirm, this fixed it for me and my traefik/external-auth-server/keycloak setup on the latest development container.
```
fireflyiii/core:develop@sha256:f66023b331c3bf06f1804434a0a14c3c6dd6fb6bc8ae5646d1e379bc48c90be3
 ```

**Comment by TheSander562** [comment] 2022-03-14 20:58
> Can everyone who has the same issue please check their `APP_URL=` variable ? If it is non-default try removing the protocol or set it back to the default.
> 
> I had mine set to `APP_URL=https://firefly.my.domain` at some point. After fiddling around with http headers for the last 3 hours I took a look at similar issues with laravel and 401 errors. Which in turn brought me to the `SANCTUM_STATEFUL_DOMAINS` variable that "inherits" the `APP_URL`. Since it looks like the stateful check strips the protocol anyway, I thought why not remove that and see what happens. That did the trick. TBH I don't understand why it works with `APP_URL=http://localhost` since it should compare either the request referer or request origin header to the domain list. I assume neither are localhost.

Holy sht, this actually works. So I just removed APP_URL and it works now as i can edit and create new transactions.
I am on version: 
`fireflyiii/core:latest	- sha256:274f16140d43eaa9969d8c2d27e2b6a1d4b3843343d0c5ffab46b9c8ff6aacc5`

**Comment by gramakri** [comment] 2022-03-17 20:03
We have the same issue in the Cloudron package - https://forum.cloudron.io/topic/6637/error-unauthenticated . Cloudron uses LDAP though:

```
AUTHENTICATION_GUARD=ldap
```

I will try the APP_URL fix mention in the previous comments and report back but the comment in the env file says "It doesn't do ANYTHING" [here](https://github.com/firefly-iii/firefly-iii/blob/main/.env.example#L309) . In fact, it says it's only used when sending out email... :-)

**Comment by gramakri** [comment] 2022-03-17 20:07
I can confirm I can create a transaction by simply removing APP_URL

![image](https://user-images.githubusercontent.com/82041/158886388-2c747956-a201-48be-826e-fc3f94c01868.png)

So far from what I can tell, the new login emails and the test email don't have APP_URL in them. Does this mean we can remove that env entirely ?

**Comment by gramakri** [comment] 2022-03-17 20:10
@JC5 If it will help you debug, you can install Firefly-III at https://my.demo.cloudron.io (username and password is `cloudron`) . Then, you can login with the same credentials. If you try to create a transaction, you will see the error.

**Comment by gramakri** [comment] 2022-03-17 21:11
I tried debugging this a bit but my PHP foo is not good enough to go further.

Essentially, if you set the valid domain in the 'stateful' parameter of sanctum, it stops working. The code lands in https://github.com/laravel/sanctum/blob/master/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php#L22 . When `static::fromFrontend` returns false, which is the case when the app's domain is not there, it seems to continue processing the request at https://github.com/laravel/sanctum/blob/master/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php#L33 . But when `static::fromFrontend` returns 1, which is the case when the app's domain is there, it fails in one of the middleware functions in https://github.com/laravel/sanctum/blob/master/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php#L23 . 

Also, lots of help on sanctum refer to a `SESSION_DOMAIN` like [this](https://stackoverflow.com/questions/65761928/what-session-domain-should-i-use-if-im-using-laravel-sail) or [this](https://dev.to/nicolus/laravel-sanctum-explained-spa-authentication-45g1) . But I cannot find any reference of this in the code, not sure if that is relevant to all this.

**Comment by JC5** [comment] 2022-03-18 17:48
Thanks for debugging, @gramakri. I was planning to spend some time on this problem this weekend. The code of Sanctum will have to stay, and the APP_URL is also mandatory in some use cases.

Strangely enough, setting or unsetting the APP_URL does not change the behaviour in some cases (it works all the time). I am going to find out more and I will report back.

**Comment by JC5** [comment] 2022-03-19 05:55
I was able to reproduce the issue locally. Thanks for all the hints and your patience, guys.

**Comment by JC5** [comment] 2022-03-19 06:24
I would like you all to restore the `APP_URL` variable to its correct value (ie. `APP_URL=https://yourdomain`).

In addition, please set the following environment variable: `SANCTUM_STATEFUL_DOMAINS=localhost`.

It seems to work for me, and I hope this could be the solution. I believe this will already work on the current release, but you are free to test this on `:develop`.

**Comment by StillLoading** [comment] 2022-03-19 11:22
> I would like you all to restore the `APP_URL` variable to its correct value (ie. `APP_URL=https://yourdomain`).
> 
> In addition, please set the following environment variable: `SANCTUM_STATEFUL_DOMAINS=localhost`.
> 
> It seems to work for me, and I hope this could be the solution. I believe this will already work on the current release, but you are free to test this on `:develop`.

Tested, works on current release. But the behavior is still strange.

These all work:
```php
APP_URL=https://fqdn

#Empty
SANCTUM_STATEFUL_DOMAINS=
#my internal domain
SANCTUM_STATEFUL_DOMAINS=internal.domain
#any text whatsoever
SANCTUM_STATEFUL_DOMAINS=randomgibberish
```

**Comment by JC5** [comment] 2022-03-19 16:12
Empty didn't work for me, but I'll check it out. I still have to debug this in combination with the new v3 layout.

Thanks for the extra info!

**Comment by viharm** [comment] 2022-03-20 20:25
I had the same issue on 5.6.16. _Docker_ with LDAP. Removed `APP_URL ` and it worked.

**Comment by JC5** [comment] 2022-03-28 17:56
I think I found the issue, but I'm not sure if it has any security implications. I would appreciate feedback on the latest `:develop`-image. It should work just fine with `APP_URL`.

If `SANCTUM_STATEFUL_DOMAINS` is set to your external host it may break, and I'm not sure yet why. It won't however, be set to that by default.

**Comment by TheSander562** [comment] 2022-03-28 18:03
> I think I found the issue, but I'm not sure if it has any security implications. I would appreciate feedback on the latest `:develop`-image. It should work just fine with `APP_URL`.
> 
> If `SANCTUM_STATEFUL_DOMAINS` is set to your external host it may break, and I'm not sure yet why. It won't however, be set to that by default.

Thank you for your work, but what should we remove/add/change in the config?

**Comment by JC5** [comment] 2022-03-28 18:06
I hope that this change means you can leave your configuration as it was before.

**Comment by weimdall** [comment] 2022-04-02 15:39
Everything is working fine on :develop image for me :+1:

**Comment by TheSander562** [comment] 2022-04-07 10:09
It works for me too on the :develop image.

**Closed** 2022-04-12 11:04 UTC
Labels: bug
